
#=====================================================
# VEROBOSITY
#=====================================================

/control/execute  mac/verbose.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# World
/gate/world/geometry/setXLength 50 cm
/gate/world/geometry/setYLength 50 cm
/gate/world/geometry/setZLength 50 cm
/gate/world/setMaterial Air
/gate/world/vis/setVisible 1
/gate/world/vis/forceWireframe

# Voxel phantom
#/gate/world/daughters/name mouse
#/gate/world/daughters/insert regularMatrix
#/gate/mouse/geometry/insertReader interfile
#/gate/mouse/interfileReader/insertTranslator range
#/gate/mouse/interfileReader/rangeTranslator/readTable data/range_geo.dat
#/gate/mouse/interfileReader/readFile data/CT_128_128_250_16uint.iff

/gate/world/daughters/name                      mouse
/gate/world/daughters/insert                    ImageRegularParametrisedVolume
/gate/mouse/geometry/setRangeToMaterialFile     data/range_geo.dat
/gate/mouse/geometry/setImage                   data/CT_128_128_250_16uint.mhd
/gate/mouse/setSkipEqualMaterials 0

/gate/mouse/vis/forceWireframe

#=====================================================
# PHYSICS
#=====================================================

/gate/physics/addPhysicsList emstandard_opt3

#=====================================================
# DETECTORS
#=====================================================

/gate/actor/addActor                                DoseActor  doseDistribution
/gate/actor/doseDistribution/attachTo    	    mouse
/gate/actor/doseDistribution/stepHitType            random
/gate/actor/doseDistribution/setSize                25.6 25.6 50. mm
/gate/actor/doseDistribution/setPosition            0 0 0 cm
/gate/actor/doseDistribution/setResolution          128 128 250
/gate/actor/doseDistribution/enableEdep             true
/gate/actor/doseDistribution/enableUncertaintyEdep  true
/gate/actor/doseDistribution/enableSquaredEdep      false
/gate/actor/doseDistribution/enableDose             true
/gate/actor/doseDistribution/enableUncertaintyDose  true
/gate/actor/doseDistribution/enableSquaredDose      false
/gate/actor/doseDistribution/enableNumberOfHits     true
/gate/actor/doseDistribution/save                   output/mouse.mhd


/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/stat-mouse.txt
/gate/actor/stat/saveEveryNSeconds 60

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

#=====================================================
# SOURCE :
#=====================================================

#Source from PET image
/control/execute    mac/source131I.mac


#=====================================================
# VISUALISATION
#=====================================================

#/vis/disable
#/control/execute  visu.mac

#=====================================================
# RANDOM
#=====================================================
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

#=====================================================
# START
#=====================================================

/gate/application/noGlobalOutput
/vis/disable
/gate/application/setTotalNumberOfPrimaries 40000000
/gate/application/start
