
#=================================================================================================
#    Electromagnetic  processes : physics list standard option 3 
#=================================================================================================

/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel

/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel StandardModel

/gate/physics/addProcess GammaConversion
/gate/physics/processes/GammaConversion/setModel StandardModel

/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/processes/ElectronIonisation/setModel StandardModel e+

/gate/physics/addProcess Bremsstrahlung e-
/gate/physics/addProcess Bremsstrahlung e+
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+

/gate/physics/addProcess PositronAnnihilation e+

/gate/physics/addProcess eMultipleScattering e+
/gate/physics/addProcess eMultipleScattering e-
/gate/physics/processes/eMultipleScattering/setModel Urban95Model e-
/gate/physics/processes/eMultipleScattering/setModel Urban95Model e+

/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e- distanceToBoundary
/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e+ distanceToBoundary

#=================================================================================================
# Additional processes not included in the list option 3
#=================================================================================================

/gate/physics/addProcess RayleighScattering
/gate/physics/processes/RayleighScattering/setModel PenelopeModel


/gate/physics/setEMin 1 keV
/gate/physics/setEMax 10 GeV
/gate/physics/setDEDXBinning 220 
/gate/physics/setLambdaBinning 220 

/gate/physics/processList Enabled 
/gate/physics/processList Initialized


#==================================================================================================
# customized CUTS 
#==================================================================================================


/gate/physics/Gamma/SetCutInRegion      world 0.1 mm
/gate/physics/Electron/SetCutInRegion   world 0.1 mm
/gate/physics/Positron/SetCutInRegion   world 0.1 mm

/gate/physics/Gamma/SetCutInRegion      mouse 0.01 mm
/gate/physics/Electron/SetCutInRegion   mouse 0.01 mm
/gate/physics/Positron/SetCutInRegion   mouse 0.01 mm

#1/20 of dosel size
/gate/physics/processes/ElectronIonisation/setStepFunction e+ 0.1 0.005 mm
/gate/physics/processes/ElectronIonisation/setStepFunction e- 0.1 0.005 mm


/gate/physics/displayCuts



