#=====================================================
# GEOMETRY
#=====================================================

# -----------------------------------------------------
# Fluorescent box

/gate/world/daughters/name        fluoBox
/gate/world/daughters/insert      box
/gate/fluoBox/setMaterial         Iodine
/gate/fluoBox/geometry/setXLength 10 cm
/gate/fluoBox/geometry/setYLength 10 cm
/gate/fluoBox/geometry/setZLength 10 cm

#=====================================================
# ACTOR
#=====================================================

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/stat-{out}.txt
/gate/actor/stat/saveEveryNSeconds 60

/gate/actor/addActor          EnergySpectrumActor    spectrum
/gate/actor/spectrum/attachTo                        fluoBox
/gate/actor/spectrum/energySpectrum/setEmin          0 keV
/gate/actor/spectrum/energySpectrum/setEmax          110 keV
/gate/actor/spectrum/energySpectrum/setNumberOfBins  300
/gate/actor/spectrum/energyLossHisto/setEmin         0 keV
/gate/actor/spectrum/energyLossHisto/setEmax         110 keV
/gate/actor/spectrum/energyLossHisto/setNumberOfBins 300
/gate/actor/spectrum/save                            output/{out}.root

/gate/actor/spectrum/addFilter                       particleFilter
/gate/actor/spectrum/particleFilter/addParticle      gamma

#=====================================================
# CUTS
#=====================================================

/gate/physics/Gamma/SetCutInRegion      fluoBox 10.0 nm
/gate/physics/Electron/SetCutInRegion   fluoBox 1.0 nm
/gate/physics/Positron/SetCutInRegion   fluoBox 1.0 nm
