#=====================================================
# GEOMETRY
#=====================================================

# -----------------------------------------------------
# Fluorescent voxelised phantom

/gate/world/daughters/name                     fluoPhantom
/gate/world/daughters/insert                   ImageNestedParametrisedVolume
/gate/fluoPhantom/geometry/SetImage            data/voxelisedPhantom.mhd
/gate/fluoPhantom/geometry/SetHUToMaterialFile data/HUmat.txt
/gate/fluoPhantom/placement/setTranslation     0.5 0.5 0.5 mm

#=====================================================
# ACTOR
#=====================================================

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/stat-{out}.txt
/gate/actor/stat/saveEveryNSeconds 60

/gate/actor/addActor          EnergySpectrumActor    spectrum
/gate/actor/spectrum/attachTo                        fluoPhantom
/gate/actor/spectrum/energySpectrum/setEmin          0 keV
/gate/actor/spectrum/energySpectrum/setEmax          110 keV
/gate/actor/spectrum/energySpectrum/setNumberOfBins  300
/gate/actor/spectrum/energyLossHisto/setEmin         0 keV
/gate/actor/spectrum/energyLossHisto/setEmax         110 keV
/gate/actor/spectrum/energyLossHisto/setNumberOfBins 300
/gate/actor/spectrum/save                            output/{out}.root

/gate/actor/spectrum/addFilter                       particleFilter
/gate/actor/spectrum/particleFilter/addParticle      gamma

#=====================================================
# CUTS
#=====================================================

/gate/physics/Gamma/SetCutInRegion      fluoPhantom 10.0 nm
/gate/physics/Electron/SetCutInRegion   fluoPhantom 1.0 m
/gate/physics/Positron/SetCutInRegion   fluoPhantom 1.0 m
