/vis/open OGLSX
/vis/drawVolume
/vis/viewer/flush
/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate

/vis/scene/add/axes            0 0 0 50 mm
/vis/scene/add/text            1 0 0 cm  20 0 0   X
/vis/scene/add/text            0 1 0 cm  20 0 0   Y
/vis/scene/add/text            0 0 1 cm  20 0 0   Z
#/vis/viewer/set/auxiliaryEdge true

# This orientation : look from patient feet
/vis/viewer/set/viewpointThetaPhi 30 50
#/vis/viewer/set/viewpointVector 0 0 1




