
/gate/physics/addPhysicsList QGSP_BIC_HP_EMY
#/gate/physics/addPhysicsList QGSP_FTFP_BERT
#/gate/physics/addPhysicsList QGSP_BERT_HP_EMY

/gate/physics/Gamma/SetCutInRegion      world 10 km
/gate/physics/Electron/SetCutInRegion   world 10 km
/gate/physics/Proton/SetCutInRegion     world 10 km
/gate/physics/Positron/SetCutInRegion   world 10 km

/gate/physics/Gamma/SetCutInRegion      Box 1 mm
/gate/physics/Proton/SetCutInRegion     Box 1 mm
/gate/physics/Electron/SetCutInRegion   Box 1 km
/gate/physics/Positron/SetCutInRegion   Box 1 km

# StepLimiter *required*
/gate/physics/SetMaxStepSizeInRegion Box 1 mm
/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter deuteron
/gate/physics/ActivateStepLimiter triton
/gate/physics/ActivateStepLimiter alpha
/gate/physics/ActivateStepLimiter GenericIon

#/gate/physics/SetMinKineticEnergyInRegion Box 100 MeV
#/gate/physics/ActivateSpecialCuts proton

/gate/physics/displayCuts
