
/gate/source/addSource mybeam gps
/gate/source/mybeam/gps/particle        proton
/gate/source/mybeam/gps/direction       1 0 0

/gate/source/mybeam/gps/pos/type        Beam
/gate/source/mybeam/gps/pos/shape       Circle
/gate/source/mybeam/gps/pos/centre      -40 0 0 cm
/gate/source/mybeam/gps/pos/radius      4. mm
/gate/source/mybeam/gps/pos/sigma_r     2 mm
/gate/source/mybeam/gps/pos/rot1        0 1 0
/gate/source/mybeam/gps/pos/rot2        0 0 1

/gate/source/mybeam/gps/ene/type        Mono
/gate/source/mybeam/gps/ene/mono        {PMAX} MeV
