
#=====================================================
# VERBOSE
#=====================================================

/control/execute mac/verbose.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# World
/gate/world/geometry/setXLength 5 m
/gate/world/geometry/setYLength 5 m
/gate/world/geometry/setZLength 5 m
/gate/world/setMaterial Air
/gate/world/vis/setVisible 0

#Outer titanium capsule
/gate/world/daughters/name             TitaniumOuter
/gate/world/daughters/insert           cylinder
/gate/TitaniumOuter/geometry/setRmin 0 mm
/gate/TitaniumOuter/geometry/setRmax 0.4 mm
/gate/TitaniumOuter/geometry/setPhiStart 0 deg
/gate/TitaniumOuter/geometry/setDeltaPhi 360 deg
/gate/TitaniumOuter/geometry/setHeight 5 mm
/gate/TitaniumOuter/placement/setTranslation 0.0 0.0 0.0 mm
/gate/TitaniumOuter/setMaterial Titanium
/gate/TitaniumOuter/vis/setVisible 0
/gate/TitaniumOuter/vis/setColor yellow

# Inner Titanium capsule
/gate/TitaniumOuter/daughters/name            TitaniumInner
/gate/TitaniumOuter/daughters/insert           cylinder
/gate/TitaniumInner/geometry/setRmin 0 mm
/gate/TitaniumInner/geometry/setRmax 0.32 mm
/gate/TitaniumInner/geometry/setPhiStart 0 deg
/gate/TitaniumInner/geometry/setDeltaPhi 360 deg
/gate/TitaniumInner/geometry/setHeight 4.84 mm
/gate/TitaniumInner/placement/setTranslation 0.0 0.0 0.0 mm
/gate/TitaniumInner/setMaterial Titanium
/gate/TitaniumInner/vis/setVisible 0
/gate/TitaniumInner/vis/setColor green

# Carbon coating containing iodine
/gate/TitaniumInner/daughters/name           CarbonCoat
/gate/TitaniumInner/daughters/insert           cylinder
/gate/CarbonCoat/geometry/setRmin 0 mm
/gate/CarbonCoat/geometry/setRmax 0.225 mm
/gate/CarbonCoat/geometry/setPhiStart 0 deg
/gate/CarbonCoat/geometry/setDeltaPhi 360 deg
/gate/CarbonCoat/geometry/setHeight 4.0 mm
/gate/CarbonCoat/placement/setTranslation 0.0 0.0 0.0 mm
/gate/CarbonCoat/setMaterial Carbon
/gate/CarbonCoat/vis/setVisible 0
/gate/CarbonCoat/vis/setColor red

#Tungsten marker
/gate/CarbonCoat/daughters/name            TungstenMarker
/gate/CarbonCoat/daughters/insert           cylinder
/gate/TungstenMarker/geometry/setRmin 0 mm
/gate/TungstenMarker/geometry/setRmax 0.125 mm
/gate/TungstenMarker/geometry/setPhiStart 0 deg
/gate/TungstenMarker/geometry/setDeltaPhi 360 deg
/gate/TungstenMarker/geometry/setHeight 3.7 mm
/gate/TungstenMarker/placement/setTranslation 0.0 0.0 0.0 mm
/gate/TungstenMarker/setMaterial Tungsten
/gate/TungstenMarker/vis/setVisible 0
/gate/TungstenMarker/vis/setColor green

#/gate/patient/geometry/enableBoundingBoxOnly            true

#=====================================================
# PHYSICS
#=====================================================

/gate/physics/addPhysicsList emstandard_opt3

/gate/physics/Gamma/SetCutInRegion      TitaniumOuter 0.1 mm
/gate/physics/Electron/SetCutInRegion   TitaniumOuter 1 m

/gate/physics/displayCuts

#=====================================================
# DETECTORS
#=====================================================

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/stat-writePhS.txt
/gate/actor/stat/saveEveryNSeconds 60

/gate/actor/addActor PhaseSpaceActor PHS_SOURCE
/gate/actor/PHS_SOURCE/attachTo TitaniumOuter
/gate/actor/PHS_SOURCE/useVolumeFrame 1
/gate/actor/PHS_SOURCE/save output/TitaniumOuter.root

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

# Enable the following lines to display available and enabled processes
# /gate/physics/processList Available
# /gate/physics/processList Enabled

#=====================================================
# BEAMS
#=====================================================

/control/execute mac/sourceIodine.mac

#=====================================================
# START BEAMS
#=====================================================

# JamesRandom Ranlux64 MersenneTwister
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed random

/gate/application/noGlobalOutput
/vis/disable
/gate/application/setTotalNumberOfPrimaries 1000000
/gate/application/start
