#  *********************************************************************
#  * DISCLAIMER                                                        *
#  *                                                                   *
#  * Neither the authors of this software system, nor their employing  *
#  * institutes, nor the agencies providing financial support for this *
#  * work make any representation or warranty, express or implied,     *
#  * regarding this software system or assume any liability for its    *
#  * use.                                                              *
#  *                                                                   *
#  * This code implementation is the intellectual property of the      *
#  * OpenGATE collaboration.                                           *
#  * By copying, distributing or modifying the Program (or any work    *
#  * based on the Program) you indicate your acceptance of this        *
#  * statement, and all its terms.                                     *
#  *********************************************************************


# V I S U A L I S A T I O N
#####
#/vis/disable
/control/execute vis.mac

# M A N D A T O R Y
#####
/gate/geometry/setMaterialDatabase ../../GateMaterials.db


# G E O M E T R Y
#####

# World
# Define the world dimensions
##
/gate/world/geometry/setXLength 100 cm
/gate/world/geometry/setYLength 100 cm
/gate/world/geometry/setZLength 100 cm

# Scanner Head
# Create a new box representing the main head-volume
# SPECThead is the name of the predefined SPECT system
# Create the SPECT system, which will yield an Interfile output of projection data
##
/gate/world/daughters/name SPECThead
/gate/world/daughters/insert box
/gate/SPECThead/geometry/setXLength  7. cm
/gate/SPECThead/geometry/setYLength 21. cm
/gate/SPECThead/geometry/setZLength 30. cm
/gate/SPECThead/placement/setTranslation  20.0 0. 0. cm
/gate/SPECThead/setMaterial Air
/gate/SPECThead/repeaters/insert ring
/gate/SPECThead/ring/setRepeatNumber 4
/gate/SPECThead/moves/insert orbiting
/gate/SPECThead/orbiting/setSpeed 0.15 deg/s
/gate/SPECThead/orbiting/setPoint1 0 0 0 cm
/gate/SPECThead/orbiting/setPoint2 0 0 1 cm
/gate/SPECThead/vis/forceWireframe


# Shielding
# Create the shielding volume
##
/gate/SPECThead/daughters/name shielding
/gate/SPECThead/daughters/insert box
/gate/shielding/geometry/setXLength  7. cm
/gate/shielding/geometry/setYLength 21. cm
/gate/shielding/geometry/setZLength 30. cm
/gate/shielding/placement/setTranslation  0. 0. 0. cm
/gate/shielding/setMaterial Lead
/gate/shielding/vis/setColor red
/gate/shielding/vis/forceWireframe


# Collimator
# Create a full volume defining the shape of the collimator
##
/gate/SPECThead/daughters/name collimator
/gate/SPECThead/daughters/insert box
/gate/collimator/geometry/setXLength 3. cm
/gate/collimator/geometry/setYLength 19. cm
/gate/collimator/geometry/setZLength 28. cm
/gate/collimator/placement/setTranslation  -2. 0. 0. cm
/gate/collimator/setMaterial Lead
/gate/collimator/vis/setColor red
/gate/collimator/vis/forceWireframe
#
# Insert the first hole of air in the collimator
##
/gate/collimator/daughters/name hole
/gate/collimator/daughters/insert hexagone
/gate/hole/geometry/setHeight 3. cm
/gate/hole/geometry/setRadius .15 cm
/gate/hole/placement/setRotationAxis 0 1 0
/gate/hole/placement/setRotationAngle 90 deg
/gate/hole/setMaterial Air
#
# Repeat the hole in an array
##
/gate/hole/repeaters/insert cubicArray
/gate/hole/cubicArray/setRepeatNumberX 1
/gate/hole/cubicArray/setRepeatNumberY 52
/gate/hole/cubicArray/setRepeatNumberZ 44
/gate/hole/cubicArray/setRepeatVector 0. 0.36  0.624 cm
#
# Repeat these holes in a linear
##
/gate/hole/repeaters/insert linear
/gate/hole/linear/setRepeatNumber 2
/gate/hole/linear/setRepeatVector 0. 0.18 0.312 cm


# CRYSTAL
# Create the crystal volume
##
/gate/SPECThead/daughters/name crystal
/gate/SPECThead/daughters/insert box
/gate/crystal/geometry/setXLength 1. cm
/gate/crystal/geometry/setYLength  19. cm
/gate/crystal/geometry/setZLength  28. cm
/gate/crystal/placement/setTranslation  0. 0. 0. cm
/gate/crystal/setMaterial NaI
/gate/crystal/vis/setColor yellow

# BACK-COMPARTMENT
# Create the back-compartment volume
##
/gate/SPECThead/daughters/name compartment
/gate/SPECThead/daughters/insert box
/gate/compartment/geometry/setXLength 2.5 cm
/gate/compartment/geometry/setYLength 19. cm
/gate/compartment/geometry/setZLength 28. cm
/gate/compartment/placement/setTranslation   1.75 0. 0. cm
/gate/compartment/setMaterial Glass
/gate/compartment/vis/setColor grey


# TABLE
# Create the table volume
##
/gate/world/daughters/name table
/gate/world/daughters/insert box
/gate/table/geometry/setXLength 0.6 cm
/gate/table/geometry/setYLength 8. cm
/gate/table/geometry/setZLength 34. cm
/gate/table/placement/setRotationAxis 0 0 1
/gate/table/placement/setRotationAngle 90 deg
/gate/table/placement/setTranslation 0. -5.3 0. cm
/gate/table/moves/insert translation
/gate/table/translation/setSpeed 0 0 0.04 cm/s
/gate/table/setMaterial Glass
/gate/table/vis/setColor grey


# PHANTOM
# Create the phantom volume
##
/gate/world/daughters/name Phantom
/gate/world/daughters/insert cylinder
/gate/Phantom/geometry/setRmax 5.  cm
/gate/Phantom/geometry/setRmin 0. cm
/gate/Phantom/geometry/setHeight 20. cm
/gate/Phantom/placement/setTranslation 0. 0. -6. cm
/gate/Phantom/moves/insert translation
/gate/Phantom/translation/setSpeed 0 0 0.04 cm/s
/gate/Phantom/setMaterial Water
/gate/Phantom/vis/setColor blue
/gate/Phantom/vis/forceWireframe


# SOURCE
# Add an extra object for source confinement
##
/gate/Phantom/daughters/name movsource
/gate/Phantom/daughters/insert cylinder
/gate/movsource/geometry/setRmax 2.  cm
/gate/movsource/geometry/setRmin 0. cm
/gate/movsource/geometry/setHeight 5. cm
/gate/movsource/placement/setTranslation 0. 0. -6. cm
/gate/movsource/setMaterial Water
/gate/movsource/vis/setColor magenta

# S Y S T E M
######
# The system acts as an interpretor between the GATE geometry and data outputs for reconstruction 
# in our case, the Interfile writer
# A system must know which components of the geometry are parts of the scanner, and what 
# their role are.
# For the moment, there is only a system SPECThead, which was built when the SPECThead volume
# was inserted. 
# The SPECThead system is made of three levels: base (for the head), crystal (for the crystal and crystal matrix) 
# and pixel (for individual crystals for pixellated gamma camera)
# For now, only the base of the system is attached to a volume: the volume SPECThead
# For the system to get information about your crystal, the level crystal must be attached to the volume 
# that has been defined for the scintillating crystal (crystal)
##

/gate/systems/SPECThead/crystal/attach crystal
/gate/systems/SPECThead/describe


# S E N S I T I V E   D E T E C T O R S
######
# GATE provides two sensitive detectors, which have two different functions
# Using them properly is very important for getting accurate results
##

# Crystal SD
#
# The crystal SD makes it possible to record hits in a sensitive volume (e.g.,. in a scintillation crystal)
# It must be attached to any volume for which hit-data must be obtained
# For recording hits in the NaI volume only, the name of which is crystal, this volume is attached 
# to the crystal SD
##

/gate/crystal/attachCrystalSD

# Phantom SD
#
# The phantom SD makes it possible to record Compton events in the volumes within the field of view
# This can provide information for result analysis to discriminate between 
# scattered and unscattered photons
# It must be attached to each and every volume for whom Compton interactions have to be recorded
##

/gate/Phantom/attachPhantomSD
/gate/movsource/attachPhantomSD
/gate/table/attachPhantomSD
/gate/compartment/attachPhantomSD
/gate/shielding/attachPhantomSD
/gate/SPECThead/attachPhantomSD
/gate/collimator/attachPhantomSD


#  P H Y S I C S
#####
/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel

/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel PenelopeModel

/gate/physics/addProcess RayleighScattering
/gate/physics/processes/RayleighScattering/setModel PenelopeModel

/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-

/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-

/gate/physics/addProcess MultipleScattering e-

/gate/physics/processList Enabled
/gate/physics/processList Initialized

#  C U T S
#####
# Cuts for particle in WORLD
##
/gate/physics/Gamma/SetCutInRegion      SPECThead 0.1 cm
/gate/physics/Electron/SetCutInRegion   SPECThead 1.0 cm


# I N I T I A L I Z A T I O N
#####

/gate/run/initialize

/control/execute secondPart.mac
