#################### Y90 Example source ####################
/gate/source/addSource  y90example fastY90 
/gate/source/y90example/setActivity 100 MBq

# to set a cutoff energy below which no bremsstrahlung is generated
# /gate/source/y90example/setMinBremEnergy 150 keV

# to modify the positron probability, true value is 31.86e-5
# /gate/source/y90example/setPositronProbability 0.01
############################################################


