#=====================================================
# VOXEL PATIENT
#=====================================================


# Generate materials from Hounsfield units
##########################################

/gate/HounsfieldMaterialGenerator/SetMaterialTable                  data/Schneider2000MaterialsTable.txt 
/gate/HounsfieldMaterialGenerator/SetDensityTable                   data/Schneider2000DensitiesTable.txt
/gate/HounsfieldMaterialGenerator/SetDensityTolerance               0.1 g/cm3
/gate/HounsfieldMaterialGenerator/SetOutputMaterialDatabaseFilename data/patient1-HUmaterials.db
/gate/HounsfieldMaterialGenerator/SetOutputHUMaterialFilename       data/patient1-HU2mat.txt
/gate/HounsfieldMaterialGenerator/Generate


/gate/world/daughters/name                      patient
/gate/world/daughters/insert                    ImageNestedParametrisedVolume

/gate/geometry/setMaterialDatabase              data/patient1-HUmaterials.db
/gate/patient/geometry/SetHUToMaterialFile      data/patient1-HU2mat.txt
/gate/patient/geometry/SetImage                 data/patient1-2mm.hdr


# Put the following image point at center
/gate/patient/placement/setTranslation                  0 0 0 mm
/gate/patient/geometry/TranslateTheImageAtThisIsoCenter 110 98 146 mm
