
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# Example of CT imaging.

#-------------------oooooOOOOO00000OOOOOooooo---------------------#


#=====================================================
# VERBOSE and VISUALISATION 
#=====================================================

/control/execute mac/verbose.mac
#/control/execute mac/visu.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# Generate materials from Hounsfield units
#/gate/HounsfieldMaterialGenerator/SetMaterialTable                  data/SimpleMaterialsTable.txt 
# /gate/HounsfieldMaterialGenerator/SetMaterialTable                  data/Schneider2000MaterialsTable.txt 
# /gate/HounsfieldMaterialGenerator/SetDensityTable                   data/Schneider2000DensitiesTable.txt
# /gate/HounsfieldMaterialGenerator/SetDensityTolerance               0.1 g/cm3
# /gate/HounsfieldMaterialGenerator/SetOutputMaterialDatabaseFilename data/patient-HUmaterials.db
# /gate/HounsfieldMaterialGenerator/SetOutputHUMaterialFilename       data/patient-HU2mat.txt
# /gate/HounsfieldMaterialGenerator/Generate

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    3.0 m
/gate/world/geometry/setYLength    3.0 m
/gate/world/geometry/setZLength    3.0 m

/gate/world/daughters/name                   autour
/gate/world/daughters/insert                 box
/gate/autour/setMaterial                     Air
/gate/autour/geometry/setXLength             2.9 m
/gate/autour/geometry/setYLength             2.9 m
/gate/autour/geometry/setZLength             2.9 m
/gate/autour/vis/forceSolid
/gate/autour/vis/setColor                    blue


/gate/autour/daughters/name                      patient
/gate/autour/daughters/insert                    ImageNestedParametrisedVolume

# /gate/geometry/setMaterialDatabase              data/patient-HUmaterials.db
# /gate/patient/geometry/SetHUToMaterialFile      data/patient-HU2mat.txt
# /gate/patient/geometry/SetImage                 data/patient-2mm.hdr

/gate/geometry/setMaterialDatabase              data/multislab.db
/gate/patient/geometry/SetHUToMaterialFile      data/HU2mat-water.txt
/gate/patient/geometry/SetImage                 data/multislab.hdr

# optional : dump used image
#/gate/patient/geometry/buildAndDumpLabeledImage  data/patient-2mm-labeled-NPV.hdr

/gate/patient/placement/setTranslation                  0 0 0 mm
#/gate/patient/geometry/TranslateTheImageAtThisIsoCenter 109.7 99.3 146.2 mm

# DETECTOR
/gate/autour/daughters/name                   detector
/gate/autour/daughters/insert                 box
/gate/detector/setMaterial                     Lead
/gate/detector/geometry/setXLength             20.0 cm
/gate/detector/geometry/setYLength             1 cm
/gate/detector/geometry/setZLength             20.0 cm
/gate/detector/placement/setTranslation        0 100 0 cm
/gate/detector/vis/forceSolid
/gate/detector/vis/setColor                    blue


#=====================================================
# PHYSICS
#=====================================================

/control/execute mac/physicslist_EM_std.mac

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      patient 0.5 mm
/gate/physics/Electron/SetCutInRegion   patient 0.01 mm
/gate/physics/Positron/SetCutInRegion   patient 0.5 mm

/gate/physics/Gamma/SetCutInRegion      detector 5 m
/gate/physics/Electron/SetCutInRegion   detector 5 m
/gate/physics/Positron/SetCutInRegion   detector 5 m

/gate/physics/SetMaxStepSizeInRegion    patient 0.1 mm

/gate/physics/displayCuts
/gate/physics/print output-gpu/physics.txt

#=====================================================
# DETECTORS
#=====================================================

# GPU Tracking
/gate/actor/addActor              TrackingGPUActor gpuactor
/gate/actor/gpuactor/attachTo     patient
/gate/actor/gpuactor/setCudaDeviceID 1
/gate/actor/gpuactor/setGPUBufferSize 3

/tracking/verbose 1

# Detector : flat panel
/gate/actor/addActor              ParticleInVolumeActor counter
/gate/actor/counter/save          output-gpu/output.mhd
/gate/actor/counter/attachTo      detector
/gate/actor/counter/setResolution 100 2 100

# Ddebug
/gate/actor/addActor              ParticleInVolumeActor counter2
/gate/actor/counter2/save          output-gpu/a.txt
/gate/actor/counter2/attachTo      detector
/gate/actor/counter2/setResolution 1 1 1

# Ddebug
/gate/actor/addActor         PhaseSpaceActor ps
/gate/actor/ps/save          output-gpu/ps.root
/gate/actor/ps/attachTo      autour


# Detector : energy spectrum
/gate/actor/addActor              EnergySpectrumActor es
/gate/actor/es/save          output-gpu/spectrum.root
/gate/actor/es/attachTo      detector
/gate/actor/es/energySpectrum/setEmin 0 eV
/gate/actor/es/energySpectrum/setEmax 10 MeV
/gate/actor/es/energySpectrum/setNumberOfBins 200
/gate/actor/es/energyLossHisto/setEmin 0 eV
/gate/actor/es/energyLossHisto/setEmax 10 MeV
/gate/actor/es/energyLossHisto/setNumberOfBins 120

# Set the names of the outputs
/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/saveEveryNSeconds 10
/gate/actor/stat/save              output-gpu/stat.txt

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

# Enable the following lines to display available and enabled processes
# /gate/physics/processList Available
# /gate/physics/processList Enabled

#=====================================================
# BEAMS
#=====================================================

/control/execute mac/beam-photon.mac

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries 10



/gate/application/start

