#	V I S U A L I S A T I O N
#/vis/open OGLSX
#/vis/viewer/set/viewpointThetaPhi 60 60
#/vis/viewer/zoom 10
#/vis/drawVolume
#/vis/viewer/flush
#/tracking/storeTrajectory 1
#/vis/scene/add/trajectories 
#/vis/scene/endOfEventAction accumulate


#/vis/open OGLIX 600x600-0+0
#/vis/sceneHandler/create OGLIX
#/vis/viewer/create ! ! 600x600-0+0
#/vis/viewer/refresh
#/vis/drawVolume
#/vis/scene/create
#/vis/scene/add/volume world
#/vis/sceneHandler/attach
#/vis/viewer/set/viewpointThetaPhi 90 180 deg
#/vis/viewer/zoom 1.4
#/vis/viewer/refresh
#/vis/scene/notifyHandlers


/control/verbose 2

/gate/verbose Geometry 5

/gate/geometry/setMaterialDatabase GateMaterials.db

# 
# V O X E L I Z E D  M A T R I X   Sebal   B R A I N   P H A N T O M
/gate/world/setMaterial Vacuum 
/gate/world/geometry/setXLength 10.0 m
/gate/world/geometry/setYLength 10.0 m
/gate/world/geometry/setZLength 10.0 m

/gate/world/daughters/name hof_brain
/gate/world/daughters/insert compressedMatrix
/gate/hof_brain/geometry/insertReader interfile
/gate/hof_brain/interfileReader/insertTranslator range
/gate/hof_brain/interfileReader/rangeTranslator/readTable AttenMap_brain.dat
/gate/hof_brain/interfileReader/rangeTranslator/describe 1
/gate/hof_brain/interfileReader/readFile AttenMap_32_32_16.h33
/gate/hof_brain/placement/setTranslation  0. 0. 0. mm
/gate/hof_brain/placement/setRotationAxis 1 0 0
/gate/hof_brain/placement/setRotationAngle 0 deg
/gate/hof_brain/attachVoxelPhantomSD
/gate/geometry/listVolumes

/gate/run/initialize

#	V I S U A L I S A T I O N
/vis/open OGLSX
/vis/viewer/set/viewpointThetaPhi 60 60
/vis/viewer/zoom 15
/vis/drawVolume
/vis/viewer/flush
/tracking/storeTrajectory 1
/vis/scene/add/trajectories 
/vis/scene/endOfEventAction accumulate

#/vis/drawVolume

