
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# Example of proton beam in water box with Pencil Beam Scanning
# source with a treatment plan obtained from a TPS.

#-------------------oooooOOOOO00000OOOOOooooo---------------------#

#=====================================================
# VERBOSE and VISUALISATION
#=====================================================

/control/execute mac/verbose.mac
#/control/execute mac/visu.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# World
/gate/world/geometry/setXLength 5 m
/gate/world/geometry/setYLength 5 m
/gate/world/geometry/setZLength 5 m
/gate/world/setMaterial Air

/gate/world/daughters/name             mainBoxEntrance
/gate/world/daughters/insert           box
/gate/mainBoxEntrance/geometry/setXLength 40 cm
/gate/mainBoxEntrance/geometry/setYLength 40 cm
/gate/mainBoxEntrance/geometry/setZLength 1 nm
/gate/mainBoxEntrance/placement/setTranslation 0.0 0.0 0.0 cm
/gate/mainBoxEntrance/setMaterial Water
/gate/mainBoxEntrance/vis/setVisible 1
/gate/mainBoxEntrance/vis/setColor yellow

#=====================================================
# PHYSICS
#=====================================================

/gate/physics/addPhysicsList QGSP_BERT_HP_EMY

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

# /gate/physics/Gamma/SetCutInRegion      mainbox 0.1 mm
# /gate/physics/Electron/SetCutInRegion   mainbox 0.1 mm
# /gate/physics/Positron/SetCutInRegion   mainbox 0.1 mm

/gate/physics/SetMaxStepSizeInRegion world 1 mm
/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter deuteron
/gate/physics/ActivateStepLimiter triton
/gate/physics/ActivateStepLimiter alpha
/gate/physics/ActivateStepLimiter GenericIon

/gate/physics/displayCuts

#=====================================================
# DETECTORS
#=====================================================

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/stat-proton.txt
/gate/actor/stat/saveEveryNSeconds 100

/gate/actor/addActor PhaseSpaceActor PHS_GLOBALBOX
/gate/actor/PHS_GLOBALBOX/attachTo mainBoxEntrance
#/gate/actor/PHS_GLOBALBOX/useVolumeFrame
/gate/actor/PHS_GLOBALBOX/save output/GlobalBoxEntrance2Beams.root

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

#=====================================================
# BEAMS
#=====================================================

/gate/source/addSource PBS TPSPencilBeam
/gate/source/PBS/setTestFlag false
/gate/source/PBS/setPlan data/PlanDescriptionToGATE.txt
#/gate/source/PBS/setNotAllowedFieldID 1
#/gate/source/PBS/setNotAllowedFieldID 2
/gate/source/PBS/setFlatGenerationFlag false
/gate/source/PBS/setSourceDescriptionFile data/Source-Properties.txt

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries 1000
/gate/application/start
