/gate/physics/addProcess PhotoElectric
/gate/physics/addProcess Compton
/gate/physics/addProcess GammaConversion

/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setStepFunction e+ 0.2 0.1 mm
/gate/physics/processes/ElectronIonisation/setStepFunction e- 0.2 0.1 mm

/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/activateSplitting e- 100
/gate/physics/processes/Bremsstrahlung/addFilter angleFilter secondaries
/gate/physics/processes/Bremsstrahlung/secondaries/angleFilter/setAngle 20
/gate/physics/processes/Bremsstrahlung/secondaries/angleFilter/setDirection 1 0 0

/gate/physics/addProcess PositronAnnihilation 

/gate/physics/addProcess MultipleScattering e+
/gate/physics/addProcess MultipleScattering e-
/gate/physics/processes/MultipleScattering/setGeometricalStepLimiterType e- distanceToBoundary
/gate/physics/processes/MultipleScattering/setGeometricalStepLimiterType e+ distanceToBoundary

/gate/physics/setEMin 0.1 keV
/gate/physics/setEMax 10 GeV
/gate/physics/setDEDXBinning 220
/gate/physics/setLambdaBinning 220
