
#=====================================
#    Electromagnetic  processes
#=====================================

/gate/physics/addProcess LowEnergyPhotoElectric
/gate/physics/addProcess LowEnergyCompton
/gate/physics/addProcess LowEnergyGammaConversion
/gate/physics/addProcess LowEnergyRayleighScattering

/gate/physics/addProcess LowEnergyBremsstrahlung e-
/gate/physics/addProcess LowEnergyElectronIonisation e-

/gate/physics/addProcess ElectronIonisation e+
/gate/physics/addProcess Bremsstrahlung e+
/gate/physics/addProcess PositronAnnihilation e+

/gate/physics/addProcess MultipleScattering
/gate/physics/processes/MultipleScattering/setGeometricalStepLimiterType e- distanceToBoundary
/gate/physics/processes/MultipleScattering/setGeometricalStepLimiterType e+ distanceToBoundary

/gate/physics/addProcess LowEnergyHadronIonisation mu+
/gate/physics/addProcess LowEnergyHadronIonisation mu-
/gate/physics/addProcess LowEnergyHadronIonisation tau+
/gate/physics/addProcess LowEnergyHadronIonisation tau-
/gate/physics/addProcess LowEnergyHadronIonisation pi+
/gate/physics/addProcess LowEnergyHadronIonisation pi-
/gate/physics/addProcess LowEnergyHadronIonisation kaon+
/gate/physics/addProcess LowEnergyHadronIonisation kaon-
/gate/physics/addProcess LowEnergyHadronIonisation sigma+
/gate/physics/addProcess LowEnergyHadronIonisation sigma-
/gate/physics/addProcess LowEnergyHadronIonisation proton
/gate/physics/addProcess LowEnergyHadronIonisation anti_proton
/gate/physics/addProcess LowEnergyHadronIonisation xi-
/gate/physics/addProcess LowEnergyHadronIonisation anti_xi-
/gate/physics/addProcess LowEnergyHadronIonisation anti_sigma+
/gate/physics/addProcess LowEnergyHadronIonisation anti_sigma-
/gate/physics/addProcess LowEnergyHadronIonisation omega-
/gate/physics/addProcess LowEnergyHadronIonisation anti_omega-
/gate/physics/processes/LowEnergyHadronIonisation/setModel Elec_Ziegler1977p

/gate/physics/addProcess IonIonisation
/gate/physics/processes/IonIonisation/setStepFunction GenericIon 0.1 0.02 mm
/gate/physics/processes/IonIonisation/setStepFunction alpha      0.1 0.02 mm
/gate/physics/processes/IonIonisation/setStepFunction deuteron   0.1 0.02 mm
/gate/physics/processes/IonIonisation/setStepFunction triton     0.1 0.02 mm
/gate/physics/processes/IonIonisation/setStepFunction He3        0.1 0.02 mm


#=====================================
#    Hadronic  processes 
#=====================================

/gate/physics/addProcess HadronElastic GenericIon
/gate/physics/processes/HadronElastic/setModel G4LElastic GenericIon

/gate/physics/addProcess UHadronElastic
/gate/physics/processes/UHadronElastic/setModel G4HadronElastic
/gate/physics/processes/UHadronElastic/setDataSet G4HadronElasticDataSet

/gate/physics/processes/UHadronElastic/setModel G4NeutronHPorLElastic neutron
/gate/physics/processes/UHadronElastic/G4HadronElastic/setEmin 19.9 MeV neutron
/gate/physics/processes/UHadronElastic/G4NeutronHPorLElastic/setEmax 20 MeV neutron

/gate/physics/addProcess ProtonInelastic
/gate/physics/processes/ProtonInelastic/setModel G4BinaryCascade
/gate/physics/processes/ProtonInelastic/G4BinaryCascade/setEmin 170 MeV
/gate/physics/processes/ProtonInelastic/G4BinaryCascade/setEmax 500 GeV
/gate/physics/processes/ProtonInelastic/setModel PreCompound
/gate/physics/processes/ProtonInelastic/PreCompound/setEmin 0 MeV
/gate/physics/processes/ProtonInelastic/PreCompound/setEmax 170 MeV

/gate/physics/addProcess IonInelastic
/gate/physics/processes/IonInelastic/setModel G4BinaryLightIonReaction
/gate/physics/processes/IonInelastic/setModel G4LEDeuteronInelastic deuteron
/gate/physics/processes/IonInelastic/setModel G4LETritonInelastic triton
/gate/physics/processes/IonInelastic/setModel G4LEAlphaInelastic alpha
/gate/physics/processes/IonInelastic/G4BinaryLightIonReaction/setEmin 80 MeV deuteron
/gate/physics/processes/IonInelastic/G4BinaryLightIonReaction/setEmax 20 GeV deuteron
/gate/physics/processes/IonInelastic/G4BinaryLightIonReaction/setEmin 80 MeV triton
/gate/physics/processes/IonInelastic/G4BinaryLightIonReaction/setEmax 20 GeV triton
/gate/physics/processes/IonInelastic/G4BinaryLightIonReaction/setEmin 80 MeV alpha
/gate/physics/processes/IonInelastic/G4BinaryLightIonReaction/setEmax 20 GeV alpha
/gate/physics/processes/IonInelastic/G4LEDeuteronInelastic/setEmin 0 MeV deuteron
/gate/physics/processes/IonInelastic/G4LEDeuteronInelastic/setEmax 80 MeV deuteron
/gate/physics/processes/IonInelastic/G4LETritonInelastic/setEmin 0 MeV triton
/gate/physics/processes/IonInelastic/G4LETritonInelastic/setEmax 80 MeV triton
/gate/physics/processes/IonInelastic/G4LEAlphaInelastic/setEmin 0 MeV alpha
/gate/physics/processes/IonInelastic/G4LEAlphaInelastic/setEmax 80 MeV alpha
/gate/physics/processes/IonInelastic/setDataSet G4IonsShenCrossSection GenericIon
/gate/physics/processes/IonInelastic/setDataSet G4TripathiLightCrossSection deuteron
/gate/physics/processes/IonInelastic/setDataSet G4TripathiLightCrossSection triton
/gate/physics/processes/IonInelastic/setDataSet G4TripathiLightCrossSection alpha

/gate/physics/addProcess PionPlusInelastic
/gate/physics/processes/PionPlusInelastic/setModel G4LEPionPlusInelastic

/gate/physics/addProcess PionMinusInelastic
/gate/physics/processes/PionMinusInelastic/setModel G4LEPionMinusInelastic


/gate/physics/addProcess NeutronCapture
/gate/physics/processes/NeutronCapture/setModel G4LCapture
/gate/physics/processes/NeutronCapture/setModel G4NeutronHPorLCapture
/gate/physics/processes/NeutronCapture/G4LCapture/setEmin 19.9 MeV
/gate/physics/processes/NeutronCapture/G4NeutronHPorLCapture/setEmax 20 MeV

/gate/physics/addProcess Fission
/gate/physics/processes/Fission/setModel G4LFission
/gate/physics/processes/Fission/setModel G4NeutronHPorLFission
/gate/physics/processes/Fission/G4LFission/setEmin 19.9 MeV neutron
/gate/physics/processes/Fission/G4NeutronHPorLFission/setEmax 20 MeV neutron

/gate/physics/addProcess NeutronInelastic
/gate/physics/processes/NeutronInelastic/setModel PreCompound
/gate/physics/processes/NeutronInelastic/setModel G4NeutronHPorLEInelastic
/gate/physics/processes/NeutronInelastic/PreCompound/setEmin 19.9 MeV neutron
/gate/physics/processes/NeutronInelastic/G4NeutronHPorLEInelastic/setEmax 20 MeV neutron

/gate/physics/addProcess Decay


#=====================================
#    Options
#=====================================

/gate/physics/setEMin 0.1 keV
/gate/physics/setEMax 10 GeV
/gate/physics/setDEDXBinning 220
/gate/physics/setLambdaBinning 220
