
# Visualisation
#/control/execute mac/visu.mac

# Verbosity
/control/execute mac/verbose.mac

# Geometry
/control/execute mac/world.mac
/control/execute mac/pet_head.mac
/control/execute mac/pet_digitizer.mac
/control/execute mac/cylindrical_phantom.mac

# Physics
/control/execute mac/physics.mac

# Output
/control/execute mac/output.mac

# Initialisation
/gate/run/initialize

# Source
/control/execute mac/sources.mac


# Random
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

# verbose
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# Start acquisition
/gate/application/setTimeStart 0 s
/gate/application/setTimeSlice 120 s
/gate/application/setTimeStop  240 s
/gate/application/startDAQ

# computation time around 2 min for 10 sec
# computation time around 1.3h for 240 sec