
/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/stat.txt
#/gate/actor/stat/saveEveryNSeconds 60


# Define a root listmode file output

/gate/output/root/enable
/gate/output/root/setFileName             output/pet

/gate/output/root/setRootHitFlag          0
/gate/output/root/setRootSinglesFlag      1
/gate/output/root/setRootCoincidencesFlag 1
/gate/output/root/setRootdelayFlag        1
/gate/output/root/setRootNtupleFlag       0


/gate/phantom/attachPhantomSD
