
# direct gamma/gamma emission

/gate/source/addSource twogamma
/gate/source/twogamma/setActivity 100 kBq
/gate/source/twogamma/setType backtoback
/gate/source/twogamma/gps/particle gamma
/gate/source/twogamma/gps/energytype Mono
/gate/source/twogamma/gps/monoenergy 0.511 MeV

/gate/source/twogamma/gps/shape 	Cylinder
/gate/source/twogamma/gps/radius 	0.5 mm
/gate/source/twogamma/gps/halfz 	0.5 mm
/gate/source/twogamma/gps/angtype 	iso
/gate/source/twogamma/gps/centre 	0. 0. 0. cm
/gate/source/twogamma/gps/centre 	5. 5. 0. cm

/gate/source/list
