
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# Example to use repeater/mover and both at the same time

#-------------------oooooOOOOO00000OOOOOooooo---------------------#


#=====================================================
# VERBOSE and VISUALISATION
#=====================================================

/control/execute mac/verbose.mac
#/control/execute mac/visu.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    5.0 m
/gate/world/geometry/setYLength    5.0 m
/gate/world/geometry/setZLength    5.0 m
/gate/world/vis/setVisible 0

### WATERBOX
/gate/world/daughters/name      mybox
/gate/world/daughters/insert    box
/gate/mybox/setMaterial         Aluminium
/gate/mybox/geometry/setXLength 50 mm
/gate/mybox/geometry/setYLength 50 mm
/gate/mybox/geometry/setZLength 50 mm
/gate/mybox/vis/setColor yellow

### translate & rotate mybox
/gate/mybox/placement/setTranslation   0 0 0 mm
/gate/mybox/placement/setRotationAxis  1 0 0
/gate/mybox/placement/setRotationAngle 30 deg

### Repeat the box with a generic repeater
/gate/mybox/moves/insert                               genericRepeaterMove
/gate/mybox/genericRepeaterMove/setPlacementsFilename  data/mybox_move_repeater.placements
/gate/mybox/genericRepeaterMove/useRelativeTranslation 1

#=====================================================
# PHYSICS
#=====================================================

/gate/physics/addPhysicsList emstandard_opt3

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      mybox 0.1 mm
/gate/physics/Electron/SetCutInRegion   mybox 0.1 mm
/gate/physics/Positron/SetCutInRegion   mybox 0.1 mm

/gate/physics/displayCuts
/gate/physics/print output/physics.txt

#=====================================================
# DETECTORS
#=====================================================

# ----------------------------------------------------
# the following actor regularly store the current number of
# event/track/step in a file

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/output-stat.txt
/gate/actor/stat/saveEveryNSeconds 6

/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  output/output.hdr
/gate/actor/doseDistribution/attachTo    	   mybox
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setVoxelSize          3 3 3 mm
/gate/actor/doseDistribution/setSize               300 300 300 mm
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep true
/gate/actor/doseDistribution/enableDose            true
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/saveEveryNSeconds     60

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

#=====================================================
# BEAMS
#=====================================================

# simple photon beam
/gate/source/addSource                mybeam gps
/gate/source/mybeam/setIntensity      10.
/gate/source/mybeam/gps/particle      gamma
/gate/source/mybeam/gps/ene/type      Mono
/gate/source/mybeam/gps/ene/mono      0.5 MeV
/gate/source/mybeam/gps/position      0 -100 0 mm
/gate/source/mybeam/gps/pos/type      Point
/gate/source/mybeam/gps/ang/type      iso
/gate/source/mybeam/gps/ang/mintheta  0. deg
/gate/source/mybeam/gps/ang/minphi    0. deg
/gate/source/mybeam/gps/ang/maxphi    360. deg
/gate/source/mybeam/gps/ang/rot1      1 0 0
/gate/source/mybeam/gps/ang/rot2      0 0 1
/gate/source/mybeam/gps/pos/rot1      1 0 0
/gate/source/mybeam/gps/pos/rot2      0 0 1
/gate/source/mybeam/gps/ang/maxtheta  0.4297223 deg


#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

/gate/application/setTimeStart 0 s
/gate/application/setTimeStop  5 s
/gate/application/setTimeSlice 1 s
/gate/application/setTotalNumberOfPrimaries 50
/gate/application/start
/gate/application/describe
