#=====================================================
# VERBOSITY
#=====================================================

/control/execute mac/verbose.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase            data/GateMaterials.db

/gate/world/setMaterial                       Air
/gate/world/geometry/setXLength               2 cm
/gate/world/geometry/setYLength               2 cm
/gate/world/geometry/setZLength               2 cm
/gate/world/vis/setVisible                    0

## Volume total 
/gate/world/daughters/name                    VolumeTot
/gate/world/daughters/insert                  box
/gate/VolumeTot/setMaterial                   Air 
/gate/VolumeTot/geometry/setXLength           2 cm
/gate/VolumeTot/geometry/setYLength           2 cm
/gate/VolumeTot/geometry/setZLength           2 cm
/gate/VolumeTot/vis/setColor                  white
/gate/VolumeTot/vis/forceWireframe

## Volume Lead 
/gate/VolumeTot/daughters/name                VolumeLead
/gate/VolumeTot/daughters/insert              box
/gate/VolumeLead/setMaterial                  Lead
/gate/VolumeLead/geometry/setXLength          1 cm
/gate/VolumeLead/geometry/setYLength          2 cm
/gate/VolumeLead/geometry/setZLength          2 cm
/gate/VolumeLead/placement/setRotationAxis    0 1 0 
/gate/VolumeLead/placement/setRotationAngle   90 deg 
/gate/VolumeLead/placement/setTranslation     0 0 0.5 cm
/gate/VolumeLead/vis/setColor                 gray
/gate/VolumeLead/vis/forceSolid

## Volume Gypsum 
/gate/VolumeLead/daughters/name               VolumeGypsum
/gate/VolumeLead/daughters/insert             box
/gate/VolumeGypsum/setMaterial                Gypsum
/gate/VolumeGypsum/geometry/setXLength        1 cm
/gate/VolumeGypsum/geometry/setYLength        1 cm
/gate/VolumeGypsum/geometry/setZLength        2 cm
/gate/VolumeGypsum/placement/setRotationAxis  1 0 0 
/gate/VolumeGypsum/placement/setRotationAngle 90 deg
/gate/VolumeGypsum/placement/setTranslation   0 0 0.5 cm
/gate/VolumeGypsum/vis/setColor               yellow
/gate/VolumeGypsum/vis/forceSolid

## Volume Carbon 
/gate/VolumeGypsum/daughters/name             VolumeCarbon
/gate/VolumeGypsum/daughters/insert           box
/gate/VolumeCarbon/setMaterial                Carbon
/gate/VolumeCarbon/geometry/setXLength        1 cm
/gate/VolumeCarbon/geometry/setYLength        1 cm
/gate/VolumeCarbon/geometry/setZLength        1 cm
/gate/VolumeCarbon/placement/setTranslation   0 0 -0.5 cm
/gate/VolumeCarbon/vis/setColor               green
/gate/VolumeCarbon/vis/forceSolid

## Volume Water 
/gate/VolumeTot/daughters/name                VolumeWater
/gate/VolumeTot/daughters/insert              box
/gate/VolumeWater/setMaterial                 Water 
/gate/VolumeWater/geometry/setXLength         2 cm
/gate/VolumeWater/geometry/setYLength         1 cm
/gate/VolumeWater/geometry/setZLength         2 cm
/gate/VolumeWater/placement/setRotationAxis   1 0 0 
/gate/VolumeWater/placement/setRotationAngle  90 deg
/gate/VolumeWater/placement/setTranslation    0 0 -0.5 cm
/gate/VolumeWater/vis/setColor                blue
/gate/VolumeWater/vis/forceSolid

## Volume Al 
/gate/VolumeWater/daughters/name              VolumeAl
/gate/VolumeWater/daughters/insert            box
/gate/VolumeAl/setMaterial                    Aluminium
/gate/VolumeAl/geometry/setXLength            1 cm
/gate/VolumeAl/geometry/setYLength            2 cm
/gate/VolumeAl/geometry/setZLength            1 cm
/gate/VolumeAl/placement/setRotationAxis      0 0 1 
/gate/VolumeAl/placement/setRotationAngle     90 deg
/gate/VolumeAl/placement/setTranslation       0 0 0.5 cm
/gate/VolumeAl/vis/setColor                   magenta
/gate/VolumeAl/vis/forceSolid

## Volume Air 
/gate/VolumeAl/daughters/name                 VolumeAir
/gate/VolumeAl/daughters/insert               box
/gate/VolumeAir/setMaterial                   Air
/gate/VolumeAir/geometry/setXLength           1 cm
/gate/VolumeAir/geometry/setYLength           1 cm
/gate/VolumeAir/geometry/setZLength           1 cm
/gate/VolumeAir/placement/setTranslation      0 0.5 0 cm
/gate/VolumeAir/vis/setColor                  white
/gate/VolumeAir/vis/forceSolid

#=====================================================
# BEAM
#=====================================================

/gate/source/addSource xraygun        gps
/gate/source/xraygun/gps/particle     gamma
/gate/source/xraygun/gps/energytype   Mono
/gate/source/xraygun/gps/ene/mono     100 keV
/gate/source/xraygun/gps/type         Plane
/gate/source/xraygun/gps/shape        Rectangle
/gate/source/xraygun/gps/pos/halfx    2 cm
/gate/source/xraygun/gps/pos/halfy    2 cm
/gate/source/xraygun/gps/pos/centre   0. 0. 2. cm
/gate/source/xraygun/gps/direction    0 0 -1

#=====================================================
# PHYSICS
#=====================================================

/gate/physics/addPhysicsList           emstandard_opt3

/gate/physics/Gamma/SetCutInRegion     world 10 mm
/gate/physics/Electron/SetCutInRegion  world 10 mm

#=====================================================
# DETECTORS
#=====================================================

/gate/actor/addActor SimulationStatisticActor SSA
/gate/actor/SSA/save                          output/SSA.txt

/gate/actor/addActor DoseActor                DAVW
/gate/actor/DAVW/save                         output/DAVW.mhd
/gate/actor/DAVW/attachTo                     VolumeTot
/gate/actor/DAVW/stepHitType                  random
/gate/actor/DAVW/setDoseAlgorithm             VolumeWeighting
/gate/actor/DAVW/setResolution                2 2 2
/gate/actor/DAVW/enableDose                   true
/gate/actor/DAVW/enableSquaredDose            true
/gate/actor/DAVW/enableUncertaintyDose        true

/gate/actor/addActor DoseActor                DAMW
/gate/actor/DAMW/save                         output/DAMW.mhd
/gate/actor/DAMW/attachTo                     VolumeTot
/gate/actor/DAMW/stepHitType                  random
/gate/actor/DAMW/setDoseAlgorithm             MassWeighting
/gate/actor/DAMW/setResolution                2 2 2
/gate/actor/DAMW/enableDose                   true
/gate/actor/DAMW/enableSquaredDose            true
/gate/actor/DAMW/enableUncertaintyDose        true
/gate/actor/DAMW/exportMassImage              output/DAMW-Mass.mhd

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

#=====================================================
# VISUALISATION
#=====================================================

#/control/execute mac/visu.mac

#=====================================================
# START BEAMS
#=====================================================

/gate/application/setTotalNumberOfPrimaries 1e5
/gate/application/start
