#=====================================================
# VISUALISATION
#=====================================================

#/vis/disable

/vis/open                             OGLSX
/vis/viewer/set/viewpointThetaPhi     60 60
/vis/viewer/zoom                      5.0
/vis/drawVolume
/tracking/storeTrajectory             1
/vis/scene/add/trajectories 
/vis/scene/endOfEventAction           accumulate


