/gate/actor/addActor                           KillActor Left_Leaf_Killer
/gate/actor/Left_Leaf_Killer/attachTo          mylinac_MLC_Leaf1_Left_Leaf_Kill_Plane
/gate/actor/Left_Leaf_Killer/save              output/killPhS_L.txt

/gate/actor/addActor                           KillActor Right_Leaf_Killer
/gate/actor/Right_Leaf_Killer/attachTo         mylinac_MLC_Leaf2_Right_Leaf_Kill_Plane
/gate/actor/Right_Leaf_Killer/save             output/killPhS_R.txt

/gate/actor/addActor                          KillActor backupY1_Killer
/gate/actor/backupY1_Killer/attachTo          backupY_1_Kill_Plane
/gate/actor/backupY1_Killer/save              output/killPhS_BY1.txt

/gate/actor/addActor                          KillActor backupY2_Killer
/gate/actor/backupY2_Killer/attachTo          backupY_2_Kill_Plane
/gate/actor/backupY2_Killer/save              output/killPhS_BY2.txt

/gate/actor/addActor                          KillActor backupX1_Killer
/gate/actor/backupX1_Killer/attachTo          backupX_1_Kill_Plane
/gate/actor/backupX1_Killer/save              output/killPhS_BX1.txt

/gate/actor/addActor                          KillActor backupX2_Killer
/gate/actor/backupX2_Killer/attachTo          backupX_2_Kill_Plane
/gate/actor/backupX2_Killer/save              output/killPhS_BX2.txt
