
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# Example of photon beam in patient CT image with IMRT
# irradiation. 100 slices with different MLC positions

#-------------------oooooOOOOO00000OOOOOooooo---------------------#


#=====================================================
# VERBOSE and VISUALISATION 
#=====================================================

/control/execute mac/verbose.mac
#/control/execute mac/visu.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    5.0 m
/gate/world/geometry/setYLength    5.0 m
/gate/world/geometry/setZLength    5.0 m
/gate/world/vis/setVisible 0

## Target : choose CT or waterbox
/control/execute mac/target-CT.mac
#/control/execute mac/target-waterbox.mac

### A simple linac with backup X,Y and MLC
/gate/geometry/setMaterialDatabase data/PreciseMaterials.db
/control/execute mac/precise_Linac.mac

### kill box to stop particle going through leafs
/control/execute mac/kill_box.mac

#=====================================================
# PHYSICS
#=====================================================

/control/execute mac/physicslist_EM_std.mac

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      patient 0.1 mm
/gate/physics/Electron/SetCutInRegion   patient 0.1 mm
/gate/physics/Positron/SetCutInRegion   patient 0.1 mm

/gate/physics/Gamma/SetCutInRegion      mylinac 10 mm
/gate/physics/Electron/SetCutInRegion   mylinac 10 mm
/gate/physics/Positron/SetCutInRegion   mylinac 10 mm

/gate/physics/displayCuts
/gate/physics/print output/physics.txt

#=====================================================
# DETECTORS
#=====================================================

# ----------------------------------------------------
# the following actor regularly store the current number of
# event/track/step in a file

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/output-stat.txt
/gate/actor/stat/saveEveryNSeconds 10

/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  output/output.hdr
/gate/actor/doseDistribution/attachTo    	   patient
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setVoxelSize          3 3 3 mm
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep true
/gate/actor/doseDistribution/enableDose            true
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/saveEveryNSeconds     60

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

#=====================================================
# BEAMS
#=====================================================

/gate/source/addSource mybeam LinacBeam
/gate/source/mybeam/setSourceFromPhaseSpaceFilename data/beam.root
/gate/source/mybeam/attachTo linacPhSPlane
/gate/source/mybeam/setMaxLeafDistanceAccordingToTime data/precise_BeamSource.rmax

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

/gate/application/readTimeSlicesIn data/precise_BeamSource.timeslices
/gate/application/setTotalNumberOfPrimaries 100000

/gate/application/start
/gate/application/describe

