# -----------------------------------------------------
# MACRO TEMPLATE FOR BEAM LIMITING DEVICE X (BACKUP X)
# -----------------------------------------------------

# [BLD_DISTANCE_TO_SOURCE_IN_MM] 470
# backupX backupX
# white white
# [BLD_ROUNDED_PART_RADIUS] 150
# [BLD_LEAF_LENGTH] 220
# # [BLD_LEAF_WIDTH1] 300
# # [BLD_LEAF_WIDTH2] 300

# -----------------------------------------------------
/gate/mylinacGantry/daughters/name backupX
/gate/mylinacGantry/daughters/insert box
/gate/backupX/setMaterial Air
#/gate/backupX/geometry/setXLength 1000.0 mm  
#/gate/backupX/geometry/setYLength 1000.0 mm  
#/gate/backupX/geometry/setZLength 79 mm  
/gate/backupX/geometry/setXLength 500.0 mm  
/gate/backupX/geometry/setYLength 500.0 mm  
#/gate/backupX/geometry/setZLength 79 mm  
/gate/backupX/geometry/setZLength 79.1 mm  
/gate/backupX/placement/setTranslation 0.0 0.0 -470 mm
/gate/backupX/placement/setRotationAxis  0 0 1
/gate/backupX/placement/setRotationAngle 90 deg

#ss_boite colli backup X gauche
/gate/backupX/daughters/name backupX_1
/gate/backupX/daughters/insert box
/gate/backupX_1/setMaterial Air
/gate/backupX_1/geometry/setXLength 220.10 mm  
/gate/backupX_1/geometry/setYLength 420.10 mm
/gate/backupX_1/geometry/setZLength 79 mm
/gate/backupX_1/placement/setRotationAxis  0 0 1
/gate/backupX_1/placement/setRotationAngle 0 deg

## KILL PLANE
/gate/backupX_1/daughters/name                      backupX_1_Kill_Plane
/gate/backupX_1/daughters/insert                    box
/gate/backupX_1_Kill_Plane/setMaterial              Vacuum
/gate/backupX_1_Kill_Plane/geometry/setXLength      215.1 mm  
/gate/backupX_1_Kill_Plane/geometry/setYLength      420.1 mm
/gate/backupX_1_Kill_Plane/geometry/setZLength      1 nm
/gate/backupX_1_Kill_Plane/placement/setTranslation 0.0 0.0 39.5 mm
/gate/backupX_1_Kill_Plane/vis/setColor             blue
/gate/backupX_1_Kill_Plane/vis/setVisible           1


/gate/backupX_1/daughters/name backupX_trp_inf_1
/gate/backupX_1/daughters/insert general_trpd
/gate/backupX_trp_inf_1/setMaterial AcceleratorCollimatorLeafMaterial
/gate/backupX_trp_inf_1/geometry/setX1Length 70 mm
/gate/backupX_trp_inf_1/geometry/setX2Length 70 mm
/gate/backupX_trp_inf_1/geometry/setX3Length 214.841 mm
/gate/backupX_trp_inf_1/geometry/setX4Length 214.841 mm
/gate/backupX_trp_inf_1/geometry/setY1Length 420 mm
/gate/backupX_trp_inf_1/geometry/setY2Length 420 mm
/gate/backupX_trp_inf_1/geometry/setZLength  39.0 mm
/gate/backupX_trp_inf_1/geometry/setTheta    61.697 deg
/gate/backupX_trp_inf_1/geometry/setPhi      0 deg
/gate/backupX_trp_inf_1/geometry/setAlp1     0 deg
/gate/backupX_trp_inf_1/geometry/setAlp2     0 deg
/gate/backupX_trp_inf_1/placement/setTranslation    -38.790 0.0 19.5 mm
#/gate/backupX_trp_inf_1/placement/setTranslation     1.210  0.0 19.5 mm

/gate/backupX_1/daughters/name backupX_trp_sup_1
/gate/backupX_1/daughters/insert general_trpd
/gate/backupX_trp_sup_1/setMaterial AcceleratorCollimatorLeafMaterial
/gate/backupX_trp_sup_1/geometry/setX1Length 214.841 mm
/gate/backupX_trp_sup_1/geometry/setX2Length 214.841 mm
/gate/backupX_trp_sup_1/geometry/setX3Length 70 mm
/gate/backupX_trp_sup_1/geometry/setX4Length 70 mm
/gate/backupX_trp_sup_1/geometry/setY1Length 420 mm
/gate/backupX_trp_sup_1/geometry/setY2Length 420 mm
/gate/backupX_trp_sup_1/geometry/setZLength  39.0 mm
/gate/backupX_trp_sup_1/geometry/setTheta   -61.697 deg
/gate/backupX_trp_sup_1/geometry/setPhi      0 deg
/gate/backupX_trp_sup_1/geometry/setAlp1     0 deg
/gate/backupX_trp_sup_1/geometry/setAlp2     0 deg
/gate/backupX_trp_sup_1/placement/setTranslation    -38.790 0.0 -19.51 mm
#/gate/backupX_trp_sup_1/placement/setTranslation     1.210  0.0 -19.5 mm

/gate/backupX_1/daughters/name backupX_arrondi_1
/gate/backupX_1/daughters/insert cylinder
/gate/backupX_arrondi_1/setMaterial AcceleratorCollimatorLeafMaterial
/gate/backupX_arrondi_1/geometry/setRmin 0 mm
/gate/backupX_arrondi_1/geometry/setRmax 150 mm
/gate/backupX_arrondi_1/geometry/setHeight 420 mm
/gate/backupX_arrondi_1/geometry/setPhiStart -15.070 deg
/gate/backupX_arrondi_1/geometry/setDeltaPhi  30.140 deg
/gate/backupX_arrondi_1/placement/setTranslation -40 0 0 mm
/gate/backupX_arrondi_1/placement/setRotationAxis 1 0 0 
/gate/backupX_arrondi_1/placement/setRotationAngle 90 deg

#ss_boite colli backup x droite
/gate/backupX/daughters/name backupX_2
/gate/backupX/daughters/insert box
/gate/backupX_2/setMaterial Air
/gate/backupX_2/geometry/setXLength 220.10 mm  
/gate/backupX_2/geometry/setYLength 420.10 mm
/gate/backupX_2/geometry/setZLength 79 mm
/gate/backupX_2/placement/setRotationAxis  0 0 1
/gate/backupX_2/placement/setRotationAngle 180 deg


## KILL PLANE
/gate/backupX_2/daughters/name                      backupX_2_Kill_Plane
/gate/backupX_2/daughters/insert                    box
/gate/backupX_2_Kill_Plane/setMaterial              Vacuum
/gate/backupX_2_Kill_Plane/geometry/setXLength      215.1 mm  
/gate/backupX_2_Kill_Plane/geometry/setYLength      420.1 mm
/gate/backupX_2_Kill_Plane/geometry/setZLength      1 nm
/gate/backupX_2_Kill_Plane/placement/setTranslation 0.0 0.0 39.5 mm
/gate/backupX_2_Kill_Plane/vis/setColor             blue
/gate/backupX_2_Kill_Plane/vis/setVisible           1


/gate/backupX_2/daughters/name backupX_trp_inf_2
/gate/backupX_2/daughters/insert general_trpd
/gate/backupX_trp_inf_2/setMaterial AcceleratorCollimatorLeafMaterial
/gate/backupX_trp_inf_2/geometry/setX1Length 70 mm
/gate/backupX_trp_inf_2/geometry/setX2Length 70 mm
/gate/backupX_trp_inf_2/geometry/setX3Length 214.841 mm
/gate/backupX_trp_inf_2/geometry/setX4Length 214.841 mm
/gate/backupX_trp_inf_2/geometry/setY1Length 420 mm
/gate/backupX_trp_inf_2/geometry/setY2Length 420 mm
/gate/backupX_trp_inf_2/geometry/setZLength  39.0 mm
/gate/backupX_trp_inf_2/geometry/setTheta    61.697 deg
/gate/backupX_trp_inf_2/geometry/setPhi      0 deg
/gate/backupX_trp_inf_2/geometry/setAlp1     0 deg
/gate/backupX_trp_inf_2/geometry/setAlp2     0 deg
/gate/backupX_trp_inf_2/placement/setTranslation    -38.790 0.0 19.5 mm
#/gate/backupX_trp_inf_2/placement/setTranslation     1.210  0.0 19.5 mm

/gate/backupX_2/daughters/name backupX_trp_sup_2
/gate/backupX_2/daughters/insert general_trpd
/gate/backupX_trp_sup_2/setMaterial AcceleratorCollimatorLeafMaterial
/gate/backupX_trp_sup_2/geometry/setX1Length 214.841 mm
/gate/backupX_trp_sup_2/geometry/setX2Length 214.841 mm
/gate/backupX_trp_sup_2/geometry/setX3Length 70 mm
/gate/backupX_trp_sup_2/geometry/setX4Length 70 mm
/gate/backupX_trp_sup_2/geometry/setY1Length 420 mm
/gate/backupX_trp_sup_2/geometry/setY2Length 420 mm
/gate/backupX_trp_sup_2/geometry/setZLength  39.0 mm
/gate/backupX_trp_sup_2/geometry/setTheta   -61.697 deg
/gate/backupX_trp_sup_2/geometry/setPhi      0 deg
/gate/backupX_trp_sup_2/geometry/setAlp1     0 deg
/gate/backupX_trp_sup_2/geometry/setAlp2     0 deg
/gate/backupX_trp_sup_2/placement/setTranslation    -38.790 0.0 -19.51 mm
#/gate/backupX_trp_sup_2/placement/setTranslation     1.210  0.0 -19.5 mm

/gate/backupX_2/daughters/name backupX_arrondi_2
/gate/backupX_2/daughters/insert cylinder
/gate/backupX_arrondi_2/setMaterial AcceleratorCollimatorLeafMaterial
/gate/backupX_arrondi_2/geometry/setRmin 0 mm
/gate/backupX_arrondi_2/geometry/setRmax 150 mm
/gate/backupX_arrondi_2/geometry/setHeight 420 mm
/gate/backupX_arrondi_2/geometry/setPhiStart -15.070 deg
/gate/backupX_arrondi_2/geometry/setDeltaPhi  30.140 deg
/gate/backupX_arrondi_2/placement/setTranslation -40 0 0 mm
/gate/backupX_arrondi_2/placement/setRotationAxis 1 0 0 
/gate/backupX_arrondi_2/placement/setRotationAngle 90 deg

# -----------------------------------------------------
# Color
/gate/backupX/vis/setVisible 0
/gate/backupX_1/vis/setColor white
/gate/backupX_trp_inf_1/vis/setColor white
/gate/backupX_trp_sup_1/vis/setColor white
/gate/backupX_arrondi_1/vis/setColor white

# -----------------------------------------------------
# Color
/gate/backupX_2/vis/setColor         white
/gate/backupX_trp_inf_2/vis/setColor white
/gate/backupX_trp_sup_2/vis/setColor white
/gate/backupX_arrondi_2/vis/setColor white

# -----------------------------------------------------
# Translation & Motion 
/gate/backupX_1/moves/insert genericMove
/gate/backupX_1/genericMove/setPlacementsFilename data/precise_X_BLD1.placements

/gate/backupX_2/moves/insert genericMove
/gate/backupX_2/genericMove/setPlacementsFilename data/precise_X_BLD2.placements



