# ---------------------------------------
# Patient
# ---------------------------------------

/gate/world/daughters/name patient
/gate/world/daughters/insert box
/gate/patient/setMaterial Water
/gate/patient/placement/setTranslation 0 0 0 mm
/gate/patient/geometry/setXLength 584 mm
/gate/patient/geometry/setYLength 584 mm
/gate/patient/geometry/setZLength 436 mm
/gate/patient/vis/setColor blue

### rotate the patient
/gate/patient/placement/setRotationAxis 1 0 0
/gate/patient/placement/setRotationAngle -90 deg
