#/vis/disable
/control/execute vis.mac

/gate/geometry/setMaterialDatabase ../../GateMaterials.db

#############
#   World   #
#############

/gate/world/geometry/setXLength 1.5 m
/gate/world/geometry/setYLength 1.5 m
/gate/world/geometry/setZLength 1.5 m
/gate/world/setMaterial Air

##############################
#   cylindricalPET scanner   #
##############################

/gate/world/daughters/name cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/setMaterial BGO
/gate/cylindricalPET/geometry/setRmax 450. mm
/gate/cylindricalPET/geometry/setRmin 430. mm
/gate/cylindricalPET/geometry/setHeight 24. cm
/gate/cylindricalPET/vis/forceWireframe

/gate/cylindricalPET/attachCrystalSD


##########################
#   Voxellized phantom   #
##########################

/gate/world/daughters/name Ncat

/gate/world/daughters/insert regularMatrix

#/gate/world/daughters/insert compressedMatrix

/gate/Ncat/geometry/insertReader interfile
/gate/Ncat/verbose 0
/gate/RTPhantom/insert RTVPhantom
/gate/RTVPhantom/AttachTo Ncat
/gate/RTVPhantom/SetNumberOfFrames 10
/gate/RTVPhantom/SetTimePerFrame 0.1 s
/gate/RTVPhantom/verbose 0
/gate/RTVPhantom/setHeaderFileName data/NCAT_header.h33
/gate/Ncat/interfileReader/insertTranslator range
/gate/Ncat/interfileReader/rangeTranslator/readTable data/range.dat
/gate/Ncat/interfileReader/rangeTranslator/describe 1
/gate/Ncat/placement/setTranslation  0. 0. 0. mm
/gate/RTVPhantom/setBaseFileName data/NCAT
#/gate/Ncat/vis/forceSolid
#/gate/Ncat/vis/setColor Blue


/gate/Ncat/attachVoxelPhantomSD
#/gate/geometry/update


################################
#   Physics and no Digitizer   #
################################


/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel

/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel StandardModel

/gate/physics/addProcess GammaConversion
/gate/physics/processes/GammaConversion/setModel StandardModel

/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/processes/ElectronIonisation/setModel StandardModel e+
/gate/physics/processes/ElectronIonisation/setStepFunction e+ 0.2 0.1 mm
/gate/physics/processes/ElectronIonisation/setStepFunction e- 0.2 0.1 mm

/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+

/gate/physics/addProcess PositronAnnihilation

/gate/physics/addProcess MultipleScattering
/gate/physics/processes/MultipleScattering/setGeometricalStepLimiterType e- distanceToBoundary
/gate/physics/processes/MultipleScattering/setGeometricalStepLimiterType e+ distanceToBoundary

/gate/physics/processList Enabled
/gate/physics/processList Initialized


#	I N I T I A L I Z E 
/gate/run/initialize


##############################
#   Cubic voxelized source   #
##############################

/gate/source/addSource voxel voxel
/gate/source/verbose 0
/gate/source/voxel/reader/insert interfile

/gate/RTVPhantom/AttachToSource voxel
/gate/source/voxel/interfileReader/translator/insert range
/gate/source/voxel/interfileReader/rangeTranslator/readTable data/activityRange.dat
/gate/source/voxel/interfileReader/SetTimeActivityTablesFrom data/acti.range
/gate/source/voxel/interfileReader/SetTimeSampling 0.1 s

/gate/source/voxel/interfileReader/rangeTranslator/describe 1


/gate/source/voxel/setPosition -200. -200. -200. mm

/gate/source/voxel/setType backtoback
/gate/source/voxel/gps/particle gamma
/gate/source/voxel/setForcedUnstableFlag true
/gate/source/voxel/setForcedHalfLife 6586.2 s
/gate/source/voxel/gps/energytype Mono
/gate/source/voxel/gps/monoenergy 0.511 MeV
/gate/source/voxel/gps/confine NULL
/gate/source/voxel/gps/angtype iso
/gate/source/voxel/dump 0
/gate/source/voxel/verbose 0



###############
#   Verbose   #
###############

#/gate/verbose Physic    0
#/gate/verbose Cuts      0
#/gate/verbose Actor     0
#/gate/verbose SD        0
#/gate/verbose Actions   0
#/gate/verbose Step      0
#/gate/verbose Error     0
#/gate/verbose Warning   0
#/gate/verbose Output    0
#/gate/verbose Core      0

/run/verbose 0
/event/verbose 0
/tracking/verbose 0
################
#     Output   #
################

### ROOT OUTPUT ###
/gate/output/root/enable
/gate/output/root/setFileName testTAC
/gate/output/root/setRootHitFlag 0
/gate/output/root/setRootSinglesFlag 1
/gate/output/root/setRootCoincidencesFlag 0
/gate/output/root/setRootNtupleFlag 0


#   R A N D O M
# JamesRandom Ranlux64 MersenneTwister
/gate/random/setEngineName Ranlux64
#/gate/random/setEngineSeed default
#/gate/random/setEngineSeed auto
/gate/random/setEngineSeed 123456789
#/gate/random/resetEngineFrom fileName
/gate/random/verbose 1

############################
#   Measurement settings   #
############################

/gate/application/setTimeSlice 1. s
/gate/application/setTimeStart 0. s
/gate/application/setTimeStop 1. s

/gate/application/startDAQ

