
#=====================================================
# VISUALISATION 

/vis/open                             OGLIQt
#/vis/open                             OGLSQt
/vis/drawVolume
/vis/viewer/flush
/tracking/storeTrajectory             1
/vis/scene/add/trajectories 
#/vis/scene/endOfEventAction           accumulate
/vis/viewer/set/viewpointThetaPhi 70 20
/vis/viewer/zoom 0.5
/vis/viewer/set/style surface
/gate/world/vis/setVisible false
