#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# Electron beam from a Linac into a box with water/alu/lung. See
# Figure5 from [Jan et al PMB 2011].

#-------------------oooooOOOOO00000OOOOOooooo---------------------#

#=====================================================
# VERBOSE and VISUALISATION 
#=====================================================

/control/execute mac/verbose.mac
#/control/execute mac/visu.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# World
/gate/world/geometry/setXLength 5 m
/gate/world/geometry/setYLength 5 m
/gate/world/geometry/setZLength 5 m
/gate/world/setMaterial Vacuum

# Global Box
/gate/world/daughters/name             mainbox
/gate/world/daughters/insert           box
/gate/mainbox/geometry/setXLength      30.5 cm
/gate/mainbox/geometry/setYLength      30 cm
/gate/mainbox/geometry/setZLength      30.5 cm
/gate/mainbox/placement/setTranslation 0 -15 0 cm
/gate/mainbox/setMaterial Water
/gate/mainbox/vis/setVisible 1
/gate/mainbox/vis/setColor blue

# First Water slice
/gate/mainbox/daughters/name    water_slice_1
/gate/mainbox/daughters/insert  box
/gate/water_slice_1/geometry/setXLength 30.5  cm
/gate/water_slice_1/geometry/setYLength 2 cm
/gate/water_slice_1/geometry/setZLength 30.5  cm
/gate/water_slice_1/placement/setTranslation 0 14 0 cm
/gate/water_slice_1/setMaterial Water
/gate/water_slice_1/vis/setVisible 1
/gate/water_slice_1/vis/setColor blue

# Second Alu slice
/gate/mainbox/daughters/name    alu_slice
/gate/mainbox/daughters/insert  box
/gate/alu_slice/geometry/setXLength 30 cm
/gate/alu_slice/geometry/setYLength 1 cm
/gate/alu_slice/geometry/setZLength  30.5 cm
/gate/alu_slice/placement/setTranslation 0 12.5 0 cm
/gate/alu_slice/setMaterial AluminiumEGS
/gate/alu_slice/vis/setVisible 1
/gate/alu_slice/vis/setColor yellow

# Third Lung slice
/gate/mainbox/daughters/name    lung_slice
/gate/mainbox/daughters/insert  box
/gate/lung_slice/geometry/setXLength 30.5 cm
/gate/lung_slice/geometry/setYLength 3 cm
/gate/lung_slice/geometry/setZLength  30.5 cm
/gate/lung_slice/placement/setTranslation 0 10.5 0 cm
/gate/lung_slice/setMaterial Lung
/gate/lung_slice/vis/setVisible 1
/gate/lung_slice/vis/setColor red


#collimater
/gate/world/daughters/name             colli1
/gate/world/daughters/insert           box
/gate/colli1/geometry/setXLength      200 cm
/gate/colli1/geometry/setYLength      0.0001 cm
/gate/colli1/geometry/setZLength      200 cm
/gate/colli1/placement/setTranslation 0 0.00005 -100.75 cm
/gate/colli1/setMaterial Vacuum
/gate/colli1/vis/setVisible 1

/gate/world/daughters/name             colli2
/gate/world/daughters/insert           box
/gate/colli2/geometry/setXLength      200 cm
/gate/colli2/geometry/setYLength      0.0001 cm
/gate/colli2/geometry/setZLength      200 cm
/gate/colli2/placement/setTranslation 0 0.00005 100.75 cm
/gate/colli2/setMaterial Vacuum
/gate/colli2/vis/setVisible 1

/gate/world/daughters/name             colli3
/gate/world/daughters/insert           box
/gate/colli3/geometry/setXLength      200 cm
/gate/colli3/geometry/setYLength      0.0001 cm
/gate/colli3/geometry/setZLength      1.5 cm
/gate/colli3/placement/setTranslation -100.75 0.00005 0 cm
/gate/colli3/setMaterial Vacuum
/gate/colli3/vis/setVisible 1

/gate/world/daughters/name             colli4
/gate/world/daughters/insert           box
/gate/colli4/geometry/setXLength      200 cm
/gate/colli4/geometry/setYLength      0.0001 cm
/gate/colli4/geometry/setZLength      1.5 cm
/gate/colli4/placement/setTranslation  100.75 0.00005 0 cm
/gate/colli4/setMaterial Vacuum
/gate/colli4/vis/setVisible 1


/gate/geometry/setIonisationPotential Water 75 eV
/gate/geometry/setIonisationPotential AluminiumEGS 166 eV
/gate/geometry/setIonisationPotential Lung 75.2 eV
/gate/geometry/setIonisationPotential Air 85.7 eV



#=====================================================
# PHYSICS
#=====================================================

/control/execute mac/physicslist_EM_std.mac

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      mainbox 0.1 mm
/gate/physics/Electron/SetCutInRegion   mainbox 0.1 mm
/gate/physics/Positron/SetCutInRegion   mainbox 0.1 mm

/gate/physics/SetMaxStepSizeInRegion    mainbox 0.01 mm
/gate/physics/ActivateStepLimiter e-

/gate/physics/displayCuts


#=====================================================
# DETECTORS
#=====================================================

/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  output/Electron-20MeV.root
/gate/actor/doseDistribution/attachTo              mainbox
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               5 300 5 mm
/gate/actor/doseDistribution/setVoxelSize          5 2 5 mm
/gate/actor/doseDistribution/saveEveryNSeconds     300
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep true 
/gate/actor/doseDistribution/enableDose            true
/gate/actor/doseDistribution/enableUncertaintyDose true
/gate/actor/doseDistribution/enableSquaredDose     true
/gate/actor/doseDistribution/enableSquaredEdep     true
/gate/actor/doseDistribution/enableNumberOfHits    true

/gate/actor/addActor                               DoseActor  doseDistribution2
/gate/actor/doseDistribution2/save                  output/Electron-20MeV.mhd
/gate/actor/doseDistribution2/attachTo              mainbox
/gate/actor/doseDistribution2/stepHitType           random
/gate/actor/doseDistribution2/setPosition           0 0 0 cm
/gate/actor/doseDistribution2/setSize               5 300 5 mm
/gate/actor/doseDistribution2/setVoxelSize          5 2 5 mm
/gate/actor/doseDistribution2/saveEveryNSeconds     300
/gate/actor/doseDistribution2/enableEdep            true
/gate/actor/doseDistribution2/enableUncertaintyEdep true 
/gate/actor/doseDistribution2/enableDose            true
/gate/actor/doseDistribution2/enableUncertaintyDose true
/gate/actor/doseDistribution2/enableSquaredDose     true
/gate/actor/doseDistribution2/enableSquaredEdep     true
/gate/actor/doseDistribution2/enableNumberOfHits    true

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/statElectron-20MeV.txt
/gate/actor/stat/saveEveryNSeconds 60

/gate/actor/addActor                    ParticleInVolumeActor counter
/gate/actor/counter/save                output/counterElectron-20MeV.txt
/gate/actor/counter/saveEveryNSeconds   60
/gate/actor/counter/addFilter           IDFilter
/gate/actor/counter/IDFilter/selectID   1
/gate/actor/counter/attachTo            mainbox
/gate/actor/counter/setResolution       1 1 1

/gate/actor/addActor       KillActor kill1
/gate/actor/kill1/attachTo colli1
/gate/actor/kill1/save output/colli1.txt
/gate/actor/kill1/addFilter IDFilter
/gate/actor/kill1/IDFilter/selectID 1

/gate/actor/addActor       KillActor kill2
/gate/actor/kill2/attachTo colli2
/gate/actor/kill2/save output/colli2.txt
/gate/actor/kill2/addFilter IDFilter
/gate/actor/kill2/IDFilter/selectID 1

/gate/actor/addActor       KillActor kill3
/gate/actor/kill3/attachTo colli3
/gate/actor/kill3/save output/colli3.txt
/gate/actor/kill3/addFilter IDFilter
/gate/actor/kill3/IDFilter/selectID 1

/gate/actor/addActor       KillActor kill4
/gate/actor/kill4/attachTo colli4
/gate/actor/kill4/save output/colli4.txt
/gate/actor/kill4/addFilter IDFilter
/gate/actor/kill4/IDFilter/selectID 1


#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

#=====================================================
# BEAMS
#=====================================================

/gate/source/addSource mybeam gps
/gate/source/mybeam/gps/particle e-
/gate/source/mybeam/gps/energy 20 MeV

/gate/source/mybeam/gps/position      0 100 0 cm
/gate/source/mybeam/gps/type Point
/gate/source/mybeam/gps/ang/type iso
/gate/source/mybeam/gps/posrot1 1 0 0
/gate/source/mybeam/gps/posrot2 0 0 1
/gate/source/mybeam/gps/ang/mintheta 89.570 deg
/gate/source/mybeam/gps/ang/maxtheta 90.4298 deg
/gate/source/mybeam/gps/ang/minphi    89.570 deg
/gate/source/mybeam/gps/ang/maxphi  90.4298 deg

#=====================================================
# START BEAMS
#=====================================================


/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries 3000
/gate/application/start
