#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# Example of proton beam in water box with Pencil Beam Scanning
# source with a treatment plan obtained from a TPS.

#-------------------oooooOOOOO00000OOOOOooooo---------------------#

#=====================================================
# VERBOSE and VISUALISATION
#=====================================================

/control/execute mac/verbose.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# World
/gate/world/geometry/setXLength 5 m
/gate/world/geometry/setYLength 5 m
/gate/world/geometry/setZLength 5 m
/gate/world/setMaterial Air

# -----------------------------------------------------
# Patient CT data

# Generate materials from Hounsfield units
/gate/HounsfieldMaterialGenerator/SetMaterialTable      data/Schneider2000MaterialsTable.txt
/gate/HounsfieldMaterialGenerator/SetDensityTable       data/Schneider2000DensitiesTable.txt
/gate/HounsfieldMaterialGenerator/SetDensityTolerance   0.05 g/cm3
/gate/HounsfieldMaterialGenerator/SetOutputMaterialDatabaseFilename     data/patient-HUmaterials.db
/gate/HounsfieldMaterialGenerator/SetOutputHUMaterialFilename           data/patient-HU2mat.txt
/gate/HounsfieldMaterialGenerator/Generate

# CT Volume
/gate/world/daughters/name                      patient
/gate/world/daughters/insert                    ImageNestedParametrisedVolume
/gate/geometry/setMaterialDatabase              data/patient-HUmaterials.db
/gate/patient/geometry/setHUToMaterialFile      data/patient-HU2mat.txt
/gate/patient/geometry/setImage                 data/patient-2mm.mhd

# optional : dump used image
#/gate/patient/geometry/buildAndDumpLabeledImage  output/patient-labeled.mhd

# Put the following image point at center
/gate/patient/geometry/TranslateTheImageAtThisIsoCenter -8.34 -20.64 45 mm
#/gate/patient/geometry/enableBoundingBoxOnly true
#/gate/patient/vis/setColor blue


#=====================================================
# PHYSICS
#=====================================================

/gate/physics/addPhysicsList QGSP_BERT_EMV

/gate/physics/Gamma/SetCutInRegion      world 10 mm
/gate/physics/Electron/SetCutInRegion   world 10 mm
/gate/physics/Positron/SetCutInRegion   world 10 mm
/gate/physics/Proton/SetCutInRegion     world 10 mm

/gate/physics/Gamma/SetCutInRegion      patient 1 mm
/gate/physics/Electron/SetCutInRegion   patient 1 mm
/gate/physics/Positron/SetCutInRegion   patient 1 mm
/gate/physics/Proton/SetCutInRegion     patient 1 mm

/gate/physics/SetMaxStepSizeInRegion patient 1 mm
/gate/physics/ActivateStepLimiter proton

/gate/physics/displayCuts
/gate/physics/print output/physics.txt

#=====================================================
# DETECTORS
#=====================================================

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/stat-proton.txt
#/gate/actor/stat/saveEveryNSeconds 20

/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  output/output.mhd
/gate/actor/doseDistribution/attachTo    	   patient
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setVoxelSize          2 2 2 mm
# /gate/actor/doseDistribution/saveEveryNSeconds   30
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep true
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false
/gate/actor/doseDistribution/enableNumberOfHits    false


#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

#=====================================================
# BEAMS
#=====================================================

/gate/source/addSource PBS TPSPencilBeam
/gate/source/PBS/setTestFlag false
/gate/source/PBS/setPlan data/RTIPLAN.0912590.16.txt
#/gate/source/PBS/setNotAllowedFieldID 1
#/gate/source/PBS/setNotAllowedFieldID 2
/gate/source/PBS/setFlatGenerationFlag false
/gate/source/PBS/setSourceDescriptionFile data/Source-Properties.txt

#=====================================================
# START BEAMS
#=====================================================

/gate/application/noGlobalOutput
/gate/run/enableGlobalOutput false

/vis/disable

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries 750000
/gate/application/start
