#=====================================
#    Electromagnetic  processes
#=====================================

/gate/physics/addProcess PhotoElectric gamma
/gate/physics/processes/PhotoElectric/setModel StandardModel

/gate/physics/addProcess Compton gamma
/gate/physics/processes/Compton/setModel StandardModel

/gate/physics/addProcess RayleighScattering gamma
/gate/physics/processes/RayleighScattering/setModel LivermoreModel

/gate/physics/addProcess GammaConversion gamma
/gate/physics/processes/GammaConversion/setModel StandardModel

/gate/physics/addProcess ElectronIonisation e-
/gate/physics/addProcess ElectronIonisation e+
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/processes/ElectronIonisation/setModel StandardModel e+
/gate/physics/processes/ElectronIonisation/setStepFunction e+ 0.2 0.1 mm
/gate/physics/processes/ElectronIonisation/setStepFunction e- 0.2 0.1 mm

/gate/physics/addProcess Bremsstrahlung e-
/gate/physics/addProcess Bremsstrahlung e+
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+

/gate/physics/addProcess PositronAnnihilation

/gate/physics/addProcess eMultipleScattering e-
/gate/physics/addProcess eMultipleScattering e+
/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e- distanceToBoundary
/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e+ distanceToBoundary

/gate/physics/setEMin 0.1 keV
/gate/physics/setEMax 10 GeV
/gate/physics/setDEDXBinning 220
/gate/physics/setLambdaBinning 220


/gate/physics/addProcess MuIonisation mu+
/gate/physics/addProcess MuIonisation mu-
/gate/physics/addProcess MuBremsstrahlung mu+
/gate/physics/addProcess MuBremsstrahlung mu-
/gate/physics/addProcess MuPairProduction mu+
/gate/physics/addProcess MuPairProduction mu-

/gate/physics/addProcess hMultipleScattering alpha
/gate/physics/addProcess hMultipleScattering deuteron
/gate/physics/addProcess hMultipleScattering He3
/gate/physics/addProcess hMultipleScattering GenericIon
/gate/physics/addProcess hMultipleScattering proton
/gate/physics/addProcess hMultipleScattering pi+
/gate/physics/addProcess hMultipleScattering pi-

/gate/physics/addProcess HadronIonisation
/gate/physics/removeProcess HadronIonisation deuteron
/gate/physics/removeProcess HadronIonisation triton
/gate/physics/removeProcess HadronIonisation He3
/gate/physics/removeProcess HadronIonisation alpha
/gate/physics/removeProcess HadronIonisation GenericIon
/gate/physics/processes/HadronIonisation/setStepFunction proton 0.2 0.05 mm
/gate/physics/processes/HadronIonisation/setStepFunction pi+    0.2 0.05 mm
/gate/physics/processes/HadronIonisation/setStepFunction pi-    0.2 0.05 mm

/gate/physics/addProcess IonIonisation 
/gate/physics/processes/IonIonisation/setStepFunction GenericIon 0.1 0.01 mm
/gate/physics/processes/IonIonisation/setStepFunction alpha      0.1 0.02 mm
/gate/physics/processes/IonIonisation/setStepFunction deuteron   0.1 0.02 mm
/gate/physics/processes/IonIonisation/setStepFunction triton     0.1 0.02 mm
/gate/physics/processes/IonIonisation/setStepFunction He3        0.1 0.02 mm

/gate/physics/processes/IonIonisation/setNuclearStoppingOn

#=====================================
#    Hadronic processes 
#=====================================

/gate/physics/addProcess HadronElastic
#/gate/physics/processes/HadronElastic/setModel G4HadronElastic Default

/gate/physics/processes/HadronElastic/setModel G4HadronElastic neutron
/gate/physics/processes/HadronElastic/setDataSet G4HadronElasticDataSet neutron
/gate/physics/processes/HadronElastic/G4HadronElastic/setEmin 19 MeV neutron
/gate/physics/processes/HadronElastic/G4HadronElastic/setEmax 20 GeV neutron
/gate/physics/processes/HadronElastic/setModel G4NeutronHPElastic neutron
/gate/physics/processes/HadronElastic/G4NeutronHPElastic/setEmin 0 MeV neutron
/gate/physics/processes/HadronElastic/G4NeutronHPElastic/setEmax 20 MeV neutron
#/gate/physics/processes/HadronElastic/setDataSet G4NeutronHPElasticData neutron

/gate/physics/processes/HadronElastic/setModel G4HadronElastic proton
/gate/physics/processes/HadronElastic/setDataSet G4HadronElasticDataSet proton
/gate/physics/processes/HadronElastic/G4HadronElastic/setEmin 0 MeV proton
/gate/physics/processes/HadronElastic/G4HadronElastic/setEmax 20 GeV proton

/gate/physics/addProcess ProtonInelastic
/gate/physics/processes/ProtonInelastic/setModel G4BinaryCascade
/gate/physics/processes/ProtonInelastic/G4BinaryCascade/setEmin 0 MeV
/gate/physics/processes/ProtonInelastic/G4BinaryCascade/setEmax 20 GeV
/gate/physics/processes/ProtonInelastic/setDataSet G4ProtonInelasticCrossSection proton

/gate/physics/addProcess IonInelastic
/gate/physics/processes/IonInelastic/setModel G4QMDReaction GenericIon
/gate/physics/processes/IonInelastic/setModel G4QMDReaction alpha
/gate/physics/processes/IonInelastic/setModel G4QMDReaction deuteron
/gate/physics/processes/IonInelastic/setModel G4QMDReaction triton
/gate/physics/processes/IonInelastic/G4QMDReaction/setEmin 0 MeV deuteron
/gate/physics/processes/IonInelastic/G4QMDReaction/setEmax 20 GeV deuteron
/gate/physics/processes/IonInelastic/G4QMDReaction/setEmin 0 MeV alpha
/gate/physics/processes/IonInelastic/G4QMDReaction/setEmax 20 GeV alpha
/gate/physics/processes/IonInelastic/G4QMDReaction/setEmin 0 MeV triton
/gate/physics/processes/IonInelastic/G4QMDReaction/setEmax 20 GeV triton
/gate/physics/processes/IonInelastic/G4QMDReaction/setEmin 0 MeV GenericIon
/gate/physics/processes/IonInelastic/G4QMDReaction/setEmax 20 GeV GenericIon
/gate/physics/processes/IonInelastic/setDataSet G4IonsShenCrossSection GenericIon
#/gate/physics/processes/IonInelastic/setDataSet G4IonsShenCrossSection deuteron
#/gate/physics/processes/IonInelastic/setDataSet G4IonsShenCrossSection triton
#/gate/physics/processes/IonInelastic/setDataSet G4IonsShenCrossSection alpha

/gate/physics/addProcess PionPlusInelastic
/gate/physics/processes/PionPlusInelastic/setModel G4LEPionPlusInelastic

/gate/physics/addProcess PionMinusInelastic
/gate/physics/processes/PionMinusInelastic/setModel G4LEPionMinusInelastic

/gate/physics/addProcess NeutronCapture
/gate/physics/processes/NeutronCapture/setModel G4NeutronHPCapture
/gate/physics/processes/NeutronCapture/G4NeutronHPCapture/setEmin 0 MeV
/gate/physics/processes/NeutronCapture/G4NeutronHPCapture/setEmax 20 MeV
/gate/physics/processes/NeutronCapture/setModel G4LCapture
/gate/physics/processes/NeutronCapture/G4LCapture/setEmin 19 MeV
/gate/physics/processes/NeutronCapture/G4LCapture/setEmax 20 GeV
/gate/physics/processes/NeutronCapture/setDataSet G4NeutronHPCaptureData
/gate/physics/processes/NeutronCapture/setDataSet G4HadronCaptureDataSet

/gate/physics/addProcess Fission
/gate/physics/processes/Fission/setModel G4NeutronHPFission
/gate/physics/processes/Fission/G4NeutronHPFission/setEmin 0 MeV
/gate/physics/processes/Fission/G4NeutronHPFission/setEmax 20 MeV
/gate/physics/processes/Fission/setModel G4LFission
/gate/physics/processes/Fission/G4LFission/setEmin 19 MeV
/gate/physics/processes/Fission/G4LFission/setEmax 20 GeV
/gate/physics/processes/Fission/setDataSet G4NeutronHPFissionData
/gate/physics/processes/Fission/setDataSet G4HadronFissionDataSet

/gate/physics/addProcess NeutronInelastic
/gate/physics/processes/NeutronInelastic/setModel G4NeutronHPInelastic
/gate/physics/processes/NeutronInelastic/G4NeutronHPInelastic/setEmin 0 MeV
/gate/physics/processes/NeutronInelastic/G4NeutronHPInelastic/setEmax 20 MeV
/gate/physics/processes/NeutronInelastic/setModel G4BinaryCascade
/gate/physics/processes/NeutronInelastic/G4BinaryCascade/setEmin 19 MeV
/gate/physics/processes/NeutronInelastic/G4BinaryCascade/setEmax 20 GeV
#/gate/physics/processes/NeutronInelastic/setDataSet G4NeutronHPInelasticData
/gate/physics/processes/NeutronInelastic/setDataSet G4NeutronInelasticCrossSection

/gate/physics/addProcess Decay
/gate/physics/addProcess RadioactiveDecay

