
/control/execute verbose.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# World
/gate/world/geometry/setXLength 5 m
/gate/world/geometry/setYLength 5 m
/gate/world/geometry/setZLength 5 m
/gate/world/setMaterial Air



# Global Box
/gate/world/daughters/name             mainbox
/gate/world/daughters/insert           box
/gate/mainbox/geometry/setXLength 40 cm
/gate/mainbox/geometry/setYLength 40 cm
/gate/mainbox/geometry/setZLength 40 cm
/gate/mainbox/placement/setTranslation 0.0 0.0 25 cm
/gate/mainbox/setMaterial Water
/gate/mainbox/vis/setVisible 1
/gate/mainbox/vis/setColor blue


/gate/geometry/setIonisationPotential Water 75 eV
/gate/geometry/setIonisationPotential Air 85.7 eV


#=====================================================
# PHYSICS
#=====================================================

/control/execute hadrontherapyStandardPhys.mac

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      mainbox 0.1 mm
/gate/physics/Electron/SetCutInRegion   mainbox 0.1 mm
/gate/physics/Positron/SetCutInRegion   mainbox 0.1 mm

/gate/physics/SetMaxStepSizeInRegion world 1 mm
/gate/physics/ActivateStepLimiter proton       
/gate/physics/ActivateStepLimiter deuteron     
/gate/physics/ActivateStepLimiter triton       
/gate/physics/ActivateStepLimiter alpha        
/gate/physics/ActivateStepLimiter GenericIon   

/gate/physics/displayCuts


#=====================================================
# DETECTORS
#=====================================================

/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  output/Config-proton.txt
/gate/actor/doseDistribution/attachTo    	   mainbox
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setResolution         1 1 400 
/gate/actor/doseDistribution/saveEveryNSeconds     60
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableDose            true
/gate/actor/doseDistribution/enableUncertaintyDose true
/gate/actor/doseDistribution/enableNumberOfHits    false

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/stat-proton.txt
/gate/actor/stat/saveEveryNSeconds 60


#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# Enable the following lines to display available and enabled processes
# /gate/physics/processList Available
# /gate/physics/processList Enabled


#=====================================================
# BEAMS
#=====================================================

/gate/source/addSource mybeam gps

/gate/source/mybeam/gps/particle proton
/gate/source/mybeam/gps/pos/type Beam
/gate/source/mybeam/gps/pos/rot1 0 1 0
/gate/source/mybeam/gps/pos/rot2 1 0 0
/gate/source/mybeam/gps/pos/shape Circle
/gate/source/mybeam/gps/pos/centre 0 0 0 mm
/gate/source/mybeam/gps/pos/sigma_x 3 mm
/gate/source/mybeam/gps/pos/sigma_y 3 mm
/gate/source/mybeam/gps/ene/mono 150 MeV
/gate/source/mybeam/gps/ene/type Gauss
/gate/source/mybeam/gps/ene/sigma 2.0 MeV
/gate/source/mybeam/gps/direction 0 0 1


#=====================================================
# VISUALISATION
#=====================================================

# /vis/open OGLSX
# /vis/viewer/set/viewpointThetaPhi 40 45
# /vis/viewer/zoom 1
# /vis/viewer/set/style surface
# /vis/drawVolume
# /vis/viewer/flush
# /tracking/verbose 0
# /tracking/storeTrajectory 1
# /vis/scene/add/trajectories 
# /vis/scene/endOfEventAction accumulate

/control/execute visu.mac

#=====================================================
# START BEAMS
#=====================================================

# JamesRandom Ranlux64 MersenneTwister
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed 1000

# /gate/random/verbose 1
# /gate/source/verbose 0

/gate/application/noGlobalOutput
/gate/application/setTotalNumberOfPrimaries 1000
/gate/application/start



