
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# Example of proton beam in water box with Pencil Beam Scanning
# source and Phase Space output.

#-------------------oooooOOOOO00000OOOOOooooo---------------------#

#=====================================================
# VERBOSE and VISUALISATION
#=====================================================

/control/execute mac/verbose.mac
#/control/execute mac/visu.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# World
/gate/world/geometry/setXLength 5 m
/gate/world/geometry/setYLength 5 m
/gate/world/geometry/setZLength 5 m
/gate/world/setMaterial Air

# Global Box
/gate/world/daughters/name             mainbox
/gate/world/daughters/insert           box
/gate/mainbox/geometry/setXLength 40 cm
/gate/mainbox/geometry/setYLength 40 cm
/gate/mainbox/geometry/setZLength 40 cm
/gate/mainbox/placement/setTranslation 0.0 0.0 +20.1 cm
/gate/mainbox/setMaterial Water
/gate/mainbox/vis/setVisible 1
/gate/mainbox/vis/setColor blue

# Global Box Entrance
/gate/world/daughters/name             mainBoxEntrance
/gate/world/daughters/insert           cylinder
/gate/mainBoxEntrance/geometry/setRmin 0 cm
/gate/mainBoxEntrance/geometry/setRmax 10 cm
/gate/mainBoxEntrance/geometry/setPhiStart 0 deg
/gate/mainBoxEntrance/geometry/setDeltaPhi 360 deg
/gate/mainBoxEntrance/geometry/setHeight 1 nm
/gate/mainBoxEntrance/placement/setTranslation 0.0 0.0 0.0 cm
/gate/mainBoxEntrance/setMaterial Vacuum
/gate/mainBoxEntrance/vis/setVisible 1
/gate/mainBoxEntrance/vis/setColor yellow

# Beam Line
/gate/world/daughters/name             BeamLine
/gate/world/daughters/insert           cylinder
/gate/BeamLine/geometry/setRmin 0 cm
/gate/BeamLine/geometry/setRmax 10 cm
/gate/BeamLine/geometry/setPhiStart 0 deg
/gate/BeamLine/geometry/setDeltaPhi 360 deg
/gate/BeamLine/geometry/setHeight 2 m
/gate/BeamLine/placement/setTranslation 0.0 0.0 -1.5 m
/gate/BeamLine/setMaterial Vacuum
/gate/BeamLine/vis/setVisible 1
/gate/BeamLine/vis/setColor green

# Beam Line Entrance
/gate/BeamLine/daughters/name             BeamLineEntrance
/gate/BeamLine/daughters/insert           cylinder
/gate/BeamLineEntrance/geometry/setRmin 0 cm
/gate/BeamLineEntrance/geometry/setRmax 9.9 cm
/gate/BeamLineEntrance/geometry/setPhiStart 0 deg
/gate/BeamLineEntrance/geometry/setDeltaPhi 360 deg
/gate/BeamLineEntrance/geometry/setHeight 1 nm
/gate/BeamLineEntrance/placement/setTranslation 0.0 0.0 -0.9 m
/gate/BeamLineEntrance/setMaterial Vacuum
/gate/BeamLineEntrance/vis/setVisible 1
/gate/BeamLineEntrance/vis/setColor yellow

# Beam Line Middle
/gate/BeamLine/daughters/name             BeamLineMiddle
/gate/BeamLine/daughters/insert           cylinder
/gate/BeamLineMiddle/geometry/setRmin 0 cm
/gate/BeamLineMiddle/geometry/setRmax 9.9 cm
/gate/BeamLineMiddle/geometry/setPhiStart 0 deg
/gate/BeamLineMiddle/geometry/setDeltaPhi 360 deg
/gate/BeamLineMiddle/geometry/setHeight 1 nm
/gate/BeamLineMiddle/placement/setTranslation 0.0 0.0 0.0 m
/gate/BeamLineMiddle/setMaterial Vacuum
/gate/BeamLineMiddle/vis/setVisible 1
/gate/BeamLineMiddle/vis/setColor yellow

# Beam Line Exit
/gate/BeamLine/daughters/name             BeamLineExit
/gate/BeamLine/daughters/insert           cylinder
/gate/BeamLineExit/geometry/setRmin 0 cm
/gate/BeamLineExit/geometry/setRmax 9.9 cm
/gate/BeamLineExit/geometry/setPhiStart 0 deg
/gate/BeamLineExit/geometry/setDeltaPhi 360 deg
/gate/BeamLineExit/geometry/setHeight 1 nm
/gate/BeamLineExit/placement/setTranslation 0.0 0.0 +0.9 m
/gate/BeamLineExit/setMaterial Vacuum
/gate/BeamLineExit/vis/setVisible 1
/gate/BeamLineExit/vis/setColor yellow


#=====================================================
# PHYSICS
#=====================================================

/gate/physics/addPhysicsList QGSP_BERT_HP_EMY

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      mainbox 0.1 mm
/gate/physics/Electron/SetCutInRegion   mainbox 0.1 mm
/gate/physics/Positron/SetCutInRegion   mainbox 0.1 mm

/gate/physics/SetMaxStepSizeInRegion world 1 mm
/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter deuteron
/gate/physics/ActivateStepLimiter triton
/gate/physics/ActivateStepLimiter alpha
/gate/physics/ActivateStepLimiter GenericIon

/gate/physics/displayCuts

#=====================================================
# DETECTORS
#=====================================================

/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  output/IDD-proton.txt
/gate/actor/doseDistribution/attachTo    	   mainbox
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setResolution         1 1 400
/gate/actor/doseDistribution/saveEveryNSeconds     60
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableDose            true
/gate/actor/doseDistribution/enableUncertaintyDose true
/gate/actor/doseDistribution/enableNumberOfHits    false

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/stat-proton.txt
/gate/actor/stat/saveEveryNSeconds 60

/gate/actor/addActor PhaseSpaceActor PHS_ENTRANCE
/gate/actor/PHS_ENTRANCE/attachTo BeamLineEntrance
/gate/actor/PHS_ENTRANCE/useVolumeFrame true
/gate/actor/PHS_ENTRANCE/save output/BeamLineEntrance.root

/gate/actor/addActor PhaseSpaceActor PHS_MIDDLE
/gate/actor/PHS_MIDDLE/attachTo BeamLineMiddle
/gate/actor/PHS_MIDDLE/useVolumeFrame true
/gate/actor/PHS_MIDDLE/save output/BeamLineMiddle.root

/gate/actor/addActor PhaseSpaceActor PHS_EXIT
/gate/actor/PHS_EXIT/attachTo BeamLineExit
/gate/actor/PHS_EXIT/useVolumeFrame true
/gate/actor/PHS_EXIT/save output/BeamLineExit.root

/gate/actor/addActor PhaseSpaceActor PHS_GLOBALBOX
/gate/actor/PHS_GLOBALBOX/attachTo mainBoxEntrance
/gate/actor/PHS_GLOBALBOX/useVolumeFrame true
/gate/actor/PHS_GLOBALBOX/save output/GlobalBoxEntrance.root

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

#=====================================================
# BEAMS
#=====================================================

/control/execute mac/sourcePBS.mac

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries 1000
/gate/application/start
