# ----------------------------------------------------
# the following actor regularly store the current number of
# event/track/step in a file

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/saveEveryNSeconds 600


/gate/actor/addActor                             SETLEDoseActor setle
/gate/actor/setle/attachTo                       phantom
/gate/actor/setle/setVoxelSize                   2 2 2 mm
/gate/actor/setle/enableHybridino                true
/gate/actor/setle/setPrimaryMultiplicity         200
/gate/actor/setle/setSecondaryMultiplicity       400
/gate/actor/setle/enableDose                     true
/gate/actor/setle/enableUncertaintyDose          true
/gate/actor/setle/enablePrimaryDose              true
/gate/actor/setle/enablePrimaryUncertaintyDose   false
/gate/actor/setle/enableSecondaryDose            true
/gate/actor/setle/enableSecondaryUncertaintyDose false
/gate/actor/setle/save                           output/seTLE-thorax.mhd
