# ----------------------------------------------------
# the following actor regularly store the current number of
# event/track/step in a file

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/saveEveryNSeconds 600


/gate/actor/addActor                               TLEDoseActor  doseDistribution
/gate/actor/doseDistribution/attachTo    	   thorax
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 mm
/gate/actor/doseDistribution/setResolution         256 256 26
/gate/actor/doseDistribution/enableDose            true
/gate/actor/doseDistribution/save  output/TLE-thorax.mhd

/gate/actor/addActor                               DoseActor  doseDistribution2
/gate/actor/doseDistribution2/attachTo    	   thorax
/gate/actor/doseDistribution2/stepHitType           random
/gate/actor/doseDistribution2/setPosition           0 0 0 mm
/gate/actor/doseDistribution2/setResolution         256 256 26
/gate/actor/doseDistribution2/enableDose            true
/gate/actor/doseDistribution2/save  output/Dose-thorax.mhd