# 
# V O X E L I Z E D  M A T R I X   H O F F M A N   B R A I N   P H A N T O M


/gate/world/daughters/name hof_brain
/gate/world/daughters/insert ImageRegularParametrisedVolume
/gate/hof_brain/geometry/SetImage brain_phantom.h33
/gate/hof_brain/geometry/setRangeToMaterialFile range_atten_brain.dat

/gate/hof_brain/placement/setTranslation  0. 0. 0. mm
/gate/hof_brain/placement/setRotationAxis 1 0 0
/gate/hof_brain/placement/setRotationAngle 0 deg
/gate/hof_brain/attachPhantomSD

#/gate/phantom/setSkipEqualMaterials                      0
#/gate/phantom/setFictitiousEnergy                       111. keV
#/gate/phantom/setGammaDiscardEnergy                     0.1 keV

