########
# ROOT #
########
/gate/output/root/enable
/gate/output/root/setFileName benchmarkFastCT
/gate/output/root/setRootHitFlag 0
/gate/output/root/setRootSinglesFlag 1
/gate/output/root/setRootNtupleFlag 0
/gate/output/verbose 2

#########
# ASCII #
#########
/gate/output/ascii/setOutFileVoxelFlag false
/gate/output/ascii/setOutFileHitsFlag false

############
# CT Image #
############
/gate/output/imageCT/enable
/gate/output/imageCT/verbose 0
/gate/output/imageCT/setFileName benchmarkFastCT
/gate/output/imageCT/numFastPixelX 100
/gate/output/imageCT/numFastPixelY 100
/gate/output/imageCT/numFastPixelZ   1

/gate/random/setEngineName MersenneTwister
/gate/output/imageCT/setStartSeed 567489
