/gate/source/addSource tc99m_0 gps
/gate/source/verbose 0
/gate/source/tc99m_0/gps/particle gamma
/gate/source/tc99m_0/setActivity 2000000.00 Bq
/gate/source/tc99m_0/setForcedUnstableFlag false
/gate/source/tc99m_0/gps/energytype Mono
/gate/source/tc99m_0/gps/monoenergy 140.5 keV
/gate/source/tc99m_0/gps/type Point
/gate/source/tc99m_0/gps/pos/centre 0.0 0.00 0.00 mm
/gate/source/tc99m_0/gps/angtype iso
/gate/source/tc99m_0/dump 1
