
/gate/actor/addActor                         LETActor  let
/gate/actor/let/save                         output/letDose.mhd
/gate/actor/let/attachTo                     phantom
/gate/actor/let/setVoxelSize                 {PhantomSizeXY} {PhantomSizeXY} 0.2 mm
/gate/actor/let/setType						 DoseAveraged
/gate/actor/let/doParallelCalculation		 false
#/gate/actor/let/setRestricted				 false
#/gate/actor/let/setDeltaRestricted  		 50000 mm
/gate/actor/let/setDoseToWater               false
## The ID filter can be applied to any actor. ID = 1: only primary particles
/gate/actor/let/addFilter                    IDFilter
/gate/actor/let/IDFilter/selectID			 1
#/gate/actor/let/saveEveryNSeconds    		 720


/gate/actor/addActor                         LETActor  letDoseToWater
/gate/actor/letDoseToWater/save                         output/letDoseToWater.mhd
/gate/actor/letDoseToWater/attachTo                     phantom
/gate/actor/letDoseToWater/setVoxelSize                 {PhantomSizeXY} {PhantomSizeXY} 0.2 mm
/gate/actor/letDoseToWater/setType						 DoseAveraged
#/gate/actor/letDoseToWater/setRestricted				 false
#/gate/actor/letDoseToWater/setDeltaRestricted  		 50000 mm
/gate/actor/letDoseToWater/setDoseToWater               true
/gate/actor/letDoseToWater/doParallelCalculation		false
## The ID filter can be applied to any actor. ID = 1: only primary particles
/gate/actor/letDoseToWater/addFilter                    IDFilter
/gate/actor/letDoseToWater/IDFilter/selectID			1
#/gate/actor/letDoseToWater/saveEveryNSeconds     		720

## Track averaged LET
#### primary and secondary protons  
/gate/actor/addActor                         LETActor  letTrack
/gate/actor/letTrack/save                         output/letDoseToWater.mhd
/gate/actor/letTrack/attachTo                     phantom
/gate/actor/letTrack/setVoxelSize                 {PhantomSizeXY} {PhantomSizeXY} 0.2 mm
/gate/actor/letTrack/setType					  TrackAveraged
#/gate/actor/letTrack/setRestricted				  false
#/gate/actor/letTrack/setDeltaRestricted  		  50000 mm
/gate/actor/letTrack/setDoseToWater               true
/gate/actor/letTrack/doParallelCalculation		  false
#/gate/actor/letTrack/saveEveryNSeconds     			720
## The particle filter can be applied to any actor. proton: all protons (primary, secondary, tertiary...)
/gate/actor/letTrack/addFilter                    particleFilter
/gate/actor/letTrack/particleFilter/addParticle   proton
