#/control/execute mac/visu.mac
/vis/disable
/control/execute mac/verbose.mac
/gate/geometry/setMaterialDatabase data/ICRP_HUmaterials.db

# World
/gate/world/setMaterial            Vacuum
/gate/world/geometry/setXLength    5 m
/gate/world/geometry/setYLength    5 m
/gate/world/geometry/setZLength    5 m

# Physics list
/gate/physics/addPhysicsList emlivermore

# Beam
/gate/source/addSource mybeam gps
/gate/source/mybeam/gps/particle       gamma
/gate/source/mybeam/gps/ene/type       User
/gate/source/mybeam/gps/hist/type      energy
/gate/source/mybeam/gps/pos/halfx      8 mm
/gate/source/mybeam/gps/pos/halfy      8 mm
/gate/source/mybeam/gps/pos/rot1       1 0 0
/gate/source/mybeam/gps/pos/rot2       0 1 0
/gate/source/mybeam/gps/pos/centre     0 0 1060 mm
/gate/source/mybeam/gps/pos/type       Plane
/gate/source/mybeam/gps/pos/shape      Rectangle
/gate/source/mybeam/gps/ang/type       focused
/gate/source/mybeam/gps/ang/focuspoint 0 0 1000 mm

/control/execute mac/120keV.mac

# Insert phantom
/gate/world/daughters/name                              patient
/gate/world/daughters/insert                            ImageNestedParametrisedVolume
/gate/patient/geometry/setHUToMaterialFile              data/ICRP_HU2mat.txt
/gate/patient/geometry/setImage                         data/ICRP_AF.mhd
/gate/patient/geometry/TranslateTheImageAtThisIsoCenter 0 0 0 mm
/gate/patient/vis/forceWireframe

# Detection plane
/gate/world/daughters/name                   DetectorPlane
/gate/world/daughters/insert                 box
/gate/DetectorPlane/geometry/setXLength      409.6 mm
/gate/DetectorPlane/geometry/setYLength      409.6 mm
/gate/DetectorPlane/geometry/setZLength      1 nm
/gate/DetectorPlane/placement/setTranslation 0 0 -536 mm
/gate/DetectorPlane/setMaterial              Vacuum
/gate/DetectorPlane/vis/setVisible           1
/gate/DetectorPlane/vis/setColor             yellow

# Record scatter order information
/gate/actor/addActor ScatterOrderTrackInformationActor ScatterOrder
/gate/actor/ScatterOrder/attachTo                      patient

# Fluence of gamma
/gate/actor/addActor FluenceActor                    DetectorFluence
/gate/actor/DetectorFluence/save                     output/detectorMC.mhd
/gate/actor/DetectorFluence/attachTo                 DetectorPlane
/gate/actor/DetectorFluence/stepHitType              pre
/gate/actor/DetectorFluence/setResolution            128 128 1
/gate/actor/DetectorFluence/enableScatter            true
/gate/actor/DetectorFluence/enableUncertainty        true
/gate/actor/DetectorFluence/responseDetectorFilename data/responseDetector.txt
#/gate/actor/DetectorFluence/scatterOrderFilename     output/scatter_run%04d_order%04d.mhd

# Save particles stats
/gate/actor/addActor  SimulationStatisticActor stat
/gate/actor/stat/save output/statsMC.txt

/gate/run/initialize

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed 123456

/gate/application/setTimeSlice 1 s
/gate/application/setTimeStart 0 s
/gate/application/setTimeStop 1 s

/gate/application/setTotalNumberOfPrimaries 100000
/gate/application/start

