
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# Example of photon beam in patient CT image.  Output is a 3D dose
# distribution map (with associated uncertainty).

#-------------------oooooOOOOO00000OOOOOooooo---------------------#


#=====================================================
# VERBOSE and VISUALISATION
#=====================================================

/control/execute mac/verbose.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

#=====================================================
# Generate materials from Hounsfield units
/gate/HounsfieldMaterialGenerator/SetMaterialTable                  data/Schneider2000MaterialsTable.txt
/gate/HounsfieldMaterialGenerator/SetDensityTable                   data/Schneider2000DensitiesTable.txt
/gate/HounsfieldMaterialGenerator/SetDensityTolerance               0.1 g/cm3
/gate/HounsfieldMaterialGenerator/SetOutputMaterialDatabaseFilename data/patient-HUmaterials.db
/gate/HounsfieldMaterialGenerator/SetOutputHUMaterialFilename       data/patient-HU2mat.txt
/gate/HounsfieldMaterialGenerator/Generate

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    2.0 m
/gate/world/geometry/setYLength    2.0 m
/gate/world/geometry/setZLength    2.0 m

#=====================================================
# patient CT
/gate/world/daughters/name                      patient
/gate/world/daughters/insert                    ImageRegionalizedVolume

/gate/geometry/setMaterialDatabase              data/patient-HUmaterials.db
/gate/patient/geometry/setHUToMaterialFile      data/patient-HU2mat.txt
/gate/patient/geometry/setImage                 data/patient-2mm.mhd

# Generate the dmap (needed by ImageRegionalizedVolume)
/gate/patient/geometry/buildAndDumpDistanceTransfo   data/patient-2mm-dmap.mhd
# Use it
/gate/patient/geometry/distanceMap                   data/patient-2mm-dmap.mhd

# Optional : dump used image
#/gate/patient/geometry/buildAndDumpLabeledImage  data/patient-2mm-labeled.mhd

/gate/patient/placement/setTranslation                  0 0 0 mm
/gate/patient/geometry/TranslateTheImageAtThisIsoCenter 109.7 99.3 146.2 mm
#/gate/patient/geometry/enableBoundingBoxOnly true
/gate/patient/vis/setColor blue

#=====================================================
# PHYSICS
#=====================================================

/gate/physics/addPhysicsList emstandard_opt3

/gate/physics/Gamma/SetCutInRegion      world 10 mm
/gate/physics/Electron/SetCutInRegion   world 10 mm
/gate/physics/Positron/SetCutInRegion   world 10 mm

/gate/physics/Gamma/SetCutInRegion      patient 0.5 mm
/gate/physics/Electron/SetCutInRegion   patient 0.5 mm
/gate/physics/Positron/SetCutInRegion   patient 0.5 mm

/gate/physics/displayCuts
/gate/physics/print output/physics.txt

#=====================================================
# DETECTORS
#=====================================================

# ----------------------------------------------------
# the following actor regularly store the current number of
# event/track/step in a file

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/stat-photon.txt
# /gate/actor/stat/saveEveryNSeconds 60

# ----------------------------------------------------
# the following actor stores 3D distributions of
# dose/edep/uncertainty/nbHit into files (mhd image file format)

/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/attachTo    	   patient
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 mm
/gate/actor/doseDistribution/setVoxelSize          2 2 2 mm
# /gate/actor/doseDistribution/saveEveryNSeconds     60
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep true
/gate/actor/doseDistribution/enableDose            true
/gate/actor/doseDistribution/enableNumberOfHits    false
/gate/actor/doseDistribution/save                  output/photon.mhd

#=====================================================
# INITIALISATION and START
#=====================================================

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

# Enable the following lines to display available and enabled processes
# /gate/physics/processList Available
# /gate/physics/processList Enabled

#=====================================================
# BEAMS
#=====================================================

/control/execute mac/beam-photon.mac

#=====================================================
# START BEAMS
#=====================================================

/gate/application/noGlobalOutput
/gate/run/enableGlobalOutput false

/gate/random/setEngineName MersenneTwister
/vis/disable
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries 10000000
/gate/application/start
