#=====================================================
# VERBOSE and VISUALISATION 
#=====================================================

/gate/verbose Physic    3
/gate/verbose Cuts      1
/gate/verbose SD        0
/gate/verbose Actions   0
/gate/verbose Actor     0
/gate/verbose Step      0
/gate/verbose Error     0
/gate/verbose Warning   0
/gate/verbose Output    0
/gate/verbose Beam      0
/gate/verbose Volume    10
/gate/verbose Image     0
/gate/verbose Geometry  0
/tracking/verbose	0

#/control/execute mac/visu.mac

#=====================================================
# GEOMETRY and ACTORS
#=====================================================

/gate/geometry/setMaterialDatabase data/myGateMaterials.db

# -----------------------------------------------------
# Fluorescent box or fluorescent voxelised phantom
# -----------------------------------------------------

#/control/execute mac/fluoBoxOption.mac
# or
/control/execute mac/fluoPhantomOption.mac

#=====================================================
# PHYSIC
#=====================================================

# -----------------------------------------------------
# PhysicsList-builder or userPhysics
# -----------------------------------------------------

# Builders em: emstandard
#              emstandard_opt1
#              emstandard_opt2
#              emstandard_opt3
#              emlivermore
#              emlivermore_polar
#              empenelope
#              emDNAphysics
# Builders hadronic: QGSP_BERT
#                    FTFP_BERT
#                    QGSP_BIC
#                    ...

/gate/physics/addPhysicsList emlivermore
#/process/em/fluo  false  
#/process/em/auger false

# or
#/control/execute mac/userPhysics.mac

# -----------------------------------------------------

/gate/physics/displayCuts

#=====================================================
# BEAM
#=====================================================

/gate/source/addSource              xraygun   gps
/gate/source/xraygun/gps/particle   gamma
/gate/source/xraygun/gps/monoenergy 100 keV 
/gate/source/xraygun/gps/type       Point
/gate/source/xraygun/gps/centre     0 0 0 mm 
/gate/source/xraygun/gps/ang/type   iso      

#=====================================================
# MAIN
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed 10
/gate/run/enableGlobalOutput true
/gate/run/initialize

# PARTICLE
/gate/application/setTotalNumberOfPrimaries 100000
/gate/application/start

