#
#       P H Y S I C S
#

/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel

/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel StandardModel

/gate/physics/addProcess GammaConversion
/gate/physics/processes/GammaConversion/setModel StandardModel

/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/processes/ElectronIonisation/setModel StandardModel e+
/gate/physics/processes/ElectronIonisation/setStepFunction e+ 0.2 0.1 mm
/gate/physics/processes/ElectronIonisation/setStepFunction e- 0.2 0.1 mm

/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+

/gate/physics/addProcess PositronAnnihilation

/gate/physics/addProcess MultipleScattering
/gate/physics/processes/MultipleScattering/setGeometricalStepLimiterType e- distanceToBoundary
/gate/physics/processes/MultipleScattering/setGeometricalStepLimiterType e+ distanceToBoundary



/gate/physics/processList Enabled
/gate/physics/processList Initialized

#
#       C U T S
#


# Cuts for particle in NEMACylinder
/gate/physics/Gamma/SetCutInRegion      NEMACylinder 0.001 cm
/gate/physics/Electron/SetCutInRegion   NEMACylinder 0.001 cm
/gate/physics/Positron/SetCutInRegion   NEMACylinder 0.001 cm

