#################
#               #
#  S O U R C E  #
#               #
#################

#/gate/source/addSource twogamma
#/gate/source/twogamma/setActivity 1000. becquerel
#/gate/source/twogamma/gps/particle gamma
#/gate/source/twogamma/setType backtoback
#/gate/source/twogamma/gps/energytype Mono
#/gate/source/twogamma/gps/monoenergy 511. keV
#/gate/source/twogamma/gps/centre 0.0 0.0 0.0 cm
#/gate/source/twogamma/gps/angtype iso

#/gate/source/addSource F18LineSource
#/gate/source/F18LineSource/setActivity 100000. becquerel
#/gate/source/F18LineSource/gps/particle e+
#/gate/source/F18LineSource/gps/energytype Fluor18
#/gate/source/F18LineSource/gps/centre 0.0 0.0 0.0 cm
#/gate/source/F18LineSource/gps/angtype iso

/gate/source/addSource F18LineSource
/gate/source/F18LineSource/setActivity 100000. becquerel

/gate/source/F18LineSource/gps/particle e+
/gate/source/F18LineSource/setForcedUnstableFlag true
/gate/source/F18LineSource/setForcedHalfLife 6586.2 s
/gate/source/F18LineSource/gps/energytype Fluor18
/gate/source/F18LineSource/gps/type Volume
/gate/source/F18LineSource/gps/shape Cylinder
/gate/source/F18LineSource/gps/radius .5 mm
/gate/source/F18LineSource/gps/halfz 34.0 cm
/gate/source/F18LineSource/gps/angtype iso
/gate/source/F18LineSource/gps/centre 0. -2.0 0. cm

/gate/source/addSource O15LineSource
/gate/source/O15LineSource/setActivity 100000. becquerel
/gate/source/O15LineSource/gps/particle e+
/gate/source/O15LineSource/setForcedUnstableFlag true
/gate/source/O15LineSource/setForcedHalfLife 122.24 s
/gate/source/O15LineSource/gps/energytype Oxygen15
/gate/source/O15LineSource/gps/type Volume
/gate/source/O15LineSource/gps/shape Cylinder
/gate/source/O15LineSource/gps/radius .5 mm
/gate/source/O15LineSource/gps/halfz 34.0 cm
/gate/source/O15LineSource/gps/angtype iso
/gate/source/O15LineSource/gps/centre 0. 2.0 0. cm

/gate/source/list

