
#     T E T E
/gate/world/daughters/name						cylindricalPET
/gate/world/daughters/insert 					cylinder
/gate/cylindricalPET/setMaterial 				Air
/gate/cylindricalPET/geometry/setRmax 			50 cm
/gate/cylindricalPET/geometry/setRmin 			28 cm
/gate/cylindricalPET/geometry/setHeight 		24.02 cm
/gate/cylindricalPET/vis/forceWireframe

#    S H I E L D I N G
/gate/cylindricalPET/daughters/name				Shielding
/gate/cylindricalPET/daughters/insert 			cylinder
/gate/Shielding/setMaterial 					Lead
/gate/Shielding/geometry/setRmax 				46.132 cm
/gate/Shielding/geometry/setRmin 				28 cm
/gate/Shielding/geometry/setHeight 				2.86 cm
/gate/Shielding/vis/forceWireframe
/gate/Shielding/vis/setColor					yellow

#  R E P E A T   S H I E L D I N G
/gate/Shielding/repeaters/insert				linear
/gate/Shielding/linear/setRepeatNumber 			2
/gate/Shielding/linear/setRepeatVector 			0. 0. 21.16 cm

#   F E U I L L E   A L U M I N I U M
/gate/cylindricalPET/daughters/name				coucheAlu
/gate/cylindricalPET/daughters/insert 			cylinder
/gate/coucheAlu/setMaterial 					Aluminium
/gate/coucheAlu/geometry/setRmax 				43.2 cm
/gate/coucheAlu/geometry/setRmin 				43.1 cm
/gate/coucheAlu/geometry/setHeight 				18.3 cm
/gate/coucheAlu/vis/forceWireframe

#     D E T E C T E U R  =  R S E C T O R
/gate/cylindricalPET/daughters/name				rsector
/gate/cylindricalPET/daughters/insert 			box
/gate/rsector/geometry/setXLength 				40 mm
/gate/rsector/geometry/setYLength 				94.5 mm
/gate/rsector/geometry/setZLength 				18.3 cm
/gate/rsector/setMaterial 						Glass
/gate/rsector/placement/setTranslation 			45.2 0 0 cm
/gate/rsector/vis/forceWireframe

#     M O D U L E
/gate/rsector/daughters/name					module
/gate/rsector/daughters/insert 					box
/gate/module/geometry/setXLength 				20 mm
/gate/module/geometry/setYLength 				94.5 mm
/gate/module/geometry/setZLength 				18.3 cm
/gate/module/setMaterial 						PTFE
/gate/module/placement/setTranslation  			-10 0 0 mm
/gate/module/vis/forceWireframe

#      C R Y S T A L
/gate/module/daughters/name						crystal
/gate/module/daughters/insert 					box
/gate/crystal/geometry/setXLength 				20 mm
/gate/crystal/geometry/setYLength 				4 mm
/gate/crystal/geometry/setZLength 				6 mm
/gate/crystal/setMaterial 						GSO
/gate/crystal/placement/setTranslation 			0 0 0 mm
/gate/crystal/vis/forceWireframe

#     L A Y E R   G S O
/gate/crystal/daughters/name					GSO
/gate/crystal/daughters/insert 					box
/gate/GSO/geometry/setXLength 					20 mm
/gate/GSO/geometry/setYLength 					4 mm
/gate/GSO/geometry/setZLength 					6 mm
/gate/GSO/placement/setTranslation 				0 0 0 mm
/gate/GSO/setMaterial 							GSO
/gate/GSO/vis/forceWireframe

#  R E P E T I T I O N    C R I S T A L
/gate/crystal/repeaters/insert					cubicArray
/gate/crystal/cubicArray/setRepeatNumberX 		1
/gate/crystal/cubicArray/setRepeatNumberY 		22
/gate/crystal/cubicArray/setRepeatNumberZ 		29
/gate/crystal/cubicArray/setRepeatVector 		0. 4.3 6.3 mm

#  R E P E T I T I O N    R S E C T O R
/gate/rsector/repeaters/insert					ring
/gate/rsector/ring/setRepeatNumber 				28

#	A T T A C H    S Y S T E M 
/gate/systems/cylindricalPET/rsector/attach		rsector
/gate/systems/cylindricalPET/module/attach 		module
/gate/systems/cylindricalPET/crystal/attach 	crystal
/gate/systems/cylindricalPET/layer0/attach 		GSO
/gate/GSO/attachCrystalSD

/gate/systems/cylindricalPET/describe

