#=======================================
# VISU
#=======================================
#/vis/open				OGLIX
#/vis/viewer/set/viewpointThetaPhi 	0 0
#/vis/viewer/zoom 			        2.0
#/vis/drawVolume
#/tracking/storeTrajectory		1
#/vis/scene/add/trajectories 
##/vis/scene/endOfEventAction accumulate

#======================================
# VERBOSITY
#======================================
/control/verbose	0
/run/verbose		1
/tracking/verbose	0
/event/verbose 		0
/gate/verbose Beam      0
/gate/verbose Actor     0

#======================================
# GEOMETRY
#======================================
/gate/geometry/setMaterialDatabase ./GateMaterials.db
/gate/geometry/setMaterialDatabase ./GateMaterialsGPU.db

#=============================================
#     W O R L D
#=============================================

/gate/world/geometry/setXLength       400. cm
/gate/world/geometry/setYLength       400. cm
/gate/world/geometry/setZLength       400. cm
/gate/world/setMaterial 	      Vacuum

#===================================================
# SCANNER OPTICAL
#===================================================

/gate/world/daughters/name                      OpticalSystem
/gate/world/daughters/insert                    box
/gate/OpticalSystem/geometry/setXLength         10. cm
/gate/OpticalSystem/geometry/setYLength         10. cm
/gate/OpticalSystem/geometry/setZLength         2.0 cm
/gate/OpticalSystem/placement/setTranslation    0 0 3.0 cm
/gate/OpticalSystem/setMaterial                 Air

/gate/OpticalSystem/daughters/name              crystal
/gate/OpticalSystem/daughters/insert            box
/gate/crystal/geometry/setXLength               10. cm
/gate/crystal/geometry/setYLength               10. cm
/gate/crystal/geometry/setZLength               1.0 cm
/gate/crystal/placement/setTranslation          0 0 -0.5 cm
/gate/crystal/setMaterial                       Air
/gate/crystal/vis/setColor                      green
/gate/crystal/vis/forceSolid
/gate/crystal/attachCrystalSD
/gate/systems/OpticalSystem/crystal/attach      crystal

/gate/OpticalSystem/daughters/name              Electronics
/gate/OpticalSystem/daughters/insert            box
/gate/Electronics/geometry/setXLength           10.  cm
/gate/Electronics/geometry/setYLength           10.  cm
/gate/Electronics/geometry/setZLength           1.0 cm
/gate/Electronics/setMaterial                   Air                  
/gate/Electronics/placement/setTranslation      0 0 0.5 cm
/gate/Electronics/vis/setColor                  yellow
/gate/Electronics/vis/forceSolid


#===============================================================
# Optical photons Detection Surface should be DIELECTRIC-METAL
#===============================================================

/gate/crystal/surfaces/name                           Detection1
/gate/crystal/surfaces/insert                         Electronics
/gate/crystal/surfaces/Detection1/setSurface          perfect_apd  

/gate/Electronics/surfaces/name                       Detection2
/gate/Electronics/surfaces/insert                     crystal
/gate/Electronics/surfaces/Detection2/setSurface      perfect_apd  


#===================================================
# PHANTOM
#===================================================

/gate/world/daughters/name					biolumi
/gate/world/daughters/insert					fictitiousVoxelMap

/gate/biolumi/geometry/insertReader				interfile
/gate/biolumi/interfileReader/insertTranslator 			range
/gate/biolumi/interfileReader/rangeTranslator/readTable 	range_biolumi.dat
/gate/biolumi/interfileReader/rangeTranslator/describe 		1
/gate/biolumi/interfileReader/readFile 				biolumi_header.hdr
/gate/biolumi/placement/setTranslation  			0. 0. 0. mm
/gate/biolumi/placement/setRotationAxis 			1 0 0
/gate/biolumi/placement/setRotationAngle 			0 deg

#==================================================
# PHYSICS
#==================================================
/gate/physics/addProcess 	OpticalAbsorption
/gate/physics/addProcess 	OpticalRayleigh
/gate/physics/addProcess 	OpticalBoundary
/gate/physics/addProcess 	OpticalMie
#/gate/physics/addProcess 	OpticalWLS

/gate/physics/processList 	Enabled
/gate/physics/processList 	Initialized

#========================================
# INITIALIZATION
#========================================
/gate/run/initialize

#==================================================
# DIGITIZER
#==================================================
/gate/digitizer/Singles/insert                        opticaladder 
/gate/digitizer/Singles/insert                        readout 
/gate/digitizer/Singles/readout/setDepth              1

#=======================================
# SOURCES
#=======================================

# V O X E L    S O U R C E

# VERSION GPU
/gate/source/addSource				voxel GPUOpticalVoxel
/gate/source/voxel/attachPhantomTo 		biolumi
/gate/source/voxel/setGPUBufferSize 		50000
/gate/source/voxel/setGPUDeviceID 		1

/gate/source/voxel/reader/insert 			      		interfile
/gate/source/voxel/interfileReader/translator/insert			range
/gate/source/voxel/interfileReader/rangeTranslator/readTable 		activites_optical.dat
/gate/source/voxel/interfileReader/rangeTranslator/describe 		1
/gate/source/voxel/interfileReader/verbose 				0
/gate/source/voxel/interfileReader/readFile 				biolumi_header_bed.hdr

/gate/source/voxel/gps/particle 					opticalphoton
/gate/source/voxel/gps/energytype 					Mono
/gate/source/voxel/gps/monoenergy 					2.21 eV
/gate/source/voxel/setPosition  					0. 0. -6. cm
/gate/source/voxel/gps/angtype 						iso


#==================================================
# DATA OUTPUT
#==================================================

/gate/output/ascii/enable
/gate/output/ascii/setFileName                  ListModeOPTICAL_gpu_
/gate/output/ascii/setOutFileHitsFlag           1
/gate/output/ascii/setOutFileSinglesFlag        0
/gate/output/ascii/setOutFileCoincidencesFlag   0

/gate/output/root/disable
/gate/output/binary/disable

#==============================================
# RANDOM
#==============================================
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed 10

#==============================================
# START
#==============================================

/gate/application/setTimeStart     0.0 ns
/gate/application/setTimeSlice     1.0 s
/gate/application/setTimeStop      1.0 s
/gate/application/startDAQ









