########
# ROOT #
########
/gate/output/root/setSaveRndmFlag 1
/gate/output/root/setFileName benchmarkCT
/gate/output/root/setRootHitFlag 0
/gate/output/root/setRootSinglesFlag 1
/gate/output/root/setRootNtupleFlag 0
/gate/output/verbose 2

#########
# ASCII #
#########
/gate/output/ascii/setOutFileVoxelFlag false
/gate/output/ascii/setOutFileHitsFlag false
/gate/output/ascii/disable

############
# CT Image #
############
/gate/output/imageCT/verbose 0
/gate/output/imageCT/enable
/gate/output/imageCT/setFileName benchmarkCT

/gate/random/setEngineName MersenneTwister
/gate/output/imageCT/setStartSeed 567489
