#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# Photon beam from a Linac into a box with water/alu/lung. See Figure4
# from [Jan et al PMB 2011].

#-------------------oooooOOOOO00000OOOOOooooo---------------------#


#=====================================================
# VERBOSE and VISUALISATION
#=====================================================

/control/execute mac/verbose.mac
#/control/execute mac/visu.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# World
/gate/world/geometry/setXLength 5 m
/gate/world/geometry/setYLength 5 m
/gate/world/geometry/setZLength 5 m
/gate/world/setMaterial Vacuum


# Global Box
/gate/world/daughters/name             mainbox
/gate/world/daughters/insert           box
/gate/mainbox/geometry/setXLength      30.5 cm
/gate/mainbox/geometry/setYLength      39.5 cm
/gate/mainbox/geometry/setZLength      30.0 cm
/gate/mainbox/placement/setTranslation 0 0 0 cm
/gate/mainbox/setMaterial Water
/gate/mainbox/vis/setVisible 0
/gate/mainbox/vis/setColor blue

# First Water slice
/gate/mainbox/daughters/name    water_slice_1
/gate/mainbox/daughters/insert  box
/gate/water_slice_1/geometry/setXLength 30.5  cm
/gate/water_slice_1/geometry/setYLength 39.5 cm
/gate/water_slice_1/geometry/setZLength 3  cm
/gate/water_slice_1/placement/setTranslation 0  0  -13.5 cm
/gate/water_slice_1/setMaterial Water
/gate/water_slice_1/vis/setVisible 1
/gate/water_slice_1/vis/setColor blue

# Second Alu slice
/gate/mainbox/daughters/name    alu_slice
/gate/mainbox/daughters/insert  box
/gate/alu_slice/geometry/setXLength 30.5 cm
/gate/alu_slice/geometry/setYLength 39.5 cm
/gate/alu_slice/geometry/setZLength  2.0 cm
/gate/alu_slice/placement/setTranslation 0 0 -11 cm
/gate/alu_slice/setMaterial Aluminium
/gate/alu_slice/vis/setVisible 1
/gate/alu_slice/vis/setColor yellow

# Third Lung slice
/gate/mainbox/daughters/name    lung_slice
/gate/mainbox/daughters/insert  box
/gate/lung_slice/geometry/setXLength 30.5 cm
/gate/lung_slice/geometry/setYLength 39.5 cm
/gate/lung_slice/geometry/setZLength  7.0 cm
/gate/lung_slice/placement/setTranslation 0 0 -6.5 cm
/gate/lung_slice/setMaterial Lung
/gate/lung_slice/vis/setVisible 1
/gate/lung_slice/vis/setColor red

# Fourth Water slice
/gate/mainbox/daughters/name    water_slice_2
/gate/mainbox/daughters/insert  box
/gate/water_slice_2/geometry/setXLength 30.5  cm
/gate/water_slice_2/geometry/setYLength 39.5 cm
/gate/water_slice_2/geometry/setZLength 18  cm
/gate/water_slice_2/placement/setTranslation 0  0  6 cm
/gate/water_slice_2/setMaterial Water
/gate/water_slice_2/vis/setVisible 1
/gate/water_slice_2/vis/setColor blue



#collimater
/gate/world/daughters/name             colli1
/gate/world/daughters/insert           box
/gate/colli1/geometry/setXLength      200 cm
/gate/colli1/geometry/setYLength      200 cm
/gate/colli1/geometry/setZLength      .0001 mm
/gate/colli1/placement/setTranslation 0 100.75 -15.00005 cm
/gate/colli1/setMaterial Vacuum
/gate/colli1/vis/setVisible 1
/gate/colli1/vis/setColor white

/gate/world/daughters/name             colli2
/gate/world/daughters/insert           box
/gate/colli2/geometry/setXLength      200 cm
/gate/colli2/geometry/setYLength      200 cm
/gate/colli2/geometry/setZLength      .0001 mm
/gate/colli2/placement/setTranslation 0 -100.75 -15.00005 cm
/gate/colli2/setMaterial Vacuum
/gate/colli2/vis/setVisible 1
/gate/colli2/vis/setColor white

/gate/world/daughters/name             colli3
/gate/world/daughters/insert           box
/gate/colli3/geometry/setXLength      200 cm
/gate/colli3/geometry/setYLength      1.5 cm
/gate/colli3/geometry/setZLength      .0001 mm
/gate/colli3/placement/setTranslation 100.75 0 -15.00005 cm
/gate/colli3/setMaterial Vacuum
/gate/colli3/vis/setVisible 1
/gate/colli3/vis/setColor white

/gate/world/daughters/name             colli4
/gate/world/daughters/insert           box
/gate/colli4/geometry/setXLength      200 cm
/gate/colli4/geometry/setYLength      1.5 cm
/gate/colli4/geometry/setZLength      .0001 mm
/gate/colli4/placement/setTranslation  -100.75 0 -15.00005 cm
/gate/colli4/setMaterial Vacuum
/gate/colli4/vis/setVisible 1
/gate/colli4/vis/setColor white


/gate/geometry/setIonisationPotential Water 75 eV
/gate/geometry/setIonisationPotential Aluminium 166 eV
/gate/geometry/setIonisationPotential Lung 75.2 eV
/gate/geometry/setIonisationPotential Air 85.7 eV


#=====================================================
# PHYSICS
#=====================================================

/gate/physics/addPhysicsList emstandard_opt3

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      mainbox 0.1 mm
/gate/physics/Electron/SetCutInRegion   mainbox 0.1 mm
/gate/physics/Positron/SetCutInRegion   mainbox 0.1 mm

/gate/physics/displayCuts


#=====================================================
# DETECTORS
#=====================================================

/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  output/Photon-18MeV.root
/gate/actor/doseDistribution/attachTo    	   mainbox
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               5 5 300 mm
/gate/actor/doseDistribution/setVoxelSize          5 5 2 mm
/gate/actor/doseDistribution/saveEveryNSeconds     60
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep true
/gate/actor/doseDistribution/enableDose            true
/gate/actor/doseDistribution/enableUncertaintyDose true
/gate/actor/doseDistribution/enableNumberOfHits    true

/gate/actor/addActor                SimulationStatisticActor stat
/gate/actor/stat/save               output/statPhoton-18MeV.txt
/gate/actor/stat/saveEveryNSeconds  60

/gate/actor/addActor                    ParticleInVolumeActor counter
/gate/actor/counter/save                output/counterPhoton-18MeV.txt
/gate/actor/counter/saveEveryNSeconds   60
/gate/actor/counter/addFilter           IDFilter
/gate/actor/counter/IDFilter/selectID   1
/gate/actor/counter/attachTo            mainbox
/gate/actor/counter/setResolution       1 1 1

/gate/actor/addActor       KillActor kill1
/gate/actor/kill1/attachTo colli1
/gate/actor/kill1/save     output/colli1.txt

/gate/actor/addActor       KillActor kill2
/gate/actor/kill2/attachTo colli2
/gate/actor/kill2/save     output/colli2.txt

/gate/actor/addActor       KillActor kill3
/gate/actor/kill3/attachTo colli3
/gate/actor/kill3/save     output/colli3.txt

/gate/actor/addActor       KillActor kill4
/gate/actor/kill4/attachTo colli4
/gate/actor/kill4/save     output/colli4.txt


#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

#=====================================================
# BEAMS
#=====================================================

/gate/source/addSource mybeam gps
/gate/source/mybeam/gps/particle gamma

#NRC spectrum from BEAM for an 18 MV Varian Clinac 2100
/gate/source/mybeam/gps/ene/type   User
/gate/source/mybeam/gps/hist/type  energy
/gate/source/mybeam/gps/hist/point 0          0.0
/gate/source/mybeam/gps/hist/point 2.500E-01  4.0337E-06
/gate/source/mybeam/gps/hist/point 5.000E-01  9.5959E-06
/gate/source/mybeam/gps/hist/point 7.500E-01  1.2065E-05
/gate/source/mybeam/gps/hist/point 1.000E+00  1.3781E-05
/gate/source/mybeam/gps/hist/point 1.250E+00  1.4319E-05
/gate/source/mybeam/gps/hist/point 1.500E+00  1.4062E-05
/gate/source/mybeam/gps/hist/point 1.750E+00  1.3924E-05
/gate/source/mybeam/gps/hist/point 2.000E+00  1.3086E-05
/gate/source/mybeam/gps/hist/point 2.250E+00  1.2041E-05
/gate/source/mybeam/gps/hist/point 2.500E+00  1.1453E-05
/gate/source/mybeam/gps/hist/point 2.750E+00  1.0889E-05
/gate/source/mybeam/gps/hist/point 3.000E+00  1.0112E-05
/gate/source/mybeam/gps/hist/point 3.250E+00  9.3359E-06
/gate/source/mybeam/gps/hist/point 3.500E+00  8.7616E-06
/gate/source/mybeam/gps/hist/point 3.750E+00  8.1366E-06
/gate/source/mybeam/gps/hist/point 4.000E+00  7.6597E-06
/gate/source/mybeam/gps/hist/point 4.250E+00  7.1010E-06
/gate/source/mybeam/gps/hist/point 4.500E+00  6.7447E-06
/gate/source/mybeam/gps/hist/point 4.750E+00  6.2360E-06
/gate/source/mybeam/gps/hist/point 5.000E+00  5.8474E-06
/gate/source/mybeam/gps/hist/point 5.250E+00  5.4393E-06
/gate/source/mybeam/gps/hist/point 5.500E+00  5.2179E-06
/gate/source/mybeam/gps/hist/point 5.750E+00  4.8653E-06
/gate/source/mybeam/gps/hist/point 6.000E+00  4.6058E-06
/gate/source/mybeam/gps/hist/point 6.250E+00  4.2906E-06
/gate/source/mybeam/gps/hist/point 6.500E+00  4.0800E-06
/gate/source/mybeam/gps/hist/point 6.750E+00  3.8501E-06
/gate/source/mybeam/gps/hist/point 7.000E+00  3.6913E-06
/gate/source/mybeam/gps/hist/point 7.250E+00  3.6273E-06
/gate/source/mybeam/gps/hist/point 7.500E+00  3.2497E-06
/gate/source/mybeam/gps/hist/point 7.750E+00  3.1424E-06
/gate/source/mybeam/gps/hist/point 8.000E+00  2.8892E-06
/gate/source/mybeam/gps/hist/point 8.250E+00  2.8118E-06
/gate/source/mybeam/gps/hist/point 8.500E+00  2.6369E-06
/gate/source/mybeam/gps/hist/point 8.750E+00  2.5523E-06
/gate/source/mybeam/gps/hist/point 9.000E+00  2.3753E-06
/gate/source/mybeam/gps/hist/point 9.250E+00  2.2205E-06
/gate/source/mybeam/gps/hist/point 9.500E+00  2.1544E-06
/gate/source/mybeam/gps/hist/point 9.750E+00  2.0812E-06
/gate/source/mybeam/gps/hist/point 1.000E+01  2.0213E-06
/gate/source/mybeam/gps/hist/point 1.025E+01  1.9223E-06
/gate/source/mybeam/gps/hist/point 1.050E+01  1.7353E-06
/gate/source/mybeam/gps/hist/point 1.075E+01  1.7610E-06
/gate/source/mybeam/gps/hist/point 1.100E+01  1.6670E-06
/gate/source/mybeam/gps/hist/point 1.125E+01  1.5800E-06
/gate/source/mybeam/gps/hist/point 1.150E+01  1.4863E-06
/gate/source/mybeam/gps/hist/point 1.175E+01  1.3896E-06
/gate/source/mybeam/gps/hist/point 1.200E+01  1.4569E-06
/gate/source/mybeam/gps/hist/point 1.225E+01  1.2893E-06
/gate/source/mybeam/gps/hist/point 1.250E+01  1.2828E-06
/gate/source/mybeam/gps/hist/point 1.275E+01  1.1637E-06
/gate/source/mybeam/gps/hist/point 1.300E+01  1.0773E-06
/gate/source/mybeam/gps/hist/point 1.325E+01  1.0395E-06
/gate/source/mybeam/gps/hist/point 1.350E+01  1.0556E-06
/gate/source/mybeam/gps/hist/point 1.375E+01  9.6263E-07
/gate/source/mybeam/gps/hist/point 1.400E+01  9.1664E-07
/gate/source/mybeam/gps/hist/point 1.425E+01  8.9720E-07
/gate/source/mybeam/gps/hist/point 1.450E+01  8.7556E-07
/gate/source/mybeam/gps/hist/point 1.475E+01  7.7567E-07
/gate/source/mybeam/gps/hist/point 1.500E+01  7.4345E-07
/gate/source/mybeam/gps/hist/point 1.525E+01  6.8121E-07
/gate/source/mybeam/gps/hist/point 1.550E+01  6.3706E-07
/gate/source/mybeam/gps/hist/point 1.575E+01  5.4163E-07
/gate/source/mybeam/gps/hist/point 1.600E+01  5.6762E-07
/gate/source/mybeam/gps/hist/point 1.625E+01  4.8476E-07
/gate/source/mybeam/gps/hist/point 1.650E+01  4.3953E-07
/gate/source/mybeam/gps/hist/point 1.675E+01  4.0895E-07
/gate/source/mybeam/gps/hist/point 1.700E+01  3.2791E-07
/gate/source/mybeam/gps/hist/point 1.725E+01  2.8358E-07
/gate/source/mybeam/gps/hist/point 1.750E+01  2.1152E-07
/gate/source/mybeam/gps/hist/point 1.775E+01  1.3752E-07
/gate/source/mybeam/gps/hist/point 1.800E+01  6.5072E-08
/gate/source/mybeam/gps/hist/point 1.825E+01  6.5072E-13



/gate/source/mybeam/gps/position       0 0 -115 cm

/gate/source/mybeam/gps/type Point
/gate/source/mybeam/gps/ang/type iso
/gate/source/mybeam/gps/ang/mintheta 179.3 deg
/gate/source/mybeam/gps/ang/maxtheta 180 deg
/gate/source/mybeam/gps/ang/minphi    0 deg
/gate/source/mybeam/gps/ang/maxphi  360 deg


#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries 1000000
/gate/application/start
