
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# Example of photon beam in patient CT image.  Output is a 3D dose
# distribution map (with associated uncertainty). Two different
# navigators are tested NestedParameterized and Regionalized. 

#-------------------oooooOOOOO00000OOOOOooooo---------------------#


#=====================================================
# VERBOSE and VISUALISATION 
#=====================================================

/control/execute mac/verbose.mac
#/control/execute mac/visu.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# Generate materials from Hounsfield units
#/gate/HounsfieldMaterialGenerator/SetMaterialTable                  data/SimpleMaterialsTable.txt 
/gate/HounsfieldMaterialGenerator/SetMaterialTable                  data/Schneider2000MaterialsTable.txt 
/gate/HounsfieldMaterialGenerator/SetDensityTable                   data/Schneider2000DensitiesTable.txt
/gate/HounsfieldMaterialGenerator/SetDensityTolerance               0.5 g/cm3
/gate/HounsfieldMaterialGenerator/SetOutputMaterialDatabaseFilename data/patient-HUmaterials.db
/gate/HounsfieldMaterialGenerator/SetOutputHUMaterialFilename       data/patient-HU2mat.txt
/gate/HounsfieldMaterialGenerator/Generate

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    3.0 m
/gate/world/geometry/setYLength    3.0 m
/gate/world/geometry/setZLength    3.0 m

/gate/world/daughters/name                      patient
/gate/world/daughters/insert                    ImageNestedParametrisedVolume

/gate/geometry/setMaterialDatabase              data/patient-HUmaterials.db
/gate/patient/geometry/SetHUToMaterialFile      data/patient-HU2mat.txt
/gate/patient/geometry/SetImage                 data/patient-2mm.mhd

# optional : dump used image
/gate/patient/geometry/buildAndDumpLabeledImage  data/patient-2mm-labeled-NPV.mhd

/gate/patient/placement/setTranslation                  0 0 0 mm
/gate/patient/geometry/TranslateTheImageAtThisIsoCenter 109.7 99.3 146.2 mm

#=====================================================
# PHYSICS
#=====================================================

/control/execute mac/physicslist_EM_std.mac

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      patient 0.5 mm
/gate/physics/Electron/SetCutInRegion   patient 0.5 mm
/gate/physics/Positron/SetCutInRegion   patient 0.5 mm

/gate/physics/SetMaxStepSizeInRegion    patient 0.1 mm

/gate/physics/displayCuts
/gate/physics/print output/physics.txt

#=====================================================
# DETECTORS
#=====================================================

/control/execute mac/detectors.mac

# Set the names of the outputs
/gate/actor/stat/save              output/stat-photon-NPV2.txt
/gate/actor/doseDistribution/save  output/dose-photon-NPV2.mhd

#=====================================================
# INITIALIZATION and START
#=====================================================

/control/execute mac/start.mac
