/gate/geometry/setMaterialDatabase        data/GateMaterials.db

/gate/world/setMaterial                   Air
/gate/world/geometry/setXLength           3 m
/gate/world/geometry/setYLength           3 m
/gate/world/geometry/setZLength           3 m

/gate/world/daughters/name                Volume
/gate/world/daughters/insert              ImageNestedParametrisedVolume
/gate/Volume/geometry/setHUToMaterialFile data/vis.txt
