/gate/source/addSource mybeam1 gps
/gate/source/mybeam1/gps/particle gamma
/gate/source/mybeam1/gps/ene/mono 1 keV
/gate/source/mybeam1/gps/pos/halfx 0.004 mm
/gate/source/mybeam1/gps/pos/halfy 0.004 mm
/gate/source/mybeam1/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam1/gps/pos/type Plane
/gate/source/mybeam1/gps/pos/shape Rectangle
/gate/source/mybeam1/gps/direction 0 0 -1
 
/gate/source/addSource mybeam2 gps
/gate/source/mybeam2/gps/particle gamma
/gate/source/mybeam2/gps/ene/mono 2 keV
/gate/source/mybeam2/gps/pos/halfx 0.004 mm
/gate/source/mybeam2/gps/pos/halfy 0.004 mm
/gate/source/mybeam2/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam2/gps/pos/type Plane
/gate/source/mybeam2/gps/pos/shape Rectangle
/gate/source/mybeam2/gps/direction 0 0 -1
 
/gate/source/addSource mybeam3 gps
/gate/source/mybeam3/gps/particle gamma
/gate/source/mybeam3/gps/ene/mono 3 keV
/gate/source/mybeam3/gps/pos/halfx 0.004 mm
/gate/source/mybeam3/gps/pos/halfy 0.004 mm
/gate/source/mybeam3/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam3/gps/pos/type Plane
/gate/source/mybeam3/gps/pos/shape Rectangle
/gate/source/mybeam3/gps/direction 0 0 -1
 
/gate/source/addSource mybeam4 gps
/gate/source/mybeam4/gps/particle gamma
/gate/source/mybeam4/gps/ene/mono 4 keV
/gate/source/mybeam4/gps/pos/halfx 0.004 mm
/gate/source/mybeam4/gps/pos/halfy 0.004 mm
/gate/source/mybeam4/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam4/gps/pos/type Plane
/gate/source/mybeam4/gps/pos/shape Rectangle
/gate/source/mybeam4/gps/direction 0 0 -1
 
/gate/source/addSource mybeam5 gps
/gate/source/mybeam5/gps/particle gamma
/gate/source/mybeam5/gps/ene/mono 5 keV
/gate/source/mybeam5/gps/pos/halfx 0.004 mm
/gate/source/mybeam5/gps/pos/halfy 0.004 mm
/gate/source/mybeam5/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam5/gps/pos/type Plane
/gate/source/mybeam5/gps/pos/shape Rectangle
/gate/source/mybeam5/gps/direction 0 0 -1
 
/gate/source/addSource mybeam6 gps
/gate/source/mybeam6/gps/particle gamma
/gate/source/mybeam6/gps/ene/mono 6 keV
/gate/source/mybeam6/gps/pos/halfx 0.004 mm
/gate/source/mybeam6/gps/pos/halfy 0.004 mm
/gate/source/mybeam6/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam6/gps/pos/type Plane
/gate/source/mybeam6/gps/pos/shape Rectangle
/gate/source/mybeam6/gps/direction 0 0 -1
 
/gate/source/addSource mybeam7 gps
/gate/source/mybeam7/gps/particle gamma
/gate/source/mybeam7/gps/ene/mono 7 keV
/gate/source/mybeam7/gps/pos/halfx 0.004 mm
/gate/source/mybeam7/gps/pos/halfy 0.004 mm
/gate/source/mybeam7/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam7/gps/pos/type Plane
/gate/source/mybeam7/gps/pos/shape Rectangle
/gate/source/mybeam7/gps/direction 0 0 -1
 
/gate/source/addSource mybeam8 gps
/gate/source/mybeam8/gps/particle gamma
/gate/source/mybeam8/gps/ene/mono 8 keV
/gate/source/mybeam8/gps/pos/halfx 0.004 mm
/gate/source/mybeam8/gps/pos/halfy 0.004 mm
/gate/source/mybeam8/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam8/gps/pos/type Plane
/gate/source/mybeam8/gps/pos/shape Rectangle
/gate/source/mybeam8/gps/direction 0 0 -1
 
/gate/source/addSource mybeam9 gps
/gate/source/mybeam9/gps/particle gamma
/gate/source/mybeam9/gps/ene/mono 9 keV
/gate/source/mybeam9/gps/pos/halfx 0.004 mm
/gate/source/mybeam9/gps/pos/halfy 0.004 mm
/gate/source/mybeam9/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam9/gps/pos/type Plane
/gate/source/mybeam9/gps/pos/shape Rectangle
/gate/source/mybeam9/gps/direction 0 0 -1
 
/gate/source/addSource mybeam10 gps
/gate/source/mybeam10/gps/particle gamma
/gate/source/mybeam10/gps/ene/mono 10 keV
/gate/source/mybeam10/gps/pos/halfx 0.004 mm
/gate/source/mybeam10/gps/pos/halfy 0.004 mm
/gate/source/mybeam10/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam10/gps/pos/type Plane
/gate/source/mybeam10/gps/pos/shape Rectangle
/gate/source/mybeam10/gps/direction 0 0 -1
 
/gate/source/addSource mybeam11 gps
/gate/source/mybeam11/gps/particle gamma
/gate/source/mybeam11/gps/ene/mono 11 keV
/gate/source/mybeam11/gps/pos/halfx 0.004 mm
/gate/source/mybeam11/gps/pos/halfy 0.004 mm
/gate/source/mybeam11/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam11/gps/pos/type Plane
/gate/source/mybeam11/gps/pos/shape Rectangle
/gate/source/mybeam11/gps/direction 0 0 -1
 
/gate/source/addSource mybeam12 gps
/gate/source/mybeam12/gps/particle gamma
/gate/source/mybeam12/gps/ene/mono 12 keV
/gate/source/mybeam12/gps/pos/halfx 0.004 mm
/gate/source/mybeam12/gps/pos/halfy 0.004 mm
/gate/source/mybeam12/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam12/gps/pos/type Plane
/gate/source/mybeam12/gps/pos/shape Rectangle
/gate/source/mybeam12/gps/direction 0 0 -1
 
/gate/source/addSource mybeam13 gps
/gate/source/mybeam13/gps/particle gamma
/gate/source/mybeam13/gps/ene/mono 13 keV
/gate/source/mybeam13/gps/pos/halfx 0.004 mm
/gate/source/mybeam13/gps/pos/halfy 0.004 mm
/gate/source/mybeam13/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam13/gps/pos/type Plane
/gate/source/mybeam13/gps/pos/shape Rectangle
/gate/source/mybeam13/gps/direction 0 0 -1
 
/gate/source/addSource mybeam14 gps
/gate/source/mybeam14/gps/particle gamma
/gate/source/mybeam14/gps/ene/mono 14 keV
/gate/source/mybeam14/gps/pos/halfx 0.004 mm
/gate/source/mybeam14/gps/pos/halfy 0.004 mm
/gate/source/mybeam14/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam14/gps/pos/type Plane
/gate/source/mybeam14/gps/pos/shape Rectangle
/gate/source/mybeam14/gps/direction 0 0 -1
 
/gate/source/addSource mybeam15 gps
/gate/source/mybeam15/gps/particle gamma
/gate/source/mybeam15/gps/ene/mono 15 keV
/gate/source/mybeam15/gps/pos/halfx 0.004 mm
/gate/source/mybeam15/gps/pos/halfy 0.004 mm
/gate/source/mybeam15/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam15/gps/pos/type Plane
/gate/source/mybeam15/gps/pos/shape Rectangle
/gate/source/mybeam15/gps/direction 0 0 -1
 
/gate/source/addSource mybeam16 gps
/gate/source/mybeam16/gps/particle gamma
/gate/source/mybeam16/gps/ene/mono 16 keV
/gate/source/mybeam16/gps/pos/halfx 0.004 mm
/gate/source/mybeam16/gps/pos/halfy 0.004 mm
/gate/source/mybeam16/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam16/gps/pos/type Plane
/gate/source/mybeam16/gps/pos/shape Rectangle
/gate/source/mybeam16/gps/direction 0 0 -1
 
/gate/source/addSource mybeam17 gps
/gate/source/mybeam17/gps/particle gamma
/gate/source/mybeam17/gps/ene/mono 17 keV
/gate/source/mybeam17/gps/pos/halfx 0.004 mm
/gate/source/mybeam17/gps/pos/halfy 0.004 mm
/gate/source/mybeam17/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam17/gps/pos/type Plane
/gate/source/mybeam17/gps/pos/shape Rectangle
/gate/source/mybeam17/gps/direction 0 0 -1
 
/gate/source/addSource mybeam18 gps
/gate/source/mybeam18/gps/particle gamma
/gate/source/mybeam18/gps/ene/mono 18 keV
/gate/source/mybeam18/gps/pos/halfx 0.004 mm
/gate/source/mybeam18/gps/pos/halfy 0.004 mm
/gate/source/mybeam18/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam18/gps/pos/type Plane
/gate/source/mybeam18/gps/pos/shape Rectangle
/gate/source/mybeam18/gps/direction 0 0 -1
 
/gate/source/addSource mybeam19 gps
/gate/source/mybeam19/gps/particle gamma
/gate/source/mybeam19/gps/ene/mono 19 keV
/gate/source/mybeam19/gps/pos/halfx 0.004 mm
/gate/source/mybeam19/gps/pos/halfy 0.004 mm
/gate/source/mybeam19/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam19/gps/pos/type Plane
/gate/source/mybeam19/gps/pos/shape Rectangle
/gate/source/mybeam19/gps/direction 0 0 -1
 
/gate/source/addSource mybeam20 gps
/gate/source/mybeam20/gps/particle gamma
/gate/source/mybeam20/gps/ene/mono 20 keV
/gate/source/mybeam20/gps/pos/halfx 0.004 mm
/gate/source/mybeam20/gps/pos/halfy 0.004 mm
/gate/source/mybeam20/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam20/gps/pos/type Plane
/gate/source/mybeam20/gps/pos/shape Rectangle
/gate/source/mybeam20/gps/direction 0 0 -1
 
/gate/source/addSource mybeam21 gps
/gate/source/mybeam21/gps/particle gamma
/gate/source/mybeam21/gps/ene/mono 21 keV
/gate/source/mybeam21/gps/pos/halfx 0.004 mm
/gate/source/mybeam21/gps/pos/halfy 0.004 mm
/gate/source/mybeam21/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam21/gps/pos/type Plane
/gate/source/mybeam21/gps/pos/shape Rectangle
/gate/source/mybeam21/gps/direction 0 0 -1
 
/gate/source/addSource mybeam22 gps
/gate/source/mybeam22/gps/particle gamma
/gate/source/mybeam22/gps/ene/mono 22 keV
/gate/source/mybeam22/gps/pos/halfx 0.004 mm
/gate/source/mybeam22/gps/pos/halfy 0.004 mm
/gate/source/mybeam22/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam22/gps/pos/type Plane
/gate/source/mybeam22/gps/pos/shape Rectangle
/gate/source/mybeam22/gps/direction 0 0 -1
 
/gate/source/addSource mybeam23 gps
/gate/source/mybeam23/gps/particle gamma
/gate/source/mybeam23/gps/ene/mono 23 keV
/gate/source/mybeam23/gps/pos/halfx 0.004 mm
/gate/source/mybeam23/gps/pos/halfy 0.004 mm
/gate/source/mybeam23/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam23/gps/pos/type Plane
/gate/source/mybeam23/gps/pos/shape Rectangle
/gate/source/mybeam23/gps/direction 0 0 -1
 
/gate/source/addSource mybeam24 gps
/gate/source/mybeam24/gps/particle gamma
/gate/source/mybeam24/gps/ene/mono 24 keV
/gate/source/mybeam24/gps/pos/halfx 0.004 mm
/gate/source/mybeam24/gps/pos/halfy 0.004 mm
/gate/source/mybeam24/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam24/gps/pos/type Plane
/gate/source/mybeam24/gps/pos/shape Rectangle
/gate/source/mybeam24/gps/direction 0 0 -1
 
/gate/source/addSource mybeam25 gps
/gate/source/mybeam25/gps/particle gamma
/gate/source/mybeam25/gps/ene/mono 25 keV
/gate/source/mybeam25/gps/pos/halfx 0.004 mm
/gate/source/mybeam25/gps/pos/halfy 0.004 mm
/gate/source/mybeam25/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam25/gps/pos/type Plane
/gate/source/mybeam25/gps/pos/shape Rectangle
/gate/source/mybeam25/gps/direction 0 0 -1
 
/gate/source/addSource mybeam26 gps
/gate/source/mybeam26/gps/particle gamma
/gate/source/mybeam26/gps/ene/mono 26 keV
/gate/source/mybeam26/gps/pos/halfx 0.004 mm
/gate/source/mybeam26/gps/pos/halfy 0.004 mm
/gate/source/mybeam26/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam26/gps/pos/type Plane
/gate/source/mybeam26/gps/pos/shape Rectangle
/gate/source/mybeam26/gps/direction 0 0 -1
 
/gate/source/addSource mybeam27 gps
/gate/source/mybeam27/gps/particle gamma
/gate/source/mybeam27/gps/ene/mono 27 keV
/gate/source/mybeam27/gps/pos/halfx 0.004 mm
/gate/source/mybeam27/gps/pos/halfy 0.004 mm
/gate/source/mybeam27/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam27/gps/pos/type Plane
/gate/source/mybeam27/gps/pos/shape Rectangle
/gate/source/mybeam27/gps/direction 0 0 -1
 
/gate/source/addSource mybeam28 gps
/gate/source/mybeam28/gps/particle gamma
/gate/source/mybeam28/gps/ene/mono 28 keV
/gate/source/mybeam28/gps/pos/halfx 0.004 mm
/gate/source/mybeam28/gps/pos/halfy 0.004 mm
/gate/source/mybeam28/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam28/gps/pos/type Plane
/gate/source/mybeam28/gps/pos/shape Rectangle
/gate/source/mybeam28/gps/direction 0 0 -1
 
/gate/source/addSource mybeam29 gps
/gate/source/mybeam29/gps/particle gamma
/gate/source/mybeam29/gps/ene/mono 29 keV
/gate/source/mybeam29/gps/pos/halfx 0.004 mm
/gate/source/mybeam29/gps/pos/halfy 0.004 mm
/gate/source/mybeam29/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam29/gps/pos/type Plane
/gate/source/mybeam29/gps/pos/shape Rectangle
/gate/source/mybeam29/gps/direction 0 0 -1
 
/gate/source/addSource mybeam30 gps
/gate/source/mybeam30/gps/particle gamma
/gate/source/mybeam30/gps/ene/mono 30 keV
/gate/source/mybeam30/gps/pos/halfx 0.004 mm
/gate/source/mybeam30/gps/pos/halfy 0.004 mm
/gate/source/mybeam30/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam30/gps/pos/type Plane
/gate/source/mybeam30/gps/pos/shape Rectangle
/gate/source/mybeam30/gps/direction 0 0 -1
 
/gate/source/addSource mybeam31 gps
/gate/source/mybeam31/gps/particle gamma
/gate/source/mybeam31/gps/ene/mono 31 keV
/gate/source/mybeam31/gps/pos/halfx 0.004 mm
/gate/source/mybeam31/gps/pos/halfy 0.004 mm
/gate/source/mybeam31/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam31/gps/pos/type Plane
/gate/source/mybeam31/gps/pos/shape Rectangle
/gate/source/mybeam31/gps/direction 0 0 -1
 
/gate/source/addSource mybeam32 gps
/gate/source/mybeam32/gps/particle gamma
/gate/source/mybeam32/gps/ene/mono 32 keV
/gate/source/mybeam32/gps/pos/halfx 0.004 mm
/gate/source/mybeam32/gps/pos/halfy 0.004 mm
/gate/source/mybeam32/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam32/gps/pos/type Plane
/gate/source/mybeam32/gps/pos/shape Rectangle
/gate/source/mybeam32/gps/direction 0 0 -1
 
/gate/source/addSource mybeam33 gps
/gate/source/mybeam33/gps/particle gamma
/gate/source/mybeam33/gps/ene/mono 33 keV
/gate/source/mybeam33/gps/pos/halfx 0.004 mm
/gate/source/mybeam33/gps/pos/halfy 0.004 mm
/gate/source/mybeam33/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam33/gps/pos/type Plane
/gate/source/mybeam33/gps/pos/shape Rectangle
/gate/source/mybeam33/gps/direction 0 0 -1
 
/gate/source/addSource mybeam34 gps
/gate/source/mybeam34/gps/particle gamma
/gate/source/mybeam34/gps/ene/mono 34 keV
/gate/source/mybeam34/gps/pos/halfx 0.004 mm
/gate/source/mybeam34/gps/pos/halfy 0.004 mm
/gate/source/mybeam34/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam34/gps/pos/type Plane
/gate/source/mybeam34/gps/pos/shape Rectangle
/gate/source/mybeam34/gps/direction 0 0 -1
 
/gate/source/addSource mybeam35 gps
/gate/source/mybeam35/gps/particle gamma
/gate/source/mybeam35/gps/ene/mono 35 keV
/gate/source/mybeam35/gps/pos/halfx 0.004 mm
/gate/source/mybeam35/gps/pos/halfy 0.004 mm
/gate/source/mybeam35/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam35/gps/pos/type Plane
/gate/source/mybeam35/gps/pos/shape Rectangle
/gate/source/mybeam35/gps/direction 0 0 -1
 
/gate/source/addSource mybeam36 gps
/gate/source/mybeam36/gps/particle gamma
/gate/source/mybeam36/gps/ene/mono 36 keV
/gate/source/mybeam36/gps/pos/halfx 0.004 mm
/gate/source/mybeam36/gps/pos/halfy 0.004 mm
/gate/source/mybeam36/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam36/gps/pos/type Plane
/gate/source/mybeam36/gps/pos/shape Rectangle
/gate/source/mybeam36/gps/direction 0 0 -1
 
/gate/source/addSource mybeam37 gps
/gate/source/mybeam37/gps/particle gamma
/gate/source/mybeam37/gps/ene/mono 37 keV
/gate/source/mybeam37/gps/pos/halfx 0.004 mm
/gate/source/mybeam37/gps/pos/halfy 0.004 mm
/gate/source/mybeam37/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam37/gps/pos/type Plane
/gate/source/mybeam37/gps/pos/shape Rectangle
/gate/source/mybeam37/gps/direction 0 0 -1
 
/gate/source/addSource mybeam38 gps
/gate/source/mybeam38/gps/particle gamma
/gate/source/mybeam38/gps/ene/mono 38 keV
/gate/source/mybeam38/gps/pos/halfx 0.004 mm
/gate/source/mybeam38/gps/pos/halfy 0.004 mm
/gate/source/mybeam38/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam38/gps/pos/type Plane
/gate/source/mybeam38/gps/pos/shape Rectangle
/gate/source/mybeam38/gps/direction 0 0 -1
 
/gate/source/addSource mybeam39 gps
/gate/source/mybeam39/gps/particle gamma
/gate/source/mybeam39/gps/ene/mono 39 keV
/gate/source/mybeam39/gps/pos/halfx 0.004 mm
/gate/source/mybeam39/gps/pos/halfy 0.004 mm
/gate/source/mybeam39/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam39/gps/pos/type Plane
/gate/source/mybeam39/gps/pos/shape Rectangle
/gate/source/mybeam39/gps/direction 0 0 -1
 
/gate/source/addSource mybeam40 gps
/gate/source/mybeam40/gps/particle gamma
/gate/source/mybeam40/gps/ene/mono 40 keV
/gate/source/mybeam40/gps/pos/halfx 0.004 mm
/gate/source/mybeam40/gps/pos/halfy 0.004 mm
/gate/source/mybeam40/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam40/gps/pos/type Plane
/gate/source/mybeam40/gps/pos/shape Rectangle
/gate/source/mybeam40/gps/direction 0 0 -1
 
/gate/source/addSource mybeam41 gps
/gate/source/mybeam41/gps/particle gamma
/gate/source/mybeam41/gps/ene/mono 41 keV
/gate/source/mybeam41/gps/pos/halfx 0.004 mm
/gate/source/mybeam41/gps/pos/halfy 0.004 mm
/gate/source/mybeam41/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam41/gps/pos/type Plane
/gate/source/mybeam41/gps/pos/shape Rectangle
/gate/source/mybeam41/gps/direction 0 0 -1
 
/gate/source/addSource mybeam42 gps
/gate/source/mybeam42/gps/particle gamma
/gate/source/mybeam42/gps/ene/mono 42 keV
/gate/source/mybeam42/gps/pos/halfx 0.004 mm
/gate/source/mybeam42/gps/pos/halfy 0.004 mm
/gate/source/mybeam42/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam42/gps/pos/type Plane
/gate/source/mybeam42/gps/pos/shape Rectangle
/gate/source/mybeam42/gps/direction 0 0 -1
 
/gate/source/addSource mybeam43 gps
/gate/source/mybeam43/gps/particle gamma
/gate/source/mybeam43/gps/ene/mono 43 keV
/gate/source/mybeam43/gps/pos/halfx 0.004 mm
/gate/source/mybeam43/gps/pos/halfy 0.004 mm
/gate/source/mybeam43/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam43/gps/pos/type Plane
/gate/source/mybeam43/gps/pos/shape Rectangle
/gate/source/mybeam43/gps/direction 0 0 -1
 
/gate/source/addSource mybeam44 gps
/gate/source/mybeam44/gps/particle gamma
/gate/source/mybeam44/gps/ene/mono 44 keV
/gate/source/mybeam44/gps/pos/halfx 0.004 mm
/gate/source/mybeam44/gps/pos/halfy 0.004 mm
/gate/source/mybeam44/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam44/gps/pos/type Plane
/gate/source/mybeam44/gps/pos/shape Rectangle
/gate/source/mybeam44/gps/direction 0 0 -1
 
/gate/source/addSource mybeam45 gps
/gate/source/mybeam45/gps/particle gamma
/gate/source/mybeam45/gps/ene/mono 45 keV
/gate/source/mybeam45/gps/pos/halfx 0.004 mm
/gate/source/mybeam45/gps/pos/halfy 0.004 mm
/gate/source/mybeam45/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam45/gps/pos/type Plane
/gate/source/mybeam45/gps/pos/shape Rectangle
/gate/source/mybeam45/gps/direction 0 0 -1
 
/gate/source/addSource mybeam46 gps
/gate/source/mybeam46/gps/particle gamma
/gate/source/mybeam46/gps/ene/mono 46 keV
/gate/source/mybeam46/gps/pos/halfx 0.004 mm
/gate/source/mybeam46/gps/pos/halfy 0.004 mm
/gate/source/mybeam46/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam46/gps/pos/type Plane
/gate/source/mybeam46/gps/pos/shape Rectangle
/gate/source/mybeam46/gps/direction 0 0 -1
 
/gate/source/addSource mybeam47 gps
/gate/source/mybeam47/gps/particle gamma
/gate/source/mybeam47/gps/ene/mono 47 keV
/gate/source/mybeam47/gps/pos/halfx 0.004 mm
/gate/source/mybeam47/gps/pos/halfy 0.004 mm
/gate/source/mybeam47/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam47/gps/pos/type Plane
/gate/source/mybeam47/gps/pos/shape Rectangle
/gate/source/mybeam47/gps/direction 0 0 -1
 
/gate/source/addSource mybeam48 gps
/gate/source/mybeam48/gps/particle gamma
/gate/source/mybeam48/gps/ene/mono 48 keV
/gate/source/mybeam48/gps/pos/halfx 0.004 mm
/gate/source/mybeam48/gps/pos/halfy 0.004 mm
/gate/source/mybeam48/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam48/gps/pos/type Plane
/gate/source/mybeam48/gps/pos/shape Rectangle
/gate/source/mybeam48/gps/direction 0 0 -1
 
/gate/source/addSource mybeam49 gps
/gate/source/mybeam49/gps/particle gamma
/gate/source/mybeam49/gps/ene/mono 49 keV
/gate/source/mybeam49/gps/pos/halfx 0.004 mm
/gate/source/mybeam49/gps/pos/halfy 0.004 mm
/gate/source/mybeam49/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam49/gps/pos/type Plane
/gate/source/mybeam49/gps/pos/shape Rectangle
/gate/source/mybeam49/gps/direction 0 0 -1
 
/gate/source/addSource mybeam50 gps
/gate/source/mybeam50/gps/particle gamma
/gate/source/mybeam50/gps/ene/mono 50 keV
/gate/source/mybeam50/gps/pos/halfx 0.004 mm
/gate/source/mybeam50/gps/pos/halfy 0.004 mm
/gate/source/mybeam50/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam50/gps/pos/type Plane
/gate/source/mybeam50/gps/pos/shape Rectangle
/gate/source/mybeam50/gps/direction 0 0 -1
 
/gate/source/addSource mybeam51 gps
/gate/source/mybeam51/gps/particle gamma
/gate/source/mybeam51/gps/ene/mono 51 keV
/gate/source/mybeam51/gps/pos/halfx 0.004 mm
/gate/source/mybeam51/gps/pos/halfy 0.004 mm
/gate/source/mybeam51/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam51/gps/pos/type Plane
/gate/source/mybeam51/gps/pos/shape Rectangle
/gate/source/mybeam51/gps/direction 0 0 -1
 
/gate/source/addSource mybeam52 gps
/gate/source/mybeam52/gps/particle gamma
/gate/source/mybeam52/gps/ene/mono 52 keV
/gate/source/mybeam52/gps/pos/halfx 0.004 mm
/gate/source/mybeam52/gps/pos/halfy 0.004 mm
/gate/source/mybeam52/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam52/gps/pos/type Plane
/gate/source/mybeam52/gps/pos/shape Rectangle
/gate/source/mybeam52/gps/direction 0 0 -1
 
/gate/source/addSource mybeam53 gps
/gate/source/mybeam53/gps/particle gamma
/gate/source/mybeam53/gps/ene/mono 53 keV
/gate/source/mybeam53/gps/pos/halfx 0.004 mm
/gate/source/mybeam53/gps/pos/halfy 0.004 mm
/gate/source/mybeam53/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam53/gps/pos/type Plane
/gate/source/mybeam53/gps/pos/shape Rectangle
/gate/source/mybeam53/gps/direction 0 0 -1
 
/gate/source/addSource mybeam54 gps
/gate/source/mybeam54/gps/particle gamma
/gate/source/mybeam54/gps/ene/mono 54 keV
/gate/source/mybeam54/gps/pos/halfx 0.004 mm
/gate/source/mybeam54/gps/pos/halfy 0.004 mm
/gate/source/mybeam54/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam54/gps/pos/type Plane
/gate/source/mybeam54/gps/pos/shape Rectangle
/gate/source/mybeam54/gps/direction 0 0 -1
 
/gate/source/addSource mybeam55 gps
/gate/source/mybeam55/gps/particle gamma
/gate/source/mybeam55/gps/ene/mono 55 keV
/gate/source/mybeam55/gps/pos/halfx 0.004 mm
/gate/source/mybeam55/gps/pos/halfy 0.004 mm
/gate/source/mybeam55/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam55/gps/pos/type Plane
/gate/source/mybeam55/gps/pos/shape Rectangle
/gate/source/mybeam55/gps/direction 0 0 -1
 
/gate/source/addSource mybeam56 gps
/gate/source/mybeam56/gps/particle gamma
/gate/source/mybeam56/gps/ene/mono 56 keV
/gate/source/mybeam56/gps/pos/halfx 0.004 mm
/gate/source/mybeam56/gps/pos/halfy 0.004 mm
/gate/source/mybeam56/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam56/gps/pos/type Plane
/gate/source/mybeam56/gps/pos/shape Rectangle
/gate/source/mybeam56/gps/direction 0 0 -1
 
/gate/source/addSource mybeam57 gps
/gate/source/mybeam57/gps/particle gamma
/gate/source/mybeam57/gps/ene/mono 57 keV
/gate/source/mybeam57/gps/pos/halfx 0.004 mm
/gate/source/mybeam57/gps/pos/halfy 0.004 mm
/gate/source/mybeam57/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam57/gps/pos/type Plane
/gate/source/mybeam57/gps/pos/shape Rectangle
/gate/source/mybeam57/gps/direction 0 0 -1
 
/gate/source/addSource mybeam58 gps
/gate/source/mybeam58/gps/particle gamma
/gate/source/mybeam58/gps/ene/mono 58 keV
/gate/source/mybeam58/gps/pos/halfx 0.004 mm
/gate/source/mybeam58/gps/pos/halfy 0.004 mm
/gate/source/mybeam58/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam58/gps/pos/type Plane
/gate/source/mybeam58/gps/pos/shape Rectangle
/gate/source/mybeam58/gps/direction 0 0 -1
 
/gate/source/addSource mybeam59 gps
/gate/source/mybeam59/gps/particle gamma
/gate/source/mybeam59/gps/ene/mono 59 keV
/gate/source/mybeam59/gps/pos/halfx 0.004 mm
/gate/source/mybeam59/gps/pos/halfy 0.004 mm
/gate/source/mybeam59/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam59/gps/pos/type Plane
/gate/source/mybeam59/gps/pos/shape Rectangle
/gate/source/mybeam59/gps/direction 0 0 -1
 
/gate/source/addSource mybeam60 gps
/gate/source/mybeam60/gps/particle gamma
/gate/source/mybeam60/gps/ene/mono 60 keV
/gate/source/mybeam60/gps/pos/halfx 0.004 mm
/gate/source/mybeam60/gps/pos/halfy 0.004 mm
/gate/source/mybeam60/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam60/gps/pos/type Plane
/gate/source/mybeam60/gps/pos/shape Rectangle
/gate/source/mybeam60/gps/direction 0 0 -1
 
/gate/source/addSource mybeam61 gps
/gate/source/mybeam61/gps/particle gamma
/gate/source/mybeam61/gps/ene/mono 61 keV
/gate/source/mybeam61/gps/pos/halfx 0.004 mm
/gate/source/mybeam61/gps/pos/halfy 0.004 mm
/gate/source/mybeam61/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam61/gps/pos/type Plane
/gate/source/mybeam61/gps/pos/shape Rectangle
/gate/source/mybeam61/gps/direction 0 0 -1
 
/gate/source/addSource mybeam62 gps
/gate/source/mybeam62/gps/particle gamma
/gate/source/mybeam62/gps/ene/mono 62 keV
/gate/source/mybeam62/gps/pos/halfx 0.004 mm
/gate/source/mybeam62/gps/pos/halfy 0.004 mm
/gate/source/mybeam62/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam62/gps/pos/type Plane
/gate/source/mybeam62/gps/pos/shape Rectangle
/gate/source/mybeam62/gps/direction 0 0 -1
 
/gate/source/addSource mybeam63 gps
/gate/source/mybeam63/gps/particle gamma
/gate/source/mybeam63/gps/ene/mono 63 keV
/gate/source/mybeam63/gps/pos/halfx 0.004 mm
/gate/source/mybeam63/gps/pos/halfy 0.004 mm
/gate/source/mybeam63/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam63/gps/pos/type Plane
/gate/source/mybeam63/gps/pos/shape Rectangle
/gate/source/mybeam63/gps/direction 0 0 -1
 
/gate/source/addSource mybeam64 gps
/gate/source/mybeam64/gps/particle gamma
/gate/source/mybeam64/gps/ene/mono 64 keV
/gate/source/mybeam64/gps/pos/halfx 0.004 mm
/gate/source/mybeam64/gps/pos/halfy 0.004 mm
/gate/source/mybeam64/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam64/gps/pos/type Plane
/gate/source/mybeam64/gps/pos/shape Rectangle
/gate/source/mybeam64/gps/direction 0 0 -1
 
/gate/source/addSource mybeam65 gps
/gate/source/mybeam65/gps/particle gamma
/gate/source/mybeam65/gps/ene/mono 65 keV
/gate/source/mybeam65/gps/pos/halfx 0.004 mm
/gate/source/mybeam65/gps/pos/halfy 0.004 mm
/gate/source/mybeam65/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam65/gps/pos/type Plane
/gate/source/mybeam65/gps/pos/shape Rectangle
/gate/source/mybeam65/gps/direction 0 0 -1
 
/gate/source/addSource mybeam66 gps
/gate/source/mybeam66/gps/particle gamma
/gate/source/mybeam66/gps/ene/mono 66 keV
/gate/source/mybeam66/gps/pos/halfx 0.004 mm
/gate/source/mybeam66/gps/pos/halfy 0.004 mm
/gate/source/mybeam66/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam66/gps/pos/type Plane
/gate/source/mybeam66/gps/pos/shape Rectangle
/gate/source/mybeam66/gps/direction 0 0 -1
 
/gate/source/addSource mybeam67 gps
/gate/source/mybeam67/gps/particle gamma
/gate/source/mybeam67/gps/ene/mono 67 keV
/gate/source/mybeam67/gps/pos/halfx 0.004 mm
/gate/source/mybeam67/gps/pos/halfy 0.004 mm
/gate/source/mybeam67/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam67/gps/pos/type Plane
/gate/source/mybeam67/gps/pos/shape Rectangle
/gate/source/mybeam67/gps/direction 0 0 -1
 
/gate/source/addSource mybeam68 gps
/gate/source/mybeam68/gps/particle gamma
/gate/source/mybeam68/gps/ene/mono 68 keV
/gate/source/mybeam68/gps/pos/halfx 0.004 mm
/gate/source/mybeam68/gps/pos/halfy 0.004 mm
/gate/source/mybeam68/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam68/gps/pos/type Plane
/gate/source/mybeam68/gps/pos/shape Rectangle
/gate/source/mybeam68/gps/direction 0 0 -1
 
/gate/source/addSource mybeam69 gps
/gate/source/mybeam69/gps/particle gamma
/gate/source/mybeam69/gps/ene/mono 69 keV
/gate/source/mybeam69/gps/pos/halfx 0.004 mm
/gate/source/mybeam69/gps/pos/halfy 0.004 mm
/gate/source/mybeam69/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam69/gps/pos/type Plane
/gate/source/mybeam69/gps/pos/shape Rectangle
/gate/source/mybeam69/gps/direction 0 0 -1
 
/gate/source/addSource mybeam70 gps
/gate/source/mybeam70/gps/particle gamma
/gate/source/mybeam70/gps/ene/mono 70 keV
/gate/source/mybeam70/gps/pos/halfx 0.004 mm
/gate/source/mybeam70/gps/pos/halfy 0.004 mm
/gate/source/mybeam70/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam70/gps/pos/type Plane
/gate/source/mybeam70/gps/pos/shape Rectangle
/gate/source/mybeam70/gps/direction 0 0 -1
 
/gate/source/addSource mybeam71 gps
/gate/source/mybeam71/gps/particle gamma
/gate/source/mybeam71/gps/ene/mono 71 keV
/gate/source/mybeam71/gps/pos/halfx 0.004 mm
/gate/source/mybeam71/gps/pos/halfy 0.004 mm
/gate/source/mybeam71/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam71/gps/pos/type Plane
/gate/source/mybeam71/gps/pos/shape Rectangle
/gate/source/mybeam71/gps/direction 0 0 -1
 
/gate/source/addSource mybeam72 gps
/gate/source/mybeam72/gps/particle gamma
/gate/source/mybeam72/gps/ene/mono 72 keV
/gate/source/mybeam72/gps/pos/halfx 0.004 mm
/gate/source/mybeam72/gps/pos/halfy 0.004 mm
/gate/source/mybeam72/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam72/gps/pos/type Plane
/gate/source/mybeam72/gps/pos/shape Rectangle
/gate/source/mybeam72/gps/direction 0 0 -1
 
/gate/source/addSource mybeam73 gps
/gate/source/mybeam73/gps/particle gamma
/gate/source/mybeam73/gps/ene/mono 73 keV
/gate/source/mybeam73/gps/pos/halfx 0.004 mm
/gate/source/mybeam73/gps/pos/halfy 0.004 mm
/gate/source/mybeam73/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam73/gps/pos/type Plane
/gate/source/mybeam73/gps/pos/shape Rectangle
/gate/source/mybeam73/gps/direction 0 0 -1
 
/gate/source/addSource mybeam74 gps
/gate/source/mybeam74/gps/particle gamma
/gate/source/mybeam74/gps/ene/mono 74 keV
/gate/source/mybeam74/gps/pos/halfx 0.004 mm
/gate/source/mybeam74/gps/pos/halfy 0.004 mm
/gate/source/mybeam74/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam74/gps/pos/type Plane
/gate/source/mybeam74/gps/pos/shape Rectangle
/gate/source/mybeam74/gps/direction 0 0 -1
 
/gate/source/addSource mybeam75 gps
/gate/source/mybeam75/gps/particle gamma
/gate/source/mybeam75/gps/ene/mono 75 keV
/gate/source/mybeam75/gps/pos/halfx 0.004 mm
/gate/source/mybeam75/gps/pos/halfy 0.004 mm
/gate/source/mybeam75/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam75/gps/pos/type Plane
/gate/source/mybeam75/gps/pos/shape Rectangle
/gate/source/mybeam75/gps/direction 0 0 -1
 
/gate/source/addSource mybeam76 gps
/gate/source/mybeam76/gps/particle gamma
/gate/source/mybeam76/gps/ene/mono 76 keV
/gate/source/mybeam76/gps/pos/halfx 0.004 mm
/gate/source/mybeam76/gps/pos/halfy 0.004 mm
/gate/source/mybeam76/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam76/gps/pos/type Plane
/gate/source/mybeam76/gps/pos/shape Rectangle
/gate/source/mybeam76/gps/direction 0 0 -1
 
/gate/source/addSource mybeam77 gps
/gate/source/mybeam77/gps/particle gamma
/gate/source/mybeam77/gps/ene/mono 77 keV
/gate/source/mybeam77/gps/pos/halfx 0.004 mm
/gate/source/mybeam77/gps/pos/halfy 0.004 mm
/gate/source/mybeam77/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam77/gps/pos/type Plane
/gate/source/mybeam77/gps/pos/shape Rectangle
/gate/source/mybeam77/gps/direction 0 0 -1
 
/gate/source/addSource mybeam78 gps
/gate/source/mybeam78/gps/particle gamma
/gate/source/mybeam78/gps/ene/mono 78 keV
/gate/source/mybeam78/gps/pos/halfx 0.004 mm
/gate/source/mybeam78/gps/pos/halfy 0.004 mm
/gate/source/mybeam78/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam78/gps/pos/type Plane
/gate/source/mybeam78/gps/pos/shape Rectangle
/gate/source/mybeam78/gps/direction 0 0 -1
 
/gate/source/addSource mybeam79 gps
/gate/source/mybeam79/gps/particle gamma
/gate/source/mybeam79/gps/ene/mono 79 keV
/gate/source/mybeam79/gps/pos/halfx 0.004 mm
/gate/source/mybeam79/gps/pos/halfy 0.004 mm
/gate/source/mybeam79/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam79/gps/pos/type Plane
/gate/source/mybeam79/gps/pos/shape Rectangle
/gate/source/mybeam79/gps/direction 0 0 -1
 
/gate/source/addSource mybeam80 gps
/gate/source/mybeam80/gps/particle gamma
/gate/source/mybeam80/gps/ene/mono 80 keV
/gate/source/mybeam80/gps/pos/halfx 0.004 mm
/gate/source/mybeam80/gps/pos/halfy 0.004 mm
/gate/source/mybeam80/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam80/gps/pos/type Plane
/gate/source/mybeam80/gps/pos/shape Rectangle
/gate/source/mybeam80/gps/direction 0 0 -1
 
/gate/source/addSource mybeam81 gps
/gate/source/mybeam81/gps/particle gamma
/gate/source/mybeam81/gps/ene/mono 81 keV
/gate/source/mybeam81/gps/pos/halfx 0.004 mm
/gate/source/mybeam81/gps/pos/halfy 0.004 mm
/gate/source/mybeam81/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam81/gps/pos/type Plane
/gate/source/mybeam81/gps/pos/shape Rectangle
/gate/source/mybeam81/gps/direction 0 0 -1
 
/gate/source/addSource mybeam82 gps
/gate/source/mybeam82/gps/particle gamma
/gate/source/mybeam82/gps/ene/mono 82 keV
/gate/source/mybeam82/gps/pos/halfx 0.004 mm
/gate/source/mybeam82/gps/pos/halfy 0.004 mm
/gate/source/mybeam82/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam82/gps/pos/type Plane
/gate/source/mybeam82/gps/pos/shape Rectangle
/gate/source/mybeam82/gps/direction 0 0 -1
 
/gate/source/addSource mybeam83 gps
/gate/source/mybeam83/gps/particle gamma
/gate/source/mybeam83/gps/ene/mono 83 keV
/gate/source/mybeam83/gps/pos/halfx 0.004 mm
/gate/source/mybeam83/gps/pos/halfy 0.004 mm
/gate/source/mybeam83/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam83/gps/pos/type Plane
/gate/source/mybeam83/gps/pos/shape Rectangle
/gate/source/mybeam83/gps/direction 0 0 -1
 
/gate/source/addSource mybeam84 gps
/gate/source/mybeam84/gps/particle gamma
/gate/source/mybeam84/gps/ene/mono 84 keV
/gate/source/mybeam84/gps/pos/halfx 0.004 mm
/gate/source/mybeam84/gps/pos/halfy 0.004 mm
/gate/source/mybeam84/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam84/gps/pos/type Plane
/gate/source/mybeam84/gps/pos/shape Rectangle
/gate/source/mybeam84/gps/direction 0 0 -1
 
/gate/source/addSource mybeam85 gps
/gate/source/mybeam85/gps/particle gamma
/gate/source/mybeam85/gps/ene/mono 85 keV
/gate/source/mybeam85/gps/pos/halfx 0.004 mm
/gate/source/mybeam85/gps/pos/halfy 0.004 mm
/gate/source/mybeam85/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam85/gps/pos/type Plane
/gate/source/mybeam85/gps/pos/shape Rectangle
/gate/source/mybeam85/gps/direction 0 0 -1
 
/gate/source/addSource mybeam86 gps
/gate/source/mybeam86/gps/particle gamma
/gate/source/mybeam86/gps/ene/mono 86 keV
/gate/source/mybeam86/gps/pos/halfx 0.004 mm
/gate/source/mybeam86/gps/pos/halfy 0.004 mm
/gate/source/mybeam86/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam86/gps/pos/type Plane
/gate/source/mybeam86/gps/pos/shape Rectangle
/gate/source/mybeam86/gps/direction 0 0 -1
 
/gate/source/addSource mybeam87 gps
/gate/source/mybeam87/gps/particle gamma
/gate/source/mybeam87/gps/ene/mono 87 keV
/gate/source/mybeam87/gps/pos/halfx 0.004 mm
/gate/source/mybeam87/gps/pos/halfy 0.004 mm
/gate/source/mybeam87/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam87/gps/pos/type Plane
/gate/source/mybeam87/gps/pos/shape Rectangle
/gate/source/mybeam87/gps/direction 0 0 -1
 
/gate/source/addSource mybeam88 gps
/gate/source/mybeam88/gps/particle gamma
/gate/source/mybeam88/gps/ene/mono 88 keV
/gate/source/mybeam88/gps/pos/halfx 0.004 mm
/gate/source/mybeam88/gps/pos/halfy 0.004 mm
/gate/source/mybeam88/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam88/gps/pos/type Plane
/gate/source/mybeam88/gps/pos/shape Rectangle
/gate/source/mybeam88/gps/direction 0 0 -1
 
/gate/source/addSource mybeam89 gps
/gate/source/mybeam89/gps/particle gamma
/gate/source/mybeam89/gps/ene/mono 89 keV
/gate/source/mybeam89/gps/pos/halfx 0.004 mm
/gate/source/mybeam89/gps/pos/halfy 0.004 mm
/gate/source/mybeam89/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam89/gps/pos/type Plane
/gate/source/mybeam89/gps/pos/shape Rectangle
/gate/source/mybeam89/gps/direction 0 0 -1
 
/gate/source/addSource mybeam90 gps
/gate/source/mybeam90/gps/particle gamma
/gate/source/mybeam90/gps/ene/mono 90 keV
/gate/source/mybeam90/gps/pos/halfx 0.004 mm
/gate/source/mybeam90/gps/pos/halfy 0.004 mm
/gate/source/mybeam90/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam90/gps/pos/type Plane
/gate/source/mybeam90/gps/pos/shape Rectangle
/gate/source/mybeam90/gps/direction 0 0 -1
 
/gate/source/addSource mybeam91 gps
/gate/source/mybeam91/gps/particle gamma
/gate/source/mybeam91/gps/ene/mono 91 keV
/gate/source/mybeam91/gps/pos/halfx 0.004 mm
/gate/source/mybeam91/gps/pos/halfy 0.004 mm
/gate/source/mybeam91/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam91/gps/pos/type Plane
/gate/source/mybeam91/gps/pos/shape Rectangle
/gate/source/mybeam91/gps/direction 0 0 -1
 
/gate/source/addSource mybeam92 gps
/gate/source/mybeam92/gps/particle gamma
/gate/source/mybeam92/gps/ene/mono 92 keV
/gate/source/mybeam92/gps/pos/halfx 0.004 mm
/gate/source/mybeam92/gps/pos/halfy 0.004 mm
/gate/source/mybeam92/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam92/gps/pos/type Plane
/gate/source/mybeam92/gps/pos/shape Rectangle
/gate/source/mybeam92/gps/direction 0 0 -1
 
/gate/source/addSource mybeam93 gps
/gate/source/mybeam93/gps/particle gamma
/gate/source/mybeam93/gps/ene/mono 93 keV
/gate/source/mybeam93/gps/pos/halfx 0.004 mm
/gate/source/mybeam93/gps/pos/halfy 0.004 mm
/gate/source/mybeam93/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam93/gps/pos/type Plane
/gate/source/mybeam93/gps/pos/shape Rectangle
/gate/source/mybeam93/gps/direction 0 0 -1
 
/gate/source/addSource mybeam94 gps
/gate/source/mybeam94/gps/particle gamma
/gate/source/mybeam94/gps/ene/mono 94 keV
/gate/source/mybeam94/gps/pos/halfx 0.004 mm
/gate/source/mybeam94/gps/pos/halfy 0.004 mm
/gate/source/mybeam94/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam94/gps/pos/type Plane
/gate/source/mybeam94/gps/pos/shape Rectangle
/gate/source/mybeam94/gps/direction 0 0 -1
 
/gate/source/addSource mybeam95 gps
/gate/source/mybeam95/gps/particle gamma
/gate/source/mybeam95/gps/ene/mono 95 keV
/gate/source/mybeam95/gps/pos/halfx 0.004 mm
/gate/source/mybeam95/gps/pos/halfy 0.004 mm
/gate/source/mybeam95/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam95/gps/pos/type Plane
/gate/source/mybeam95/gps/pos/shape Rectangle
/gate/source/mybeam95/gps/direction 0 0 -1
 
/gate/source/addSource mybeam96 gps
/gate/source/mybeam96/gps/particle gamma
/gate/source/mybeam96/gps/ene/mono 96 keV
/gate/source/mybeam96/gps/pos/halfx 0.004 mm
/gate/source/mybeam96/gps/pos/halfy 0.004 mm
/gate/source/mybeam96/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam96/gps/pos/type Plane
/gate/source/mybeam96/gps/pos/shape Rectangle
/gate/source/mybeam96/gps/direction 0 0 -1
 
/gate/source/addSource mybeam97 gps
/gate/source/mybeam97/gps/particle gamma
/gate/source/mybeam97/gps/ene/mono 97 keV
/gate/source/mybeam97/gps/pos/halfx 0.004 mm
/gate/source/mybeam97/gps/pos/halfy 0.004 mm
/gate/source/mybeam97/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam97/gps/pos/type Plane
/gate/source/mybeam97/gps/pos/shape Rectangle
/gate/source/mybeam97/gps/direction 0 0 -1
 
/gate/source/addSource mybeam98 gps
/gate/source/mybeam98/gps/particle gamma
/gate/source/mybeam98/gps/ene/mono 98 keV
/gate/source/mybeam98/gps/pos/halfx 0.004 mm
/gate/source/mybeam98/gps/pos/halfy 0.004 mm
/gate/source/mybeam98/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam98/gps/pos/type Plane
/gate/source/mybeam98/gps/pos/shape Rectangle
/gate/source/mybeam98/gps/direction 0 0 -1
 
/gate/source/addSource mybeam99 gps
/gate/source/mybeam99/gps/particle gamma
/gate/source/mybeam99/gps/ene/mono 99 keV
/gate/source/mybeam99/gps/pos/halfx 0.004 mm
/gate/source/mybeam99/gps/pos/halfy 0.004 mm
/gate/source/mybeam99/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam99/gps/pos/type Plane
/gate/source/mybeam99/gps/pos/shape Rectangle
/gate/source/mybeam99/gps/direction 0 0 -1
 
/gate/source/addSource mybeam100 gps
/gate/source/mybeam100/gps/particle gamma
/gate/source/mybeam100/gps/ene/mono 100 keV
/gate/source/mybeam100/gps/pos/halfx 0.004 mm
/gate/source/mybeam100/gps/pos/halfy 0.004 mm
/gate/source/mybeam100/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam100/gps/pos/type Plane
/gate/source/mybeam100/gps/pos/shape Rectangle
/gate/source/mybeam100/gps/direction 0 0 -1
 
/gate/source/addSource mybeam101 gps
/gate/source/mybeam101/gps/particle gamma
/gate/source/mybeam101/gps/ene/mono 101 keV
/gate/source/mybeam101/gps/pos/halfx 0.004 mm
/gate/source/mybeam101/gps/pos/halfy 0.004 mm
/gate/source/mybeam101/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam101/gps/pos/type Plane
/gate/source/mybeam101/gps/pos/shape Rectangle
/gate/source/mybeam101/gps/direction 0 0 -1
 
/gate/source/addSource mybeam102 gps
/gate/source/mybeam102/gps/particle gamma
/gate/source/mybeam102/gps/ene/mono 102 keV
/gate/source/mybeam102/gps/pos/halfx 0.004 mm
/gate/source/mybeam102/gps/pos/halfy 0.004 mm
/gate/source/mybeam102/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam102/gps/pos/type Plane
/gate/source/mybeam102/gps/pos/shape Rectangle
/gate/source/mybeam102/gps/direction 0 0 -1
 
/gate/source/addSource mybeam103 gps
/gate/source/mybeam103/gps/particle gamma
/gate/source/mybeam103/gps/ene/mono 103 keV
/gate/source/mybeam103/gps/pos/halfx 0.004 mm
/gate/source/mybeam103/gps/pos/halfy 0.004 mm
/gate/source/mybeam103/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam103/gps/pos/type Plane
/gate/source/mybeam103/gps/pos/shape Rectangle
/gate/source/mybeam103/gps/direction 0 0 -1
 
/gate/source/addSource mybeam104 gps
/gate/source/mybeam104/gps/particle gamma
/gate/source/mybeam104/gps/ene/mono 104 keV
/gate/source/mybeam104/gps/pos/halfx 0.004 mm
/gate/source/mybeam104/gps/pos/halfy 0.004 mm
/gate/source/mybeam104/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam104/gps/pos/type Plane
/gate/source/mybeam104/gps/pos/shape Rectangle
/gate/source/mybeam104/gps/direction 0 0 -1
 
/gate/source/addSource mybeam105 gps
/gate/source/mybeam105/gps/particle gamma
/gate/source/mybeam105/gps/ene/mono 105 keV
/gate/source/mybeam105/gps/pos/halfx 0.004 mm
/gate/source/mybeam105/gps/pos/halfy 0.004 mm
/gate/source/mybeam105/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam105/gps/pos/type Plane
/gate/source/mybeam105/gps/pos/shape Rectangle
/gate/source/mybeam105/gps/direction 0 0 -1
 
/gate/source/addSource mybeam106 gps
/gate/source/mybeam106/gps/particle gamma
/gate/source/mybeam106/gps/ene/mono 106 keV
/gate/source/mybeam106/gps/pos/halfx 0.004 mm
/gate/source/mybeam106/gps/pos/halfy 0.004 mm
/gate/source/mybeam106/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam106/gps/pos/type Plane
/gate/source/mybeam106/gps/pos/shape Rectangle
/gate/source/mybeam106/gps/direction 0 0 -1
 
/gate/source/addSource mybeam107 gps
/gate/source/mybeam107/gps/particle gamma
/gate/source/mybeam107/gps/ene/mono 107 keV
/gate/source/mybeam107/gps/pos/halfx 0.004 mm
/gate/source/mybeam107/gps/pos/halfy 0.004 mm
/gate/source/mybeam107/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam107/gps/pos/type Plane
/gate/source/mybeam107/gps/pos/shape Rectangle
/gate/source/mybeam107/gps/direction 0 0 -1
 
/gate/source/addSource mybeam108 gps
/gate/source/mybeam108/gps/particle gamma
/gate/source/mybeam108/gps/ene/mono 108 keV
/gate/source/mybeam108/gps/pos/halfx 0.004 mm
/gate/source/mybeam108/gps/pos/halfy 0.004 mm
/gate/source/mybeam108/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam108/gps/pos/type Plane
/gate/source/mybeam108/gps/pos/shape Rectangle
/gate/source/mybeam108/gps/direction 0 0 -1
 
/gate/source/addSource mybeam109 gps
/gate/source/mybeam109/gps/particle gamma
/gate/source/mybeam109/gps/ene/mono 109 keV
/gate/source/mybeam109/gps/pos/halfx 0.004 mm
/gate/source/mybeam109/gps/pos/halfy 0.004 mm
/gate/source/mybeam109/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam109/gps/pos/type Plane
/gate/source/mybeam109/gps/pos/shape Rectangle
/gate/source/mybeam109/gps/direction 0 0 -1
 
/gate/source/addSource mybeam110 gps
/gate/source/mybeam110/gps/particle gamma
/gate/source/mybeam110/gps/ene/mono 110 keV
/gate/source/mybeam110/gps/pos/halfx 0.004 mm
/gate/source/mybeam110/gps/pos/halfy 0.004 mm
/gate/source/mybeam110/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam110/gps/pos/type Plane
/gate/source/mybeam110/gps/pos/shape Rectangle
/gate/source/mybeam110/gps/direction 0 0 -1
 
/gate/source/addSource mybeam111 gps
/gate/source/mybeam111/gps/particle gamma
/gate/source/mybeam111/gps/ene/mono 111 keV
/gate/source/mybeam111/gps/pos/halfx 0.004 mm
/gate/source/mybeam111/gps/pos/halfy 0.004 mm
/gate/source/mybeam111/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam111/gps/pos/type Plane
/gate/source/mybeam111/gps/pos/shape Rectangle
/gate/source/mybeam111/gps/direction 0 0 -1
 
/gate/source/addSource mybeam112 gps
/gate/source/mybeam112/gps/particle gamma
/gate/source/mybeam112/gps/ene/mono 112 keV
/gate/source/mybeam112/gps/pos/halfx 0.004 mm
/gate/source/mybeam112/gps/pos/halfy 0.004 mm
/gate/source/mybeam112/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam112/gps/pos/type Plane
/gate/source/mybeam112/gps/pos/shape Rectangle
/gate/source/mybeam112/gps/direction 0 0 -1
 
/gate/source/addSource mybeam113 gps
/gate/source/mybeam113/gps/particle gamma
/gate/source/mybeam113/gps/ene/mono 113 keV
/gate/source/mybeam113/gps/pos/halfx 0.004 mm
/gate/source/mybeam113/gps/pos/halfy 0.004 mm
/gate/source/mybeam113/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam113/gps/pos/type Plane
/gate/source/mybeam113/gps/pos/shape Rectangle
/gate/source/mybeam113/gps/direction 0 0 -1
 
/gate/source/addSource mybeam114 gps
/gate/source/mybeam114/gps/particle gamma
/gate/source/mybeam114/gps/ene/mono 114 keV
/gate/source/mybeam114/gps/pos/halfx 0.004 mm
/gate/source/mybeam114/gps/pos/halfy 0.004 mm
/gate/source/mybeam114/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam114/gps/pos/type Plane
/gate/source/mybeam114/gps/pos/shape Rectangle
/gate/source/mybeam114/gps/direction 0 0 -1
 
/gate/source/addSource mybeam115 gps
/gate/source/mybeam115/gps/particle gamma
/gate/source/mybeam115/gps/ene/mono 115 keV
/gate/source/mybeam115/gps/pos/halfx 0.004 mm
/gate/source/mybeam115/gps/pos/halfy 0.004 mm
/gate/source/mybeam115/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam115/gps/pos/type Plane
/gate/source/mybeam115/gps/pos/shape Rectangle
/gate/source/mybeam115/gps/direction 0 0 -1
 
/gate/source/addSource mybeam116 gps
/gate/source/mybeam116/gps/particle gamma
/gate/source/mybeam116/gps/ene/mono 116 keV
/gate/source/mybeam116/gps/pos/halfx 0.004 mm
/gate/source/mybeam116/gps/pos/halfy 0.004 mm
/gate/source/mybeam116/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam116/gps/pos/type Plane
/gate/source/mybeam116/gps/pos/shape Rectangle
/gate/source/mybeam116/gps/direction 0 0 -1
 
/gate/source/addSource mybeam117 gps
/gate/source/mybeam117/gps/particle gamma
/gate/source/mybeam117/gps/ene/mono 117 keV
/gate/source/mybeam117/gps/pos/halfx 0.004 mm
/gate/source/mybeam117/gps/pos/halfy 0.004 mm
/gate/source/mybeam117/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam117/gps/pos/type Plane
/gate/source/mybeam117/gps/pos/shape Rectangle
/gate/source/mybeam117/gps/direction 0 0 -1
 
/gate/source/addSource mybeam118 gps
/gate/source/mybeam118/gps/particle gamma
/gate/source/mybeam118/gps/ene/mono 118 keV
/gate/source/mybeam118/gps/pos/halfx 0.004 mm
/gate/source/mybeam118/gps/pos/halfy 0.004 mm
/gate/source/mybeam118/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam118/gps/pos/type Plane
/gate/source/mybeam118/gps/pos/shape Rectangle
/gate/source/mybeam118/gps/direction 0 0 -1
 
/gate/source/addSource mybeam119 gps
/gate/source/mybeam119/gps/particle gamma
/gate/source/mybeam119/gps/ene/mono 119 keV
/gate/source/mybeam119/gps/pos/halfx 0.004 mm
/gate/source/mybeam119/gps/pos/halfy 0.004 mm
/gate/source/mybeam119/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam119/gps/pos/type Plane
/gate/source/mybeam119/gps/pos/shape Rectangle
/gate/source/mybeam119/gps/direction 0 0 -1
 
/gate/source/addSource mybeam120 gps
/gate/source/mybeam120/gps/particle gamma
/gate/source/mybeam120/gps/ene/mono 120 keV
/gate/source/mybeam120/gps/pos/halfx 0.004 mm
/gate/source/mybeam120/gps/pos/halfy 0.004 mm
/gate/source/mybeam120/gps/pos/centre 0 0 50.5 mm
/gate/source/mybeam120/gps/pos/type Plane
/gate/source/mybeam120/gps/pos/shape Rectangle
/gate/source/mybeam120/gps/direction 0 0 -1
 
