#/gate/source/addSource mybeam gps
/gate/source/mybeam/gps/particle gamma
/gate/source/mybeam/gps/ene/type User
/gate/source/mybeam/gps/hist/type energy

/gate/source/mybeam/gps/hist/point 0.012  1.606138
/gate/source/mybeam/gps/hist/point 0.013  33.67743
/gate/source/mybeam/gps/hist/point 0.014  352.8433
/gate/source/mybeam/gps/hist/point 0.015  2102.184
/gate/source/mybeam/gps/hist/point 0.016  8557.777
/gate/source/mybeam/gps/hist/point 0.017  25625.63
/gate/source/mybeam/gps/hist/point 0.018  61026.59
/gate/source/mybeam/gps/hist/point 0.019  123960.9
/gate/source/mybeam/gps/hist/point 0.020  221160.9
/gate/source/mybeam/gps/hist/point 0.021  356381.1
/gate/source/mybeam/gps/hist/point 0.022  529286.7
/gate/source/mybeam/gps/hist/point 0.023  736403.7
/gate/source/mybeam/gps/hist/point 0.024  971518.9
/gate/source/mybeam/gps/hist/point 0.025  1.214957e+6
/gate/source/mybeam/gps/hist/point 0.026  1.484348e+6
/gate/source/mybeam/gps/hist/point 0.027  1.753540e+6
/gate/source/mybeam/gps/hist/point 0.028  2.022188e+6
/gate/source/mybeam/gps/hist/point 0.029  2.281571e+6
/gate/source/mybeam/gps/hist/point 0.030  2.514144e+6
/gate/source/mybeam/gps/hist/point 0.031  2.738527e+6
/gate/source/mybeam/gps/hist/point 0.032  2.944665e+6
/gate/source/mybeam/gps/hist/point 0.033  3.130611e+6
/gate/source/mybeam/gps/hist/point 0.034  3.298258e+6
/gate/source/mybeam/gps/hist/point 0.035  3.436582e+6
/gate/source/mybeam/gps/hist/point 0.036  3.549040e+6
/gate/source/mybeam/gps/hist/point 0.037  3.649410e+6
/gate/source/mybeam/gps/hist/point 0.038  3.730694e+6
/gate/source/mybeam/gps/hist/point 0.039  3.789387e+6
/gate/source/mybeam/gps/hist/point 0.040  3.832752e+6
/gate/source/mybeam/gps/hist/point 0.041  3.865996e+6
/gate/source/mybeam/gps/hist/point 0.042  3.880175e+6
/gate/source/mybeam/gps/hist/point 0.043  3.883500e+6
/gate/source/mybeam/gps/hist/point 0.044  3.877606e+6
/gate/source/mybeam/gps/hist/point 0.045  3.859606e+6
/gate/source/mybeam/gps/hist/point 0.046  3.837198e+6
/gate/source/mybeam/gps/hist/point 0.047  3.803806e+6
/gate/source/mybeam/gps/hist/point 0.048  3.763250e+6
/gate/source/mybeam/gps/hist/point 0.049  3.720405e+6
/gate/source/mybeam/gps/hist/point 0.050  3.669896e+6
/gate/source/mybeam/gps/hist/point 0.051  3.616308e+6
/gate/source/mybeam/gps/hist/point 0.052  3.557881e+6
/gate/source/mybeam/gps/hist/point 0.053  3.500617e+6
/gate/source/mybeam/gps/hist/point 0.054  3.438647e+6
/gate/source/mybeam/gps/hist/point 0.055  3.374860e+6
/gate/source/mybeam/gps/hist/point 0.056  3.307962e+6
/gate/source/mybeam/gps/hist/point 0.057  3.240691e+6
/gate/source/mybeam/gps/hist/point 0.058  1.072517e+7
/gate/source/mybeam/gps/hist/point 0.059  1.629836e+7
/gate/source/mybeam/gps/hist/point 0.060  3.038592e+6
/gate/source/mybeam/gps/hist/point 0.061  2.969403e+6
/gate/source/mybeam/gps/hist/point 0.062  2.902221e+6
/gate/source/mybeam/gps/hist/point 0.063  2.833106e+6
/gate/source/mybeam/gps/hist/point 0.064  2.767596e+6
/gate/source/mybeam/gps/hist/point 0.065  2.698853e+6
/gate/source/mybeam/gps/hist/point 0.066  2.633575e+6
/gate/source/mybeam/gps/hist/point 0.067  6.976168e+6
/gate/source/mybeam/gps/hist/point 0.068  2.501697e+6
/gate/source/mybeam/gps/hist/point 0.069  3.589790e+6
/gate/source/mybeam/gps/hist/point 0.070  1.864149e+6
/gate/source/mybeam/gps/hist/point 0.071  1.831070e+6
/gate/source/mybeam/gps/hist/point 0.072  1.795990e+6
/gate/source/mybeam/gps/hist/point 0.073  1.764715e+6
/gate/source/mybeam/gps/hist/point 0.074  1.730748e+6
/gate/source/mybeam/gps/hist/point 0.075  1.696966e+6
/gate/source/mybeam/gps/hist/point 0.076  1.660770e+6
/gate/source/mybeam/gps/hist/point 0.077  1.626258e+6
/gate/source/mybeam/gps/hist/point 0.078  1.591552e+6
/gate/source/mybeam/gps/hist/point 0.079  1.555117e+6
/gate/source/mybeam/gps/hist/point 0.080  1.519064e+6
/gate/source/mybeam/gps/hist/point 0.081  1.482827e+6
/gate/source/mybeam/gps/hist/point 0.082  1.448267e+6
/gate/source/mybeam/gps/hist/point 0.083  1.411818e+6
/gate/source/mybeam/gps/hist/point 0.084  1.375425e+6
/gate/source/mybeam/gps/hist/point 0.085  1.338743e+6
/gate/source/mybeam/gps/hist/point 0.086  1.302876e+6
/gate/source/mybeam/gps/hist/point 0.087  1.267544e+6
/gate/source/mybeam/gps/hist/point 0.088  1.231810e+6
/gate/source/mybeam/gps/hist/point 0.089  1.195798e+6
/gate/source/mybeam/gps/hist/point 0.090  1.160321e+6
/gate/source/mybeam/gps/hist/point 0.091  1.124550e+6
/gate/source/mybeam/gps/hist/point 0.092  1.089720e+6
/gate/source/mybeam/gps/hist/point 0.093  1.054096e+6
/gate/source/mybeam/gps/hist/point 0.094  1.019039e+6
/gate/source/mybeam/gps/hist/point 0.095  984581.7
/gate/source/mybeam/gps/hist/point 0.096  949999.6
/gate/source/mybeam/gps/hist/point 0.097  915005
/gate/source/mybeam/gps/hist/point 0.098  880579.3
/gate/source/mybeam/gps/hist/point 0.099  846221.4
/gate/source/mybeam/gps/hist/point 0.100  812490.5
/gate/source/mybeam/gps/hist/point 0.101  778757.9
/gate/source/mybeam/gps/hist/point 0.102  744250.8
/gate/source/mybeam/gps/hist/point 0.103  710448.4
/gate/source/mybeam/gps/hist/point 0.104  676313.6
/gate/source/mybeam/gps/hist/point 0.105  642301.7
/gate/source/mybeam/gps/hist/point 0.106  608559
/gate/source/mybeam/gps/hist/point 0.107  573989.6
/gate/source/mybeam/gps/hist/point 0.108  539930.9
/gate/source/mybeam/gps/hist/point 0.109  504924.3
/gate/source/mybeam/gps/hist/point 0.110  470553.2
/gate/source/mybeam/gps/hist/point 0.111  435560
/gate/source/mybeam/gps/hist/point 0.112  400002.7
/gate/source/mybeam/gps/hist/point 0.113  364590.4
/gate/source/mybeam/gps/hist/point 0.114  324750.3
/gate/source/mybeam/gps/hist/point 0.115  286399.4
/gate/source/mybeam/gps/hist/point 0.116  247883.6
/gate/source/mybeam/gps/hist/point 0.117  209744.3
/gate/source/mybeam/gps/hist/point 0.118  155676.2
/gate/source/mybeam/gps/hist/point 0.119  76654.8
/gate/source/mybeam/gps/hist/point 0.120  0

/gate/source/mybeam/gps/pos/halfx 8 mm
/gate/source/mybeam/gps/pos/halfy 8 mm
/gate/source/mybeam/gps/pos/rot1 1 0 0
/gate/source/mybeam/gps/pos/rot2 0 1 0
/gate/source/mybeam/gps/pos/centre 0 0 3000.0 mm
#/gate/source/mybeam/gps/pos/centre 0 0 1060 mm
#/gate/source/mybeam/gps/pos/type Point
/gate/source/mybeam/gps/pos/type Plane
/gate/source/mybeam/gps/pos/shape Rectangle
/gate/source/mybeam/gps/ang/type focused
/gate/source/mybeam/gps/ang/focuspoint 0 0 2819.05 mm

