#/gate/source/addSource mybeam gps
/gate/source/mybeam/gps/particle gamma
/gate/source/mybeam/gps/ene/type User
/gate/source/mybeam/gps/hist/type energy

/gate/source/mybeam/gps/hist/point	0.01		0.0001145
/gate/source/mybeam/gps/hist/point	0.011		0.0265377
/gate/source/mybeam/gps/hist/point	0.012		1.696291
/gate/source/mybeam/gps/hist/point	0.013		35.60969
/gate/source/mybeam/gps/hist/point	0.014		375.0344
/gate/source/mybeam/gps/hist/point	0.015		2238.035
/gate/source/mybeam/gps/hist/point	0.016		9102.615
/gate/source/mybeam/gps/hist/point	0.017		27158.55
/gate/source/mybeam/gps/hist/point	0.018		64342.55
/gate/source/mybeam/gps/hist/point	0.019		129801.1
/gate/source/mybeam/gps/hist/point	0.02		229590.1
/gate/source/mybeam/gps/hist/point	0.021		366500.7
/gate/source/mybeam/gps/hist/point	0.022		538473.5
/gate/source/mybeam/gps/hist/point	0.023		741173.5
/gate/source/mybeam/gps/hist/point	0.024		966712.6
/gate/source/mybeam/gps/hist/point	0.025		1.195013e+6
/gate/source/mybeam/gps/hist/point	0.026		1.443049e+6
/gate/source/mybeam/gps/hist/point	0.027		1.684881e+6
/gate/source/mybeam/gps/hist/point	0.028		1.921955e+6
/gate/source/mybeam/gps/hist/point	0.029		2.143059e+6
/gate/source/mybeam/gps/hist/point	0.03		2.336596e+6
/gate/source/mybeam/gps/hist/point	0.031		2.518237e+6
/gate/source/mybeam/gps/hist/point	0.032		2.680914e+6
/gate/source/mybeam/gps/hist/point	0.033		2.822495e+6
/gate/source/mybeam/gps/hist/point	0.034		2.943945e+6
/gate/source/mybeam/gps/hist/point	0.035		3.040030e+6
/gate/source/mybeam/gps/hist/point	0.036		3.113462e+6
/gate/source/mybeam/gps/hist/point	0.037		3.173910e+6
/gate/source/mybeam/gps/hist/point	0.038		3.218119e+6
/gate/source/mybeam/gps/hist/point	0.039		3.242518e+6
/gate/source/mybeam/gps/hist/point	0.04		3.255800e+6
/gate/source/mybeam/gps/hist/point	0.041		3.258236e+6
/gate/source/mybeam/gps/hist/point	0.042		3.247407e+6
/gate/source/mybeam/gps/hist/point	0.043		3.227609e+6
/gate/source/mybeam/gps/hist/point	0.044		3.200591e+6
/gate/source/mybeam/gps/hist/point	0.045		3.164947e+6
/gate/source/mybeam/gps/hist/point	0.046		3.125593e+6
/gate/source/mybeam/gps/hist/point	0.047		3.079214e+6
/gate/source/mybeam/gps/hist/point	0.048		3.026521e+6
/gate/source/mybeam/gps/hist/point	0.049		2.973909e+6
/gate/source/mybeam/gps/hist/point	0.05		2.915587e+6
/gate/source/mybeam/gps/hist/point	0.051		2.854778e+6
/gate/source/mybeam/gps/hist/point	0.052		2.791778e+6
/gate/source/mybeam/gps/hist/point	0.053		2.729030e+6
/gate/source/mybeam/gps/hist/point	0.054		2.664807e+6
/gate/source/mybeam/gps/hist/point	0.055		2.598725e+6
/gate/source/mybeam/gps/hist/point	0.056		2.531792e+6
/gate/source/mybeam/gps/hist/point	0.057		2.464047e+6
/gate/source/mybeam/gps/hist/point	0.058		5.779181e+6
/gate/source/mybeam/gps/hist/point	0.059		8.238463e+6
/gate/source/mybeam/gps/hist/point	0.06		2.264826e+6
/gate/source/mybeam/gps/hist/point	0.061		2.198054e+6
/gate/source/mybeam/gps/hist/point	0.062		2.133401e+6
/gate/source/mybeam/gps/hist/point	0.063		2.067139e+6
/gate/source/mybeam/gps/hist/point	0.064		2.004628e+6
/gate/source/mybeam/gps/hist/point	0.065		1.939120e+6
/gate/source/mybeam/gps/hist/point	0.066		1.877691e+6
/gate/source/mybeam/gps/hist/point	0.067		3.789177e+6
/gate/source/mybeam/gps/hist/point	0.068		1.753662e+6
/gate/source/mybeam/gps/hist/point	0.069		2.209302e+6
/gate/source/mybeam/gps/hist/point	0.07		1.380973e+6
/gate/source/mybeam/gps/hist/point	0.071		1.341001e+6
/gate/source/mybeam/gps/hist/point	0.072		1.300689e+6
/gate/source/mybeam/gps/hist/point	0.073		1.261699e+6
/gate/source/mybeam/gps/hist/point	0.074		1.221875e+6
/gate/source/mybeam/gps/hist/point	0.075		1.181677e+6
/gate/source/mybeam/gps/hist/point	0.076		1.140778e+6
/gate/source/mybeam/gps/hist/point	0.077		1.100247e+6
/gate/source/mybeam/gps/hist/point	0.078		1.060656e+6
/gate/source/mybeam/gps/hist/point	0.079		1.019259e+6
/gate/source/mybeam/gps/hist/point	0.08		978748
/gate/source/mybeam/gps/hist/point	0.081		937567.9
/gate/source/mybeam/gps/hist/point	0.082		897965.4
/gate/source/mybeam/gps/hist/point	0.083		856675.9
/gate/source/mybeam/gps/hist/point	0.084		815536.8
/gate/source/mybeam/gps/hist/point	0.085		774093.3
/gate/source/mybeam/gps/hist/point	0.086		733558.1
/gate/source/mybeam/gps/hist/point	0.087		691985.6
/gate/source/mybeam/gps/hist/point	0.088		651150.7
/gate/source/mybeam/gps/hist/point	0.089		608394.8
/gate/source/mybeam/gps/hist/point	0.09		567141
/gate/source/mybeam/gps/hist/point	0.091		523615.4
/gate/source/mybeam/gps/hist/point	0.092		481542.6
/gate/source/mybeam/gps/hist/point	0.093		436743.2
/gate/source/mybeam/gps/hist/point	0.094		393052.8
/gate/source/mybeam/gps/hist/point	0.095		343935.1
/gate/source/mybeam/gps/hist/point	0.096		295697
/gate/source/mybeam/gps/hist/point	0.097		246801.6
/gate/source/mybeam/gps/hist/point	0.098		199194.7
/gate/source/mybeam/gps/hist/point	0.099		98203.33
/gate/source/mybeam/gps/hist/point	0.1		0

/gate/source/mybeam/gps/pos/halfx 2 mm
/gate/source/mybeam/gps/pos/halfy 2 mm
/gate/source/mybeam/gps/pos/rot1 1 0 0
/gate/source/mybeam/gps/pos/rot2 0 1 0
/gate/source/mybeam/gps/pos/centre 0 0 -2850.0 mm
/gate/source/mybeam/gps/pos/type Plane
/gate/source/mybeam/gps/pos/shape Rectangle
/gate/source/mybeam/gps/ang/type focused
/gate/source/mybeam/gps/ang/focuspoint 0 0 -2820.0 mm
