#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# Example of CT imaging.

#-------------------oooooOOOOO00000OOOOOooooo---------------------#

#=====================================================
# VERBOSE and VISUALISATION 
#=====================================================

#/control/execute mac/verbose.mac
#/control/execute mac/visu1.mac

#=====================================================
# GEOMETRY
#=====================================================

# World
/gate/geometry/setMaterialDatabase data/GateMaterials.db
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    6 m
/gate/world/geometry/setYLength    6 m
/gate/world/geometry/setZLength    6 m

# Insert phantom
#/control/execute mac/catphan.mac
/control/execute mac/patient_head.mac

# Detection plane
/gate/world/daughters/name                    DetectorPlane
/gate/world/daughters/insert                  box
/gate/DetectorPlane/geometry/setZLength       1 nm
/gate/DetectorPlane/geometry/setYLength       447.97 mm
/gate/DetectorPlane/geometry/setXLength       447.97 mm
/gate/DetectorPlane/placement/setTranslation  0 0 560.0 mm
#/gate/DetectorPlane/placement/setRotationAxis 0 1 0
/gate/DetectorPlane/setMaterial               Air
/gate/DetectorPlane/vis/setVisible            1
/gate/DetectorPlane/vis/setColor              yellow



#=====================================================
# PHYSIC
#=====================================================
/control/execute mac/Physicslist_Livermore_no_e.mac


# Be sure there is no e- 
/gate/physics/Gamma/SetCutInRegion      world 10 nm
/gate/physics/Electron/SetCutInRegion   world 100 cm
/gate/physics/Positron/SetCutInRegion   world 10 m

/gate/physics/displayCuts

#=====================================================
# DETECTORS
#=====================================================

# -----------------------------------------------------
# timing
/gate/actor/addActor  TimeActor statt
/gate/actor/statt/enableDetailedStats false
/gate/actor/statt/save output/time.txt


# -----------------------------------------------------
# Fixed ForcedDetection Actor (ffda)
/gate/actor/addActor                       FixedForcedDetectionActor ffda
/gate/actor/ffda/attachTo                  world
/gate/actor/ffda/setDetector               DetectorPlane
/gate/actor/ffda/setDetectorResolution     224 224
/gate/actor/ffda/responseDetectorFilename  data/imagXresponseDetector.txt
/gate/actor/ffda/geometryFilename          output/imag_geometry_Hy.xml
/gate/actor/ffda/primaryFilename           output/imag_primary_Hy.mhd
/gate/actor/ffda/rayleighFilename          output/imag_rayleigh_Hy.mhd
/gate/actor/ffda/comptonFilename           output/imag_compton_Hy.mhd
/gate/actor/ffda/fluorescenceFilename      output/imag_fluorescence_Hy.mhd
/gate/actor/ffda/secondaryFilename         output/imag_secondary_Hy.mhd
/gate/actor/ffda/materialMuFilename        output/imag_materialMu.mhd
/gate/actor/ffda/saveEveryNSeconds         120


# find source if gps. --> keep the first one.
# assumption : ponctuel (focuspoint ou centre)


# -----------------------------------------------------
# Complete fluence of gamma
/gate/actor/addActor FluenceActor                     DetectorActor
/gate/actor/DetectorActor/save                        output/imag_fluenceControl_Mc.mhd
/gate/actor/DetectorActor/attachTo                    DetectorPlane
/gate/actor/DetectorActor/responseDetectorFilename    data/imagXresponseDetector.txt
/gate/actor/DetectorActor/separateScatteringFilename  output/imag_fluenceControlSecondary_Mc.mhd
/gate/actor/DetectorActor/stepHitType                 pre
/gate/actor/DetectorActor/setResolution               224 224 1
/gate/actor/DetectorActor/enableScatter               true
/gate/actor/DetectorActor/saveEveryNSeconds           120

# -----------------------------------------------------
# Save particles stats 
/gate/actor/addActor  SimulationStatisticActor stat
/gate/actor/stat/save output/tiro200_glab_stats_Hy.txt
/gate/actor/stat/saveEveryNSeconds 20

#=====================================================
# BEAM
#=====================================================

/gate/source/addSource mybeam gps
/control/execute mac/beam-iMagX100keV.mac


#/vis/open HepRepXML


#=====================================================
# MAIN
#=====================================================

# DEBUG
#/tracking/verbose 1
#/tracking/verbose 1

/gate/run/initialize

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

/gate/application/setTimeSlice 1 s
/gate/application/setTimeStart 0 s
/gate/application/setTimeStop 1 s
#/gate/application/setTimeStop 3 s

/gate/application/noGlobalOutput
/gate/run/enableGlobalOutput false

# PARTICLE
/gate/application/setTotalNumberOfPrimaries 10000000
/gate/application/start
