#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# Example of CT imaging.

#-------------------oooooOOOOO00000OOOOOooooo---------------------#

#=====================================================
# VERBOSE and VISUALISATION 
#=====================================================

/control/execute mac/verbose.mac
#/control/execute mac/visu.mac

#=====================================================
# GEOMETRY
#=====================================================

# World
/gate/geometry/setMaterialDatabase data/GateMaterials.db
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    3 m
/gate/world/geometry/setYLength    3 m
/gate/world/geometry/setZLength    3 m

# Insert phantom
#/control/execute mac/catphan.mac
/control/execute mac/patient.mac

# Bidon 
# /gate/world/daughters/name             Bidon
# /gate/world/daughters/insert           box
# /gate/Bidon/geometry/setXLength        500 mm
# /gate/Bidon/geometry/setYLength        500 mm
# /gate/Bidon/geometry/setZLength        100 mm
# /gate/Bidon/placement/setTranslation   100 0 0 mm
# /gate/Bidon/placement/setRotationAxis  0 1 0
# /gate/Bidon/placement/setRotationAngle 45 deg
# /gate/Bidon/setMaterial                Air
# /gate/Bidon/vis/setVisible             1
# /gate/Bidon/vis/setColor               red

# Detection plane
/gate/world/daughters/name                     DetectorPlane
/gate/world/daughters/insert                   box
/gate/DetectorPlane/geometry/setXLength        1024 mm
/gate/DetectorPlane/geometry/setYLength        1024 mm
/gate/DetectorPlane/geometry/setZLength        1 nm
/gate/DetectorPlane/placement/setTranslation   0 0 -536 mm
/gate/DetectorPlane/placement/setRotationAxis  0 1 0
/gate/DetectorPlane/placement/setRotationAngle 0 deg
/gate/DetectorPlane/setMaterial                Air
/gate/DetectorPlane/vis/setVisible             1
/gate/DetectorPlane/vis/setColor               yellow

#=====================================================
# PHYSIC
#=====================================================

#/control/execute mac/Physicslist_std_no_e.mac
#/control/execute mac/Physicslist_Penelope_no_e.mac
/control/execute mac/Physicslist_Livermore_no_e.mac

#PhysicsList to activate Fluorescence
#/gate/physics/addPhysicsList emlivermore
#/process/em/fluo  true
#/process/em/auger true

# NOTE: if you use heavy materials as target you should 
# reduce the SetCutInRegion for your particle (e.g. 10nm)

# Be sure there is no e- 
/gate/physics/Gamma/SetCutInRegion      world 10 m
/gate/physics/Electron/SetCutInRegion   world 10 m
/gate/physics/Positron/SetCutInRegion   world 10 m

/gate/physics/displayCuts

#=====================================================
# DETECTORS
#=====================================================

# -----------------------------------------------------
# timing
/gate/actor/addActor  TimeActor statt
/gate/actor/statt/enableDetailedStats false
/gate/actor/statt/save output/time.txt

# Scatter Order Track Information (soti)
/gate/actor/addActor                   ScatterOrderTrackInformationActor soti
/gate/actor/soti/attachTo              world

# -----------------------------------------------------
# Hybrid ForcedDetection Actor (hfda)
/gate/actor/addActor                   HybridForcedDetectionActor hfda
/gate/actor/hfda/attachTo              world
/gate/actor/hfda/setDetector           DetectorPlane
/gate/actor/hfda/setDetectorResolution 256 256
/gate/actor/hfda/geometryFilename      output/geometry.xml
/gate/actor/hfda/primaryFilename       output/primary%.04d.mha
/gate/actor/hfda/rayleighFilename      output/rayleigh%.04d.mha
/gate/actor/hfda/comptonFilename       output/compton%.04d.mha
/gate/actor/hfda/fluorescenceFilename  output/fluorescence%.04d.mha
/gate/actor/hfda/secondaryFilename     output/secondary%.04d.mha
/gate/actor/hfda/totalFilename         output/total%.04d.mha
/gate/actor/hfda/materialMuFilename    output/materialMu.mha
/gate/actor/hfda/attenuationFilename   output/attenuation%.04d.mha
/gate/actor/hfda/flatFieldFilename     output/flatField%.04d.mha
/gate/actor/hfda/saveEveryNSeconds     120
#/gate/actor/hfda/singleInteractionFilename  output/single{ZDISTANCE}.mha
/gate/actor/hfda/singleInteractionType      Compton
/gate/actor/hfda/singleInteractionPosition  0 0 {ZDISTANCE} cm
/gate/actor/hfda/singleInteractionDirection 0 0 -1
/gate/actor/hfda/singleInteractionEnergy    70 keV
/gate/actor/hfda/singleInteractionZ         7
/gate/actor/hfda/phaseSpaceFilename         output/interactions.root


# find source if gps. --> keep the first one.
# assumption : ponctuel (focuspoint ou centre)

# -----------------------------------------------------
# Complete fluence of gamma
/gate/actor/addActor FluenceActor                  DetectorActor
/gate/actor/DetectorActor/save                     output/fluence%04d.mha
/gate/actor/DetectorActor/scatterOrderFilename     output/fluence%04d_%04d.mha
/gate/actor/DetectorActor/attachTo                 DetectorPlane
/gate/actor/DetectorActor/stepHitType              pre
/gate/actor/DetectorActor/setResolution            256 256 1
/gate/actor/DetectorActor/enableScatter            true
/gate/actor/DetectorActor/saveEveryNSeconds        120
#/gate/actor/DetectorActor/responseDetectorFilename data/responseDetector.txt

# -----------------------------------------------------
# Save particles stats 
/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/stats.txt
/gate/actor/stat/saveEveryNSeconds 120

#=====================================================
# BEAM
#=====================================================

/gate/source/addSource mybeam gps
#/control/execute mac/beam-mono.mac
#/control/execute mac/beam-iMagX-mono.mac
#/control/execute mac/beam-iMagX120keV.mac
#/control/execute mac/beam-iMagX80keV.mac
/control/execute mac/beam-with-spektrum.mac

#=====================================================
# MAIN
#=====================================================

# DEBUG
#/tracking/verbose 1
#/tracking/verbose 1

/gate/run/initialize

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

/gate/application/setTimeSlice 1 s
/gate/application/setTimeStart 0 s
/gate/application/setTimeStop 1 s
#/gate/application/setTimeStop 360 s

/gate/application/noGlobalOutput
/gate/run/enableGlobalOutput false

# PARTICLE
/gate/application/setTotalNumberOfPrimaries 100
/gate/application/start
