

/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel LivermoreModel

/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel LivermoreModel

/gate/physics/addProcess RayleighScattering
/gate/physics/processes/RayleighScattering/setModel LivermoreModel

/gate/physics/addProcess GammaConversion
/gate/physics/processes/GammaConversion/setModel LivermoreModel

