# ----------------------------------------------------
# the following actor regularly store the current number of
# event/track/step in a file

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/saveEveryNSeconds 3600

## The following macro is set in the main files
# /gate/actor/stat/save output/XXXX

# ----------------------------------------------------
# the following actor stores 3D distributions of
# dose/edep/uncertainty/nbHit into files (hdr image file format)

/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/attachTo    	   patient
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 mm
/gate/actor/doseDistribution/setVoxelSize          4. 4. 4. mm
/gate/actor/doseDistribution/saveEveryNSeconds     7200
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableDose            true
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/setResetDataAtEachRunFlag    true
/gate/actor/doseDistribution/setOverWriteFilesFlag    false
## The following macro is set in the main files
#/gate/actor/doseDistribution/save  output/XXXX

# 
/gate/actor/addActor     ImageDeformActor A
/gate/actor/A/attachTo   patient
/gate/actor/A/setPDFFile    	   data/pdf.txt

