
#=====================================
#    Electromagnetic  processes
#=====================================

#=============
# For Leptons
#=============

/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel

/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel StandardModel

/gate/physics/addProcess GammaConversion
/gate/physics/processes/GammaConversion/setModel StandardModel

/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/processes/ElectronIonisation/setModel StandardModel e+
/gate/physics/processes/ElectronIonisation/setStepFunction e+ 0.2 0.1 mm
/gate/physics/processes/ElectronIonisation/setStepFunction e- 0.2 0.1 mm
/gate/physics/processes/ElectronIonisation/setLinearLossLimit electron 0.01

/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+

/gate/physics/addProcess PositronAnnihilation

/gate/physics/addProcess eMultipleScattering
/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e- distanceToBoundary
/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e+ distanceToBoundary

#=========
# Options
#=========

/gate/physics/setEMin 0.1 keV
/gate/physics/setEMax 10 GeV
/gate/physics/setDEDXBinning 350
/gate/physics/setLambdaBinning 350

